print("A: about to construct QCalendarWidget");
var cal = new QCalendarWidget();
print("B: QCalendarWidget ok; QDateEdit next");
var de = new QDateEdit();
print("C: QDateEdit ok; QTextCharFormat next");
var f = new QTextCharFormat();
print("D: QTextCharFormat ok; QComboBox next");
var cb = new QComboBox();
print("E: QComboBox ok; QLocale next");
var loc = new QLocale("zh_CN");
print("F: QLocale ok; QGroupBox next");
var gb = new QGroupBox("test");
print("G: all constructions ok");
