var lines = [];
var h = new QXmlDefaultHandler();
lines.push("h.startElement=" + typeof h.startElement);
lines.push("h.characters=" + typeof h.characters);
var p = "D:/OpenSource/qcad-3.30.1.0/scripts/CrosshairCursor.png";
lines.push("cursorPng.exists=" + new QFile(p).exists());
var b = new QBitmap(p, "PNG");
lines.push("bitmap.isNull=" + b.isNull() + " size=" + b.width() + "x" + b.height());
var m = new QBitmap("D:/OpenSource/qcad-3.30.1.0/scripts/CrosshairCursorMask.png", "PNG");
lines.push("mask.isNull=" + m.isNull() + " size=" + m.width() + "x" + m.height());
var c = new QCursor(b, m, 15, 15);
lines.push("QCursor(bitmap,mask)=" + typeof c);
var f = new QFile("D:/OpenSource/qtscriptgenerator-master/examples/_qobject_probe_out.txt");
f.open(QIODevice.OpenMode(QIODevice.WriteOnly, QIODevice.Truncate));
var ts = new QTextStream(f); ts.writeString(lines.join("\n")); ts.flush(); f.close();
