/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * Signals
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractanimation.jsx";
import "qt/qabstractbutton.jsx";
import "qt/qabstractitemdelegate.jsx";
import "qt/qabstractsocket.jsx";
import "qt/qaction.jsx";
import "qt/qbrush.jsx";
import "qt/qcolor.jsx";
import "qt/qclipboard.jsx";
import "qt/qdoublevalidator.jsx";
import "qt/qdate.jsx";
import "qt/qdockwidget.jsx";
import "qt/qfont.jsx";
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsblureffect.jsx";
import "qt/qheaderview.jsx";
import "qt/qicon.jsx";
import "qt/qimagereader.jsx";
import "qt/qitemselection.jsx";
import "qt/qlistwidgetitem.jsx";
import "qt/qlocalsocket.jsx";
import "qt/qmdisubwindow.jsx";
import "qt/qmodelindex.jsx";
import "qt/qmovie.jsx";
import "qt/qnetworkproxy.jsx";
import "qt/qauthenticator.jsx";
import "qt/qnetworkaccessmanager.jsx";
import "qt/qnetworkreply.jsx";
import "qt/qnetworkrequest.jsx";
import "qt/qobject.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qprinter.jsx";
import "qt/qprocess.jsx";
import "qt/qrect.jsx";
import "qt/qrectf.jsx";
import "qt/qsessionmanager.jsx";
import "qt/qsize.jsx";
import "qt/qsqlrecord.jsx";
import "qt/qsslerror.jsx";
import "qt/qsslsocket.jsx";
import "qt/qstandarditem.jsx";
import "qt/qsystemtrayicon.jsx";
import "qt/qtablewidgetitem.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextcursor.jsx";
import "qt/qtime.jsx";
import "qt/qtimeline.jsx";
import "qt/qtreewidgetitem.jsx";
import "qt/qundostack.jsx";
import "qt/qurl.jsx";
import "qt/qwebframe.jsx";
import "qt/qwidget.jsx";
import "qt/qt.jsx";
