/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * Signals
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractanimation.jsx";
import "qt/qabstractbutton.jsx";
import "qt/qabstractitemdelegate.jsx";
import "qt/qabstractsocket.jsx";
import "qt/qaction.jsx";
import "qt/qbrush.jsx";
import "qt/qcolor.jsx";
import "qt/qclipboard.jsx";
import "qt/qdoublevalidator.jsx";
import "qt/qdate.jsx";
import "qt/qdockwidget.jsx";
import "qt/qfont.jsx";
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsblureffect.jsx";
import "qt/qheaderview.jsx";
import "qt/qicon.jsx";
import "qt/qimagereader.jsx";
import "qt/qitemselection.jsx";
import "qt/qlistwidgetitem.jsx";
import "qt/qlocalsocket.jsx";
import "qt/qmdisubwindow.jsx";
import "qt/qmodelindex.jsx";
import "qt/qmovie.jsx";
import "qt/qnetworkproxy.jsx";
import "qt/qauthenticator.jsx";
import "qt/qnetworkaccessmanager.jsx";
import "qt/qnetworkreply.jsx";
import "qt/qnetworkrequest.jsx";
import "qt/qobject.jsx";
import "qt/qpoint.jsx";
import "qt/qpointf.jsx";
import "qt/qprinter.jsx";
import "qt/qprocess.jsx";
import "qt/qrect.jsx";
import "qt/qrectf.jsx";
import "qt/qsessionmanager.jsx";
import "qt/qsize.jsx";
import "qt/qsqlrecord.jsx";
import "qt/qsslerror.jsx";
import "qt/qsslsocket.jsx";
import "qt/qstandarditem.jsx";
import "qt/qsystemtrayicon.jsx";
import "qt/qtablewidgetitem.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextcursor.jsx";
import "qt/qtime.jsx";
import "qt/qtimeline.jsx";
import "qt/qtreewidgetitem.jsx";
import "qt/qundostack.jsx";
import "qt/qurl.jsx";
import "qt/qwebframe.jsx";
import "qt/qwidget.jsx";
import "qt/qt.jsx";
native __fake__ class QtJSXSignal {
    function connect(callback : () -> void): void;
    function disconnect(callback : () -> void): void;
}

native __fake__ class QtJSXQFontSignal {
    function connect(callback : (QFont) -> void): void;
    function disconnect(callback : (QFont) -> void): void;
}

native __fake__ class QtJSXQObjectSignal {
    function connect(callback : (QObject) -> void): void;
    function disconnect(callback : (QObject) -> void): void;
}

native __fake__ class QtJSXQPaletteSignal {
    function connect(callback : (QPalette) -> void): void;
    function disconnect(callback : (QPalette) -> void): void;
}

native __fake__ class QtJSXQRectSignal {
    function connect(callback : (QRect) -> void): void;
    function disconnect(callback : (QRect) -> void): void;
}

native __fake__ class QtJSXQRegExpSignal {
    function connect(callback : (RegExp) -> void): void;
    function disconnect(callback : (RegExp) -> void): void;
}

native __fake__ class QtJSXQSizeSignal {
    function connect(callback : (QSize) -> void): void;
    function disconnect(callback : (QSize) -> void): void;
}

native __fake__ class QtJSXQTextCursorSignal {
    function connect(callback : (QTextCursor) -> void): void;
    function disconnect(callback : (QTextCursor) -> void): void;
}

native __fake__ class QtJSXQUrlSignal {
    function connect(callback : (QUrl) -> void): void;
    function disconnect(callback : (QUrl) -> void): void;
}

native __fake__ class QtJSXQt_LayoutDirectionSignal {
    function connect(callback : (Qt_LayoutDirection) -> void): void;
    function disconnect(callback : (Qt_LayoutDirection) -> void): void;
}

native __fake__ class QtJSXQt_QDoubleValidator_NotationSignal {
    function connect(callback : (Qt_QDoubleValidator_Notation) -> void): void;
    function disconnect(callback : (Qt_QDoubleValidator_Notation) -> void): void;
}

native __fake__ class QtJSXQt_QImageReader_ImageReaderErrorSignal {
    function connect(callback : (Qt_QImageReader_ImageReaderError) -> void): void;
    function disconnect(callback : (Qt_QImageReader_ImageReaderError) -> void): void;
}

native __fake__ class QtJSXQt_QMovie_MovieStateSignal {
    function connect(callback : (Qt_QMovie_MovieState) -> void): void;
    function disconnect(callback : (Qt_QMovie_MovieState) -> void): void;
}

native __fake__ class QtJSXboolSignal {
    function connect(callback : (boolean) -> void): void;
    function disconnect(callback : (boolean) -> void): void;
}

native __fake__ class QtJSXdoubleSignal {
    function connect(callback : (number) -> void): void;
    function disconnect(callback : (number) -> void): void;
}

native __fake__ class QtJSXintSignal {
    function connect(callback : (int) -> void): void;
    function disconnect(callback : (int) -> void): void;
}

native __fake__ class QtJSXintintintSignal {
    function connect(callback : (int, int, int) -> void): void;
    function disconnect(callback : (int, int, int) -> void): void;
}

