/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractItemView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qabstractscrollarea.jsx";
import "qt/qitemselection.jsx";
import "qt/qitemselectionmodel.jsx";
import "qt/qstyleoptionviewitem.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QAbstractItemView_SelectionMode {}

final native class Qt_QAbstractItemView_DragDropMode {}

native class QAbstractItemView extends QAbstractScrollArea
{
    function constructor (parent : QWidget);

    static const NoSelection : Qt_QAbstractItemView_SelectionMode;
    static const SingleSelection : Qt_QAbstractItemView_SelectionMode;
    static const MultiSelection : Qt_QAbstractItemView_SelectionMode;
    static const ExtendedSelection : Qt_QAbstractItemView_SelectionMode;
    static const ContiguousSelection : Qt_QAbstractItemView_SelectionMode;
    static function SelectionMode(value : Qt_QAbstractItemView_SelectionMode) : Qt_QAbstractItemView_SelectionMode;

    static const NoDragDrop : Qt_QAbstractItemView_DragDropMode;
    static const DragOnly : Qt_QAbstractItemView_DragDropMode;
    static const DropOnly : Qt_QAbstractItemView_DragDropMode;
    static const DragDrop : Qt_QAbstractItemView_DragDropMode;
    static const InternalMove : Qt_QAbstractItemView_DragDropMode;
    static function DragDropMode(value : Qt_QAbstractItemView_DragDropMode) : Qt_QAbstractItemView_DragDropMode;

    // Methods
    function doAutoScroll () : void;
    function executeDelayedItemsLayout () : void;
    function itemDelegate () : QAbstractItemDelegate;
    function keyboardSearch (search : string) : void;
    function resetHorizontalScrollMode () : void;
    function resetVerticalScrollMode () : void;
    function scheduleDelayedItemsLayout () : void;
    function selectionModel () : QItemSelectionModel;
    function setItemDelegate (delegate : QAbstractItemDelegate) : void;
    function setSelectionModel (selectionModel : QItemSelectionModel) : void;
    function startAutoScroll () : void;
    function stopAutoScroll () : void;
    function viewOptions () : QStyleOptionViewItem;

    // Slots
    function clearSelection () : void;
    function closeEditor (editor : QWidget, hint : Qt_QAbstractItemDelegate_EndEditHint) : void;
    function commitData (editor : QWidget) : void;
    function doItemsLayout () : void;
    function reset () : void;
    function scrollToBottom () : void;
    function scrollToTop () : void;
    function selectAll () : void;
    function selectionChanged (selected : QItemSelection, deselected : QItemSelection) : void;
    function updateEditorData () : void;
    function updateEditorGeometries () : void;
    function updateGeometries () : void;

    // Signals
    var viewportEntered : QtJSXSignal;

    // Instance Properties
    var editTriggers : Qt_QAbstractItemView_EditTriggers;
    var dragDropMode : Qt_QAbstractItemView_DragDropMode;
    var selectionMode : Qt_QAbstractItemView_SelectionMode;
    var selectionBehavior : Qt_QAbstractItemView_SelectionBehavior;
    var verticalScrollMode : Qt_QAbstractItemView_ScrollMode;
    var horizontalScrollMode : Qt_QAbstractItemView_ScrollMode;
}
