/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractState class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qstate.jsx";
import "qt/qstatemachine.jsx";
import "qt/_signals.jsx";

native class QAbstractState
{

    // Methods
    function machine () : QStateMachine;
    function onEntry (event : QEvent) : void;
    function onExit (event : QEvent) : void;
    function parentState () : QState;

    // Signals
    var activeChanged : QtJSXboolSignal;

    // Instance Properties
    var active : boolean;
}
