/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractGraphicsShapeItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";

native class QAbstractGraphicsShapeItem extends QGraphicsItem
{
    function constructor (parent : QGraphicsItem);
}
