/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractItemDelegate class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QAbstractItemDelegate_EndEditHint {}

native class QAbstractItemDelegate
{

    static const NoHint : Qt_QAbstractItemDelegate_EndEditHint;
    static const EditNextItem : Qt_QAbstractItemDelegate_EndEditHint;
    static const EditPreviousItem : Qt_QAbstractItemDelegate_EndEditHint;
    static const SubmitModelCache : Qt_QAbstractItemDelegate_EndEditHint;
    static const RevertModelCache : Qt_QAbstractItemDelegate_EndEditHint;
    static function EndEditHint(value : Qt_QAbstractItemDelegate_EndEditHint) : Qt_QAbstractItemDelegate_EndEditHint;

    // Signals
    var closeEditor : QtJSXQWidgetQt_QAbstractItemDelegate_EndEditHintSignal;
    var commitData : QtJSXQWidgetSignal;
}
