/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractSlider class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QAbstractSlider_SliderAction {}

native class QAbstractSlider extends QWidget
{
    function constructor (parent : QWidget);

    static const SliderNoAction : Qt_QAbstractSlider_SliderAction;
    static const SliderSingleStepAdd : Qt_QAbstractSlider_SliderAction;
    static const SliderSingleStepSub : Qt_QAbstractSlider_SliderAction;
    static const SliderPageStepAdd : Qt_QAbstractSlider_SliderAction;
    static const SliderPageStepSub : Qt_QAbstractSlider_SliderAction;
    static const SliderToMinimum : Qt_QAbstractSlider_SliderAction;
    static const SliderToMaximum : Qt_QAbstractSlider_SliderAction;
    static const SliderMove : Qt_QAbstractSlider_SliderAction;
    static function SliderAction(value : Qt_QAbstractSlider_SliderAction) : Qt_QAbstractSlider_SliderAction;

    // Methods
    function repeatAction () : Qt_QAbstractSlider_SliderAction;
    function triggerAction (action : Qt_QAbstractSlider_SliderAction) : void;

    // Signals
    var sliderPressed : QtJSXSignal;
    var sliderReleased : QtJSXSignal;
}
