/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractSocket class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qauthenticator.jsx";
import "qt/qhostaddress.jsx";
import "qt/qnetworkproxy.jsx";
import "qt/_signals.jsx";

final native class Qt_QAbstractSocket_SocketType {}

final native class Qt_QAbstractSocket_PauseMode {}

native class QAbstractSocket
{
    function constructor ();

    static const UnknownSocketType : Qt_QAbstractSocket_SocketType;
    static const TcpSocket : Qt_QAbstractSocket_SocketType;
    static const UdpSocket : Qt_QAbstractSocket_SocketType;
    static const SctpSocket : Qt_QAbstractSocket_SocketType;
    static function SocketType(value : Qt_QAbstractSocket_SocketType) : Qt_QAbstractSocket_SocketType;

    static const PauseNever : Qt_QAbstractSocket_PauseMode;
    static const PauseOnSslErrors : Qt_QAbstractSocket_PauseMode;
    static function PauseMode(value : Qt_QAbstractSocket_PauseMode) : Qt_QAbstractSocket_PauseMode;

    // Methods
    function abort () : void;
    function disconnectFromHost () : void;
    function localAddress () : QHostAddress;
    function peerAddress () : QHostAddress;
    function peerName () : string;
    function protocolTag () : string;
    function proxy () : QNetworkProxy;
    function resume () : void;
    function setLocalAddress (address : QHostAddress) : void;
    function setPeerAddress (address : QHostAddress) : void;
    function setPeerName (name : string) : void;
    function setProtocolTag (tag : string) : void;
    function setProxy (networkProxy : QNetworkProxy) : void;
    function setSocketError (socketError : Qt_QAbstractSocket_SocketError) : void;
    function setSocketOption (option : Qt_QAbstractSocket_SocketOption, value : variant) : void;
    function setSocketState (state : Qt_QAbstractSocket_SocketState) : void;
    function socketOption (option : Qt_QAbstractSocket_SocketOption) : variant;
    function socketType () : Qt_QAbstractSocket_SocketType;
    function state () : Qt_QAbstractSocket_SocketState;

    // Signals
    var connected : QtJSXSignal;
    var disconnected : QtJSXSignal;
    var error : QtJSXQt_QAbstractSocket_SocketErrorSignal;
    var errorOccurred : QtJSXQt_QAbstractSocket_SocketErrorSignal;
    var hostFound : QtJSXSignal;
    var proxyAuthenticationRequired : QtJSXQNetworkProxyQAuthenticatorSignal;
    var stateChanged : QtJSXQt_QAbstractSocket_SocketStateSignal;
}
