/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractScrollArea class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qscrollbar.jsx";
import "qt/qwidget.jsx";

native class QAbstractScrollArea extends QFrame
{
    function constructor (parent : QWidget);

    // Methods
    function cornerWidget () : QWidget;
    function horizontalScrollBar () : QScrollBar;
    function setCornerWidget (widget : QWidget) : void;
    function setHorizontalScrollBar (scrollbar : QScrollBar) : void;
    function setVerticalScrollBar (scrollbar : QScrollBar) : void;
    function setViewport (widget : QWidget) : void;
    function setupViewport (viewport : QWidget) : void;
    function verticalScrollBar () : QScrollBar;
    function viewport () : QWidget;
}
