/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractPrintDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qprinter.jsx";

native class QAbstractPrintDialog
{
    function constructor ();

    // Methods
    function printer () : QPrinter;
}
