/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractTransition class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractanimation.jsx";
import "qt/qabstractstate.jsx";
import "qt/qevent.jsx";
import "qt/qstate.jsx";
import "qt/qstatemachine.jsx";

native class QAbstractTransition
{
    function constructor (sourceState : QState);

    // Methods
    function addAnimation (animation : QAbstractAnimation) : void;
    function animations () : QAbstractAnimation[];
    function eventTest (event : QEvent) : boolean;
    function machine () : QStateMachine;
    function onTransition (event : QEvent) : void;
    function removeAnimation (animation : QAbstractAnimation) : void;

    // Instance Properties
    var sourceState : QState;
    var targetState : QAbstractState;
    var targetStates : QAbstractAnimation[];
}
