/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractNetworkCache class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qnetworkcachemetadata.jsx";

native class QAbstractNetworkCache
{
    function constructor ();

    // Methods
    function updateMetaData (metaData : QNetworkCacheMetaData) : void;

    // Slots
    function clear () : void;
}
