/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractSpinBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlineedit.jsx";
import "qt/qstyleoptionspinbox.jsx";
import "qt/qt.jsx";
import "qt/qtimerevent.jsx";
import "qt/qvalidator.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QAbstractSpinBox_StepEnabledFlag {}

final native class Qt_QAbstractSpinBox_StepEnabled {}

final native class Qt_QAbstractSpinBox_ButtonSymbols {}

final native class Qt_QAbstractSpinBox_CorrectionMode {}

native class QAbstractSpinBox extends QWidget
{
    function constructor (parent : QWidget);

    static const StepNone : Qt_QAbstractSpinBox_StepEnabledFlag;
    static const StepUpEnabled : Qt_QAbstractSpinBox_StepEnabledFlag;
    static const StepDownEnabled : Qt_QAbstractSpinBox_StepEnabledFlag;
    static function StepEnabledFlag(value : Qt_QAbstractSpinBox_StepEnabledFlag) : Qt_QAbstractSpinBox_StepEnabledFlag;
    static function StepEnabled(...value : Qt_QAbstractSpinBox_StepEnabledFlag) : Qt_QAbstractSpinBox_StepEnabled;

    static const UpDownArrows : Qt_QAbstractSpinBox_ButtonSymbols;
    static const PlusMinus : Qt_QAbstractSpinBox_ButtonSymbols;
    static const NoButtons : Qt_QAbstractSpinBox_ButtonSymbols;
    static function ButtonSymbols(value : Qt_QAbstractSpinBox_ButtonSymbols) : Qt_QAbstractSpinBox_ButtonSymbols;

    static const CorrectToPreviousValue : Qt_QAbstractSpinBox_CorrectionMode;
    static const CorrectToNearestValue : Qt_QAbstractSpinBox_CorrectionMode;
    static function CorrectionMode(value : Qt_QAbstractSpinBox_CorrectionMode) : Qt_QAbstractSpinBox_CorrectionMode;

    // Methods
    function clear () : void;
    function fixup (input : string) : void;
    function initStyleOption (option : QStyleOptionSpinBox) : void;
    function interpretText () : void;
    function lineEdit () : QLineEdit;
    function selectAll () : void;
    function setLineEdit (edit : QLineEdit) : void;
    function stepBy (steps : int) : void;
    function stepDown () : void;
    function stepEnabled () : Qt_QAbstractSpinBox_StepEnabled;
    function stepUp () : void;
    function timerEvent (event : QTimerEvent) : void;
    function validate (input : string, pos : int) : Qt_QValidator_State;

    // Signals
    var editingFinished : QtJSXSignal;

    // Instance Properties
    var wrapping : boolean;
    var frame : boolean;
    var alignment : Qt_Alignment;
    var readOnly : boolean;
    var buttonSymbols : Qt_QAbstractSpinBox_ButtonSymbols;
    var specialValueText : string;
    var text : string;
    var accelerated : boolean;
    var correctionMode : Qt_QAbstractSpinBox_CorrectionMode;
    var acceptableInput : boolean;
    var keyboardTracking : boolean;
    var showGroupSeparator : boolean;
}
