/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAbstractButton class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbuttongroup.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QAbstractButton extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function checkStateSet () : void;
    function group () : QButtonGroup;
    function nextCheckState () : void;

    // Slots
    function click () : void;
    function toggle () : void;

    // Signals
    var pressed : QtJSXSignal;
    var released : QtJSXSignal;

    // Instance Properties
    var text : string;
}
