/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QAction class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qactiongroup.jsx";
import "qt/qgraphicswidget.jsx";
import "qt/qmenu.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QAction_ActionEvent {}

final native class Qt_QAction_MenuRole {}

native class QAction
{
    function constructor ();

    static const Trigger : Qt_QAction_ActionEvent;
    static const Hover : Qt_QAction_ActionEvent;
    static function ActionEvent(value : Qt_QAction_ActionEvent) : Qt_QAction_ActionEvent;

    static const NoRole : Qt_QAction_MenuRole;
    static const TextHeuristicRole : Qt_QAction_MenuRole;
    static const ApplicationSpecificRole : Qt_QAction_MenuRole;
    static const AboutQtRole : Qt_QAction_MenuRole;
    static const AboutRole : Qt_QAction_MenuRole;
    static const PreferencesRole : Qt_QAction_MenuRole;
    static const QuitRole : Qt_QAction_MenuRole;
    static function MenuRole(value : Qt_QAction_MenuRole) : Qt_QAction_MenuRole;

    // Methods
    function actionGroup () : QActionGroup;
    function activate (event : Qt_QAction_ActionEvent) : void;
    function associatedGraphicsWidgets () : QGraphicsWidget[];
    function associatedWidgets () : QWidget[];
    function data () : variant;
    function menu () : QMenu;
    function parentWidget () : QWidget;
    function setActionGroup (group : QActionGroup) : void;
    function setData (var_ : variant) : void;
    function setMenu (menu : QMenu) : void;

    // Slots
    function hover () : void;
    function toggle () : void;
    function trigger () : void;

    // Signals
    var changed : QtJSXSignal;
    var hovered : QtJSXSignal;

    // Instance Properties
    var text : string;
    var iconText : string;
    var toolTip : string;
    var statusTip : string;
    var whatsThis : string;
    var menuRole : Qt_QAction_MenuRole;
    var priority : Qt_QAction_Priority;
}
