/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QActionGroup class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qicon.jsx";
import "qt/qobject.jsx";
import "qt/_signals.jsx";

native class QActionGroup extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function actions () : QAction[];
    function addAction (a : QAction) : QAction;
    function addAction (icon : QIcon, text : string) : QAction;
    function addAction (text : string) : QAction;
    function checkedAction () : QAction;
    function isExclusive () : boolean;
    function removeAction (a : QAction) : void;

    // Slots
    function setDisabled (b : boolean) : void;
    function setExclusive (arg__1 : boolean) : void;

    // Signals
    var hovered : QtJSXQActionSignal;
    var triggered : QtJSXQActionSignal;

    // Instance Properties
    var enabled : boolean;
    var visible : boolean;
}
