/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QActionGroup class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/_signals.jsx";

native class QActionGroup
{
    function constructor ();

    // Methods
    function actions () : QAction[];
    function addAction (a : QAction) : QAction;
    function addAction (text : string) : QAction;
    function checkedAction () : QAction;
    function removeAction (a : QAction) : void;

    // Signals
    var hovered : QtJSXQActionSignal;
    var triggered : QtJSXQActionSignal;
}
