/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QApplication class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdesktopwidget.jsx";
import "qt/qstyle.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QApplication_ColorSpec {}

native class QApplication
{
    function constructor ();

    // Static Members
    static function activeModalWidget () : QWidget;
    static function activePopupWidget () : QWidget;
    static function activeWindow () : QWidget;
    static function allWidgets () : QWidget[];
    static function beep () : void;
    static function desktop () : QDesktopWidget;
    static function focusWidget () : QWidget;
    static function setActiveWindow (act : QWidget) : void;
    static function setStyle (arg__1 : QStyle) : void;
    static function style () : QStyle;
    static function topLevelWidgets () : QWidget[];

    static const NormalColor : Qt_QApplication_ColorSpec;
    static const CustomColor : Qt_QApplication_ColorSpec;
    static const ManyColor : Qt_QApplication_ColorSpec;
    static function ColorSpec(value : Qt_QApplication_ColorSpec) : Qt_QApplication_ColorSpec;

    // Slots
    function aboutQt () : void;
    function closeAllWindows () : void;

    // Signals
    var focusChanged : QtJSXQWidgetQWidgetSignal;

    // Instance Properties
    var styleSheet : string;
}
