/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QBitmap class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpixmap.jsx";

native class QBitmap
{
    function constructor ();
    function constructor (other : QBitmap);
    function constructor (arg__1 : QPixmap);

    // Methods
    function operator_assign (other : QBitmap) : QBitmap;
}
