/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QBoxLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";
import "qt/qspaceritem.jsx";
import "qt/qwidget.jsx";

final native class Qt_QBoxLayout_Direction {}

native class QBoxLayout extends QLayout
{
    function constructor (arg__1 : Qt_QBoxLayout_Direction, parent : QWidget);

    static const LeftToRight : Qt_QBoxLayout_Direction;
    static const RightToLeft : Qt_QBoxLayout_Direction;
    static const TopToBottom : Qt_QBoxLayout_Direction;
    static const BottomToTop : Qt_QBoxLayout_Direction;
    static function Direction(value : Qt_QBoxLayout_Direction) : Qt_QBoxLayout_Direction;

    // Methods
    function addSpacerItem (spacerItem : QSpacerItem) : void;
    function direction () : Qt_QBoxLayout_Direction;
    function setDirection (arg__1 : Qt_QBoxLayout_Direction) : void;
}
