/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QButtonGroup class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractbutton.jsx";
import "qt/_signals.jsx";

native class QButtonGroup
{
    function constructor ();

    // Methods
    function buttons () : QAbstractButton[];
    function checkedButton () : QAbstractButton;
    function removeButton (arg__1 : QAbstractButton) : void;

    // Signals
    var buttonClicked : QtJSXQAbstractButtonSignal;
    var buttonPressed : QtJSXQAbstractButtonSignal;
    var buttonReleased : QtJSXQAbstractButtonSignal;
}
