/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QCalendarWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QCalendarWidget_HorizontalHeaderFormat {}

native class QCalendarWidget extends QWidget
{
    function constructor (parent : QWidget);

    static const NoHorizontalHeader : Qt_QCalendarWidget_HorizontalHeaderFormat;
    static const SingleLetterDayNames : Qt_QCalendarWidget_HorizontalHeaderFormat;
    static const ShortDayNames : Qt_QCalendarWidget_HorizontalHeaderFormat;
    static const LongDayNames : Qt_QCalendarWidget_HorizontalHeaderFormat;
    static function HorizontalHeaderFormat(value : Qt_QCalendarWidget_HorizontalHeaderFormat) : Qt_QCalendarWidget_HorizontalHeaderFormat;

    // Methods
    function updateCells () : void;

    // Slots
    function showNextMonth () : void;
    function showNextYear () : void;
    function showPreviousMonth () : void;
    function showPreviousYear () : void;
    function showSelectedDate () : void;
    function showToday () : void;

    // Signals
    var selectionChanged : QtJSXSignal;

    // Instance Properties
    var selectionMode : Qt_QCalendarWidget_SelectionMode;
    var horizontalHeaderFormat : Qt_QCalendarWidget_HorizontalHeaderFormat;
    var verticalHeaderFormat : Qt_QCalendarWidget_VerticalHeaderFormat;
}
