/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QCheckBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractbutton.jsx";
import "qt/qstyleoptionbutton.jsx";
import "qt/qwidget.jsx";

native class QCheckBox extends QAbstractButton
{
    function constructor (parent : QWidget);
    function constructor (text : string, parent : QWidget);

    // Methods
    function initStyleOption (option : QStyleOptionButton) : void;
}
