/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QClipboard class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qimage.jsx";
import "qt/qpixmap.jsx";
import "qt/_signals.jsx";

final native class Qt_QClipboard_Mode {}

native class QClipboard
{
    function constructor ();

    static const Clipboard : Qt_QClipboard_Mode;
    static const Selection : Qt_QClipboard_Mode;
    static const FindBuffer : Qt_QClipboard_Mode;
    static function Mode(value : Qt_QClipboard_Mode) : Qt_QClipboard_Mode;

    // Methods
    function clear (mode : Qt_QClipboard_Mode) : void;
    function image (mode : Qt_QClipboard_Mode) : QImage;
    function pixmap (mode : Qt_QClipboard_Mode) : QPixmap;
    function setImage (arg__1 : QImage, mode : Qt_QClipboard_Mode) : void;
    function setPixmap (arg__1 : QPixmap, mode : Qt_QClipboard_Mode) : void;
    function setText (arg__1 : string, mode : Qt_QClipboard_Mode) : void;
    function text (mode : Qt_QClipboard_Mode) : string;
    function text (subtype : string, mode : Qt_QClipboard_Mode) : string;

    // Signals
    var changed : QtJSXQt_QClipboard_ModeSignal;
    var dataChanged : QtJSXSignal;
    var findBufferChanged : QtJSXSignal;
    var selectionChanged : QtJSXSignal;
}
