/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QColorDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdialog.jsx";
import "qt/qwidget.jsx";

final native class Qt_QColorDialog_ColorDialogOption {}

final native class Qt_QColorDialog_ColorDialogOptions {}

native class QColorDialog extends QDialog
{
    function constructor (parent : QWidget);

    static const ShowAlphaChannel : Qt_QColorDialog_ColorDialogOption;
    static const NoButtons : Qt_QColorDialog_ColorDialogOption;
    static const DontUseNativeDialog : Qt_QColorDialog_ColorDialogOption;
    static function ColorDialogOption(value : Qt_QColorDialog_ColorDialogOption) : Qt_QColorDialog_ColorDialogOption;
    static function ColorDialogOptions(...value : Qt_QColorDialog_ColorDialogOption) : Qt_QColorDialog_ColorDialogOptions;

    // Instance Properties
    var options : Qt_QColorDialog_ColorDialogOptions;
}
