/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QColormap class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";

native class QColormap
{
    function constructor (colormap : QColormap);

    // Static Members
    static function cleanup () : void;
    static function initialize () : void;

    // Methods
    function colormap () : QColor[];
}
