/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QColumnView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qwidget.jsx";

native class QColumnView extends QAbstractItemView
{
    function constructor (parent : QWidget);

    // Methods
    function initializeColumn (column : QAbstractItemView) : void;
    function previewWidget () : QWidget;
    function setPreviewWidget (widget : QWidget) : void;
}
