/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QComboBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qabstractitemview.jsx";
import "qt/qcompleter.jsx";
import "qt/qlineedit.jsx";
import "qt/qstyleoptioncombobox.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QComboBox_InsertPolicy {}

final native class Qt_QComboBox_SizeAdjustPolicy {}

native class QComboBox extends QWidget
{
    function constructor (parent : QWidget);

    static const NoInsert : Qt_QComboBox_InsertPolicy;
    static const InsertAtTop : Qt_QComboBox_InsertPolicy;
    static const InsertAtCurrent : Qt_QComboBox_InsertPolicy;
    static const InsertAtBottom : Qt_QComboBox_InsertPolicy;
    static const InsertAfterCurrent : Qt_QComboBox_InsertPolicy;
    static const InsertBeforeCurrent : Qt_QComboBox_InsertPolicy;
    static const InsertAlphabetically : Qt_QComboBox_InsertPolicy;
    static function InsertPolicy(value : Qt_QComboBox_InsertPolicy) : Qt_QComboBox_InsertPolicy;

    static const AdjustToContents : Qt_QComboBox_SizeAdjustPolicy;
    static const AdjustToContentsOnFirstShow : Qt_QComboBox_SizeAdjustPolicy;
    static const AdjustToMinimumContentsLength : Qt_QComboBox_SizeAdjustPolicy;
    static const AdjustToMinimumContentsLengthWithIcon : Qt_QComboBox_SizeAdjustPolicy;
    static function SizeAdjustPolicy(value : Qt_QComboBox_SizeAdjustPolicy) : Qt_QComboBox_SizeAdjustPolicy;

    // Methods
    function addItem (text : string, userData : variant) : void;
    function addItems (texts : string[]) : void;
    function completer () : QCompleter;
    function hidePopup () : void;
    function initStyleOption (option : QStyleOptionComboBox) : void;
    function itemDelegate () : QAbstractItemDelegate;
    function lineEdit () : QLineEdit;
    function setCompleter (c : QCompleter) : void;
    function setItemDelegate (delegate : QAbstractItemDelegate) : void;
    function setLineEdit (edit : QLineEdit) : void;
    function setView (itemView : QAbstractItemView) : void;
    function showPopup () : void;
    function view () : QAbstractItemView;

    // Slots
    function clear () : void;
    function clearEditText () : void;
    function setEditText (text : string) : void;

    // Signals
    var activated : QtJSXQStringSignal;
    var currentIndexChanged : QtJSXQStringSignal;
    var currentTextChanged : QtJSXQStringSignal;
    var editTextChanged : QtJSXQStringSignal;
    var highlighted : QtJSXQStringSignal;
    var textActivated : QtJSXQStringSignal;
    var textHighlighted : QtJSXQStringSignal;

    // Instance Properties
    var currentText : string;
    var currentData : variant;
    var insertPolicy : Qt_QComboBox_InsertPolicy;
    var sizeAdjustPolicy : Qt_QComboBox_SizeAdjustPolicy;
    var placeholderText : string;
}
