/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QCompleter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QCompleter_CompletionMode {}

native class QCompleter
{
    function constructor ();

    static const PopupCompletion : Qt_QCompleter_CompletionMode;
    static const UnfilteredPopupCompletion : Qt_QCompleter_CompletionMode;
    static const InlineCompletion : Qt_QCompleter_CompletionMode;
    static function CompletionMode(value : Qt_QCompleter_CompletionMode) : Qt_QCompleter_CompletionMode;

    // Methods
    function currentCompletion () : string;
    function popup () : QAbstractItemView;
    function setPopup (popup : QAbstractItemView) : void;
    function setWidget (widget : QWidget) : void;
    function splitPath (path : string) : string[];
    function widget () : QWidget;

    // Signals
    var activated : QtJSXQStringSignal;
    var highlighted : QtJSXQStringSignal;

    // Instance Properties
    var completionPrefix : string;
    var modelSorting : Qt_QCompleter_ModelSorting;
    var completionMode : Qt_QCompleter_CompletionMode;
}
