/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QContextMenuEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qinputevent.jsx";

final native class Qt_QContextMenuEvent_Reason {}

native class QContextMenuEvent extends QInputEvent
{

    static const Mouse : Qt_QContextMenuEvent_Reason;
    static const Keyboard : Qt_QContextMenuEvent_Reason;
    static const Other : Qt_QContextMenuEvent_Reason;
    static function Reason(value : Qt_QContextMenuEvent_Reason) : Qt_QContextMenuEvent_Reason;

    // Methods
    function reason () : Qt_QContextMenuEvent_Reason;
}
