/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QConicalGradient class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgradient.jsx";

native class QConicalGradient extends QGradient
{
    function constructor ();
}
