/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QCryptographicHash class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qiodevice.jsx";

final native class Qt_QCryptographicHash_Algorithm {}

native class QCryptographicHash
{
    function constructor (method : Qt_QCryptographicHash_Algorithm);

    // Static Members
    static function hash (data : QByteArray, method : Qt_QCryptographicHash_Algorithm) : QByteArray;
    static function hashLength (method : Qt_QCryptographicHash_Algorithm) : int;

    static const Md4 : Qt_QCryptographicHash_Algorithm;
    static const Md5 : Qt_QCryptographicHash_Algorithm;
    static const Sha1 : Qt_QCryptographicHash_Algorithm;
    static const Sha224 : Qt_QCryptographicHash_Algorithm;
    static const Sha256 : Qt_QCryptographicHash_Algorithm;
    static const Sha384 : Qt_QCryptographicHash_Algorithm;
    static const Sha512 : Qt_QCryptographicHash_Algorithm;
    static const Keccak_224 : Qt_QCryptographicHash_Algorithm;
    static const Keccak_256 : Qt_QCryptographicHash_Algorithm;
    static const Keccak_384 : Qt_QCryptographicHash_Algorithm;
    static const Keccak_512 : Qt_QCryptographicHash_Algorithm;
    static const RealSha3_224 : Qt_QCryptographicHash_Algorithm;
    static const RealSha3_256 : Qt_QCryptographicHash_Algorithm;
    static const RealSha3_384 : Qt_QCryptographicHash_Algorithm;
    static const RealSha3_512 : Qt_QCryptographicHash_Algorithm;
    static function Algorithm(value : Qt_QCryptographicHash_Algorithm) : Qt_QCryptographicHash_Algorithm;

    // Methods
    function addData (device : QIODevice) : boolean;
    function addData (data : QByteArray) : void;
    function reset () : void;
    function result () : QByteArray;
}
