/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDateEdit class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdatetimeedit.jsx";
import "qt/qwidget.jsx";

native class QDateEdit extends QDateTimeEdit
{
    function constructor (parent : QWidget);
}
