/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDataWidgetMapper class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qwidget.jsx";

final native class Qt_QDataWidgetMapper_SubmitPolicy {}

native class QDataWidgetMapper
{
    function constructor ();

    static const AutoSubmit : Qt_QDataWidgetMapper_SubmitPolicy;
    static const ManualSubmit : Qt_QDataWidgetMapper_SubmitPolicy;
    static function SubmitPolicy(value : Qt_QDataWidgetMapper_SubmitPolicy) : Qt_QDataWidgetMapper_SubmitPolicy;

    // Methods
    function clearMapping () : void;
    function itemDelegate () : QAbstractItemDelegate;
    function removeMapping (widget : QWidget) : void;
    function setItemDelegate (delegate : QAbstractItemDelegate) : void;

    // Slots
    function revert () : void;
    function toFirst () : void;
    function toLast () : void;
    function toNext () : void;
    function toPrevious () : void;

    // Instance Properties
    var submitPolicy : Qt_QDataWidgetMapper_SubmitPolicy;
}
