/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDesktopWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QDesktopWidget extends QWidget
{
    function constructor ();

    // Signals
    var primaryScreenChanged : QtJSXSignal;
}
