/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDesktopServices class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QDesktopServices
{
    function constructor ();

    // Static Members
    static function unsetUrlHandler (scheme : string) : void;
}
