/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qobject.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QDialog_DialogCode {}

native class QDialog extends QWidget
{
    function constructor (parent : QWidget, f : Qt_WindowFlags);

    static const Rejected : Qt_QDialog_DialogCode;
    static const Accepted : Qt_QDialog_DialogCode;
    static function DialogCode(value : Qt_QDialog_DialogCode) : Qt_QDialog_DialogCode;

    // Methods
    function accept () : void;
    function adjustPosition (arg__1 : QWidget) : void;
    function done (arg__1 : int) : void;
    function eventFilter (arg__1 : QObject, arg__2 : QEvent) : boolean;
    function exec () : int;
    function open () : void;
    function reject () : void;
    function result () : int;
    function setResult (r : int) : void;
    function setVisible (visible : boolean) : void;

    // Signals
    var accepted : QtJSXSignal;
    var finished : QtJSXintSignal;
    var rejected : QtJSXSignal;

    // Instance Properties
    var sizeGripEnabled : boolean;
}
