/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QDialog_DialogCode {}

native class QDialog extends QWidget
{
    function constructor ();

    static const Rejected : Qt_QDialog_DialogCode;
    static const Accepted : Qt_QDialog_DialogCode;
    static function DialogCode(value : Qt_QDialog_DialogCode) : Qt_QDialog_DialogCode;

    // Methods
    function adjustPosition (arg__1 : QWidget) : void;

    // Slots
    function accept () : void;
    function open () : void;
    function reject () : void;

    // Signals
    var accepted : QtJSXSignal;
    var rejected : QtJSXSignal;
}
