/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDockWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qstyleoptiondockwidget.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QDockWidget_DockWidgetFeature {}

final native class Qt_QDockWidget_DockWidgetFeatures {}

native class QDockWidget extends QWidget
{
    function constructor ();

    static const NoDockWidgetFeatures : Qt_QDockWidget_DockWidgetFeature;
    static const DockWidgetClosable : Qt_QDockWidget_DockWidgetFeature;
    static const DockWidgetMovable : Qt_QDockWidget_DockWidgetFeature;
    static const DockWidgetFloatable : Qt_QDockWidget_DockWidgetFeature;
    static const AllDockWidgetFeatures : Qt_QDockWidget_DockWidgetFeature;
    static const DockWidgetVerticalTitleBar : Qt_QDockWidget_DockWidgetFeature;
    static const DockWidgetFeatureMask : Qt_QDockWidget_DockWidgetFeature;
    static const Reserved : Qt_QDockWidget_DockWidgetFeature;
    static function DockWidgetFeature(value : Qt_QDockWidget_DockWidgetFeature) : Qt_QDockWidget_DockWidgetFeature;
    static function DockWidgetFeatures(...value : Qt_QDockWidget_DockWidgetFeature) : Qt_QDockWidget_DockWidgetFeatures;

    // Methods
    function initStyleOption (option : QStyleOptionDockWidget) : void;
    function setTitleBarWidget (widget : QWidget) : void;
    function setWidget (widget : QWidget) : void;
    function titleBarWidget () : QWidget;
    function toggleViewAction () : QAction;
    function widget () : QWidget;

    // Signals
    var featuresChanged : QtJSXQt_QDockWidget_DockWidgetFeaturesSignal;

    // Instance Properties
    var features : Qt_QDockWidget_DockWidgetFeatures;
}
