/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomNode class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomattr.jsx";
import "qt/qdomcdatasection.jsx";
import "qt/qdomcharacterdata.jsx";
import "qt/qdomcomment.jsx";
import "qt/qdomdocument.jsx";
import "qt/qdomdocumentfragment.jsx";
import "qt/qdomdocumenttype.jsx";
import "qt/qdomelement.jsx";
import "qt/qdomentity.jsx";
import "qt/qdomentityreference.jsx";
import "qt/qdomnodelist.jsx";
import "qt/qdomnotation.jsx";
import "qt/qdomprocessinginstruction.jsx";
import "qt/qdomtext.jsx";

final native class Qt_QDomNode_NodeType {}

final native class Qt_QDomNode_EncodingPolicy {}

native class QDomNode
{
    function constructor ();
    function constructor (arg__1 : QDomNode);

    static const ElementNode : Qt_QDomNode_NodeType;
    static const AttributeNode : Qt_QDomNode_NodeType;
    static const TextNode : Qt_QDomNode_NodeType;
    static const CDATASectionNode : Qt_QDomNode_NodeType;
    static const EntityReferenceNode : Qt_QDomNode_NodeType;
    static const EntityNode : Qt_QDomNode_NodeType;
    static const ProcessingInstructionNode : Qt_QDomNode_NodeType;
    static const CommentNode : Qt_QDomNode_NodeType;
    static const DocumentNode : Qt_QDomNode_NodeType;
    static const DocumentTypeNode : Qt_QDomNode_NodeType;
    static const DocumentFragmentNode : Qt_QDomNode_NodeType;
    static const NotationNode : Qt_QDomNode_NodeType;
    static const BaseNode : Qt_QDomNode_NodeType;
    static const CharacterDataNode : Qt_QDomNode_NodeType;
    static function NodeType(value : Qt_QDomNode_NodeType) : Qt_QDomNode_NodeType;

    static const EncodingFromDocument : Qt_QDomNode_EncodingPolicy;
    static const EncodingFromTextStream : Qt_QDomNode_EncodingPolicy;
    static function EncodingPolicy(value : Qt_QDomNode_EncodingPolicy) : Qt_QDomNode_EncodingPolicy;

    // Methods
    function appendChild (newChild : QDomNode) : QDomNode;
    function childNodes () : QDomNodeList;
    function clear () : void;
    function firstChild () : QDomNode;
    function firstChildElement (tagName : string) : QDomElement;
    function insertAfter (newChild : QDomNode, refChild : QDomNode) : QDomNode;
    function insertBefore (newChild : QDomNode, refChild : QDomNode) : QDomNode;
    function lastChild () : QDomNode;
    function lastChildElement (tagName : string) : QDomElement;
    function localName () : string;
    function namedItem (name : string) : QDomNode;
    function namespaceURI () : string;
    function nextSibling () : QDomNode;
    function nextSiblingElement (taName : string) : QDomElement;
    function nodeName () : string;
    function nodeType () : Qt_QDomNode_NodeType;
    function nodeValue () : string;
    function normalize () : void;
    function ownerDocument () : QDomDocument;
    function parentNode () : QDomNode;
    function prefix () : string;
    function previousSibling () : QDomNode;
    function previousSiblingElement (tagName : string) : QDomElement;
    function removeChild (oldChild : QDomNode) : QDomNode;
    function replaceChild (newChild : QDomNode, oldChild : QDomNode) : QDomNode;
    function setNodeValue (arg__1 : string) : void;
    function setPrefix (pre : string) : void;
    function toAttr () : QDomAttr;
    function toCDATASection () : QDomCDATASection;
    function toCharacterData () : QDomCharacterData;
    function toComment () : QDomComment;
    function toDocument () : QDomDocument;
    function toDocumentFragment () : QDomDocumentFragment;
    function toDocumentType () : QDomDocumentType;
    function toElement () : QDomElement;
    function toEntity () : QDomEntity;
    function toEntityReference () : QDomEntityReference;
    function toNotation () : QDomNotation;
    function toProcessingInstruction () : QDomProcessingInstruction;
    function toText () : QDomText;
}
