/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomCharacterData class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnode.jsx";

native class QDomCharacterData extends QDomNode
{
    function constructor ();
    function constructor (x : QDomCharacterData);

    // Methods
    function appendData (arg : string) : void;
    function data () : string;
    function setData (arg__1 : string) : void;
}
