/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomDocument class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomattr.jsx";
import "qt/qdomcdatasection.jsx";
import "qt/qdomcomment.jsx";
import "qt/qdomdocumentfragment.jsx";
import "qt/qdomdocumenttype.jsx";
import "qt/qdomelement.jsx";
import "qt/qdomentityreference.jsx";
import "qt/qdomimplementation.jsx";
import "qt/qdomnode.jsx";
import "qt/qdomnodelist.jsx";
import "qt/qdomprocessinginstruction.jsx";
import "qt/qdomtext.jsx";

native class QDomDocument extends QDomNode
{
    function constructor ();
    function constructor (x : QDomDocument);
    function constructor (doctype : QDomDocumentType);
    function constructor (name : string);

    // Methods
    function createAttribute (name : string) : QDomAttr;
    function createAttributeNS (nsURI : string, qName : string) : QDomAttr;
    function createCDATASection (data : string) : QDomCDATASection;
    function createComment (data : string) : QDomComment;
    function createDocumentFragment () : QDomDocumentFragment;
    function createElement (tagName : string) : QDomElement;
    function createElementNS (nsURI : string, qName : string) : QDomElement;
    function createEntityReference (name : string) : QDomEntityReference;
    function createProcessingInstruction (target : string, data : string) : QDomProcessingInstruction;
    function createTextNode (data : string) : QDomText;
    function doctype () : QDomDocumentType;
    function documentElement () : QDomElement;
    function elementById (elementId : string) : QDomElement;
    function elementsByTagName (tagname : string) : QDomNodeList;
    function elementsByTagNameNS (nsURI : string, localName : string) : QDomNodeList;
    function implementation () : QDomImplementation;
}
