/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomNodeList class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QDomNodeList
{
    function constructor ();
    function constructor (arg__1 : QDomNodeList);
}
