/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDomNamedNodeMap class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdomnode.jsx";

native class QDomNamedNodeMap
{
    function constructor ();
    function constructor (arg__1 : QDomNamedNodeMap);

    // Methods
    function namedItem (name : string) : QDomNode;
    function namedItemNS (nsURI : string, localName : string) : QDomNode;
    function removeNamedItem (name : string) : QDomNode;
    function removeNamedItemNS (nsURI : string, localName : string) : QDomNode;
    function setNamedItem (newNode : QDomNode) : QDomNode;
    function setNamedItemNS (newNode : QDomNode) : QDomNode;
}
