/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDoubleValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qvalidator.jsx";
import "qt/_signals.jsx";

final native class Qt_QDoubleValidator_Notation {}

native class QDoubleValidator extends QValidator
{
    function constructor ();

    static const StandardNotation : Qt_QDoubleValidator_Notation;
    static const ScientificNotation : Qt_QDoubleValidator_Notation;
    static function Notation(value : Qt_QDoubleValidator_Notation) : Qt_QDoubleValidator_Notation;

    // Signals
    var notationChanged : QtJSXQt_QDoubleValidator_NotationSignal;

    // Instance Properties
    var notation : Qt_QDoubleValidator_Notation;
}
