/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDragEnterEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdragmoveevent.jsx";

native class QDragEnterEvent extends QDragMoveEvent
{
}
