/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDrag class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpixmap.jsx";

native class QDrag
{
    function constructor ();

    // Static Members
    static function cancel () : void;

    // Methods
    function pixmap () : QPixmap;
    function setPixmap (arg__1 : QPixmap) : void;
}
