/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QDropEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QDropEvent
{

    // Methods
    function acceptProposedAction () : void;
}
