/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFileOpenEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QFileOpenEvent
{
    function constructor (file : string);

    // Methods
    function file () : string;
}
