/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFileDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qdialog.jsx";
import "qt/qfileiconprovider.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QFileDialog_ViewMode {}

final native class Qt_QFileDialog_Option {}

final native class Qt_QFileDialog_Options {}

native class QFileDialog extends QDialog
{
    function constructor (parent : QWidget, caption : string, directory : string, filter : string);

    // Static Members
    static function getExistingDirectory (parent : QWidget, caption : string, dir : string, options : Qt_QFileDialog_Options) : string;
    static function getOpenFileName (parent : QWidget, caption : string, dir : string, filter : string, selectedFilter : string, options : Qt_QFileDialog_Options) : string;
    static function getOpenFileNames (parent : QWidget, caption : string, dir : string, filter : string, selectedFilter : string, options : Qt_QFileDialog_Options) : string[];
    static function getSaveFileName (parent : QWidget, caption : string, dir : string, filter : string, selectedFilter : string, options : Qt_QFileDialog_Options) : string;

    static const Detail : Qt_QFileDialog_ViewMode;
    static const List : Qt_QFileDialog_ViewMode;
    static function ViewMode(value : Qt_QFileDialog_ViewMode) : Qt_QFileDialog_ViewMode;

    static const ShowDirsOnly : Qt_QFileDialog_Option;
    static const DontResolveSymlinks : Qt_QFileDialog_Option;
    static const DontConfirmOverwrite : Qt_QFileDialog_Option;
    static const DontUseSheet : Qt_QFileDialog_Option;
    static const DontUseNativeDialog : Qt_QFileDialog_Option;
    static const ReadOnly : Qt_QFileDialog_Option;
    static const HideNameFilterDetails : Qt_QFileDialog_Option;
    static const DontUseCustomDirectoryIcons : Qt_QFileDialog_Option;
    static function Option(value : Qt_QFileDialog_Option) : Qt_QFileDialog_Option;
    static function Options(...value : Qt_QFileDialog_Option) : Qt_QFileDialog_Options;

    // Methods
    function history () : string[];
    function iconProvider () : QFileIconProvider;
    function itemDelegate () : QAbstractItemDelegate;
    function labelText (label : Qt_QFileDialog_DialogLabel) : string;
    function mimeTypeFilters () : string[];
    function nameFilters () : string[];
    function selectFile (filename : string) : void;
    function selectMimeTypeFilter (filter : string) : void;
    function selectNameFilter (filter : string) : void;
    function selectedFiles () : string[];
    function selectedMimeTypeFilter () : string;
    function selectedNameFilter () : string;
    function setDirectory (directory : string) : void;
    function setHistory (paths : string[]) : void;
    function setIconProvider (provider : QFileIconProvider) : void;
    function setItemDelegate (delegate : QAbstractItemDelegate) : void;
    function setLabelText (label : Qt_QFileDialog_DialogLabel, text : string) : void;
    function setMimeTypeFilters (filters : string[]) : void;
    function setNameFilter (filter : string) : void;
    function setNameFilters (filters : string[]) : void;

    // Signals
    var currentChanged : QtJSXQStringSignal;
    var directoryEntered : QtJSXQStringSignal;
    var fileSelected : QtJSXQStringSignal;
    var filesSelected : QtJSXQStringListSignal;
    var filterSelected : QtJSXQStringSignal;

    // Instance Properties
    var viewMode : Qt_QFileDialog_ViewMode;
    var fileMode : Qt_QFileDialog_FileMode;
    var acceptMode : Qt_QFileDialog_AcceptMode;
    var defaultSuffix : string;
    var options : Qt_QFileDialog_Options;
    var supportedSchemes : string[];
}
