/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFileIconProvider class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QFileIconProvider_IconType {}

native class QFileIconProvider
{
    function constructor ();

    static const Computer : Qt_QFileIconProvider_IconType;
    static const Desktop : Qt_QFileIconProvider_IconType;
    static const Trashcan : Qt_QFileIconProvider_IconType;
    static const Network : Qt_QFileIconProvider_IconType;
    static const Drive : Qt_QFileIconProvider_IconType;
    static const Folder : Qt_QFileIconProvider_IconType;
    static const File : Qt_QFileIconProvider_IconType;
    static function IconType(value : Qt_QFileIconProvider_IconType) : Qt_QFileIconProvider_IconType;
}
