/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFocusFrame class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qobject.jsx";
import "qt/qstyleoption.jsx";
import "qt/qwidget.jsx";

native class QFocusFrame extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function eventFilter (arg__1 : QObject, arg__2 : QEvent) : boolean;
    function initStyleOption (option : QStyleOption) : void;
    function setWidget (widget : QWidget) : void;
    function widget () : QWidget;
}
