/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFontDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdialog.jsx";
import "qt/qwidget.jsx";

final native class Qt_QFontDialog_FontDialogOption {}

final native class Qt_QFontDialog_FontDialogOptions {}

native class QFontDialog extends QDialog
{
    function constructor (parent : QWidget);

    static const NoButtons : Qt_QFontDialog_FontDialogOption;
    static const DontUseNativeDialog : Qt_QFontDialog_FontDialogOption;
    static const ScalableFonts : Qt_QFontDialog_FontDialogOption;
    static const NonScalableFonts : Qt_QFontDialog_FontDialogOption;
    static const MonospacedFonts : Qt_QFontDialog_FontDialogOption;
    static const ProportionalFonts : Qt_QFontDialog_FontDialogOption;
    static function FontDialogOption(value : Qt_QFontDialog_FontDialogOption) : Qt_QFontDialog_FontDialogOption;
    static function FontDialogOptions(...value : Qt_QFontDialog_FontDialogOption) : Qt_QFontDialog_FontDialogOptions;

    // Instance Properties
    var options : Qt_QFontDialog_FontDialogOptions;
}
