/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFontMetricsF class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfont.jsx";
import "qt/qrectf.jsx";
import "qt/qsizef.jsx";
import "qt/qt.jsx";

native class QFontMetricsF
{
    function constructor (font : QFont);

    // Methods
    function ascent () : number;
    function averageCharWidth () : number;
    function boundingRect (r : QRectF, flags : int, string : string, tabstops : int, tabarray : int) : QRectF;
    function boundingRect (string : string) : QRectF;
    function capHeight () : number;
    function descent () : number;
    function elidedText (text : string, mode : Qt_TextElideMode, width : number, flags : int) : string;
    function fontDpi () : number;
    function height () : number;
    function horizontalAdvance (arg__1 : string) : number;
    function horizontalAdvance (string : string, length : int) : number;
    function inFont (arg__1 : string) : boolean;
    function inFontUcs4 (ucs4 : int) : boolean;
    function leading () : number;
    function leftBearing (arg__1 : string) : number;
    function lineSpacing () : number;
    function lineWidth () : number;
    function maxWidth () : number;
    function minLeftBearing () : number;
    function minRightBearing () : number;
    function overlinePos () : number;
    function rightBearing (arg__1 : string) : number;
    function size (flags : int, str : string, tabstops : int, tabarray : int) : QSizeF;
    function strikeOutPos () : number;
    function swap (other : QFontMetricsF) : void;
    function tightBoundingRect (text : string) : QRectF;
    function underlinePos () : number;
    function width (string : string) : number;
    function xHeight () : number;
}
