/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFontInfo class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfont.jsx";

native class QFontInfo
{
    function constructor (arg__1 : QFont);
    function constructor (arg__1 : QFontInfo);

    // Methods
    function family () : string;
    function style () : Qt_QFont_Style;
    function styleHint () : Qt_QFont_StyleHint;
    function styleName () : string;
    function swap (other : QFontInfo) : void;
}
