/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFormLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";

final native class Qt_QFormLayout_FieldGrowthPolicy {}

native class QFormLayout extends QLayout
{
    function constructor ();

    static const FieldsStayAtSizeHint : Qt_QFormLayout_FieldGrowthPolicy;
    static const ExpandingFieldsGrow : Qt_QFormLayout_FieldGrowthPolicy;
    static const AllNonFixedFieldsGrow : Qt_QFormLayout_FieldGrowthPolicy;
    static function FieldGrowthPolicy(value : Qt_QFormLayout_FieldGrowthPolicy) : Qt_QFormLayout_FieldGrowthPolicy;

    // Instance Properties
    var fieldGrowthPolicy : Qt_QFormLayout_FieldGrowthPolicy;
    var rowWrapPolicy : Qt_QFormLayout_RowWrapPolicy;
}
