/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QFrame class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptionframe.jsx";
import "qt/qwidget.jsx";

final native class Qt_QFrame_Shape {}

native class QFrame extends QWidget
{
    function constructor ();

    static const NoFrame : Qt_QFrame_Shape;
    static const Box : Qt_QFrame_Shape;
    static const Panel : Qt_QFrame_Shape;
    static const WinPanel : Qt_QFrame_Shape;
    static const HLine : Qt_QFrame_Shape;
    static const VLine : Qt_QFrame_Shape;
    static const StyledPanel : Qt_QFrame_Shape;
    static function Shape(value : Qt_QFrame_Shape) : Qt_QFrame_Shape;

    // Methods
    function initStyleOption (option : QStyleOptionFrame) : void;

    // Instance Properties
    var frameShape : Qt_QFrame_Shape;
    var frameShadow : Qt_QFrame_Shadow;
}
