/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGesture class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QGesture_GestureCancelPolicy {}

native class QGesture
{

    static const CancelNone : Qt_QGesture_GestureCancelPolicy;
    static const CancelAllInContext : Qt_QGesture_GestureCancelPolicy;
    static function GestureCancelPolicy(value : Qt_QGesture_GestureCancelPolicy) : Qt_QGesture_GestureCancelPolicy;

    // Methods
    function unsetHotSpot () : void;

    // Instance Properties
    var gestureCancelPolicy : Qt_QGesture_GestureCancelPolicy;
}
