/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLColormap class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QGLColormap
{
    function constructor ();
    function constructor (arg__1 : QGLColormap);

    // Methods
    function detach () : void;
}
