/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLContext class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QGLContext_BindOption {}

final native class Qt_QGLContext_BindOptions {}

native class QGLContext
{

    // Static Members
    static function currentContext () : QGLContext;

    static const NoBindOption : Qt_QGLContext_BindOption;
    static const InvertedYBindOption : Qt_QGLContext_BindOption;
    static const MipmapBindOption : Qt_QGLContext_BindOption;
    static const PremultipliedAlphaBindOption : Qt_QGLContext_BindOption;
    static const LinearFilteringBindOption : Qt_QGLContext_BindOption;
    static const DefaultBindOption : Qt_QGLContext_BindOption;
    static const MemoryManagedBindOption : Qt_QGLContext_BindOption;
    static const InternalBindOption : Qt_QGLContext_BindOption;
    static const CanFlipNativePixmapBindOption : Qt_QGLContext_BindOption;
    static const TemporarilyCachedBindOption : Qt_QGLContext_BindOption;
    static function BindOption(value : Qt_QGLContext_BindOption) : Qt_QGLContext_BindOption;
    static function BindOptions(...value : Qt_QGLContext_BindOption) : Qt_QGLContext_BindOptions;

    // Methods
    function doneCurrent () : void;
    function makeCurrent () : void;
    function reset () : void;
    function swapBuffers () : void;
}
