/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLFramebufferObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglframebufferobjectformat.jsx";
import "qt/qimage.jsx";
import "qt/qpaintdevice.jsx";
import "qt/qpointf.jsx";
import "qt/qrect.jsx";
import "qt/qrectf.jsx";
import "qt/qsize.jsx";

final native class Qt_QGLFramebufferObject_Attachment {}

native class QGLFramebufferObject extends QPaintDevice
{
    function constructor (size : QSize, attachment : Qt_QGLFramebufferObject_Attachment, target : int, internal_format : int);
    function constructor (size : QSize, format : QGLFramebufferObjectFormat);
    function constructor (size : QSize, target : int);
    function constructor (width : int, height : int, attachment : Qt_QGLFramebufferObject_Attachment, target : int, internal_format : int);
    function constructor (width : int, height : int, format : QGLFramebufferObjectFormat);
    function constructor (width : int, height : int, target : int);

    // Static Members
    static function bindDefault () : boolean;
    static function blitFramebuffer (target : QGLFramebufferObject, targetRect : QRect, source : QGLFramebufferObject, sourceRect : QRect, buffers : int, filter : int) : void;
    static function hasOpenGLFramebufferBlit () : boolean;
    static function hasOpenGLFramebufferObjects () : boolean;

    static const NoAttachment : Qt_QGLFramebufferObject_Attachment;
    static const CombinedDepthStencil : Qt_QGLFramebufferObject_Attachment;
    static const Depth : Qt_QGLFramebufferObject_Attachment;
    static function Attachment(value : Qt_QGLFramebufferObject_Attachment) : Qt_QGLFramebufferObject_Attachment;

    // Methods
    function attachment () : Qt_QGLFramebufferObject_Attachment;
    function bind () : boolean;
    function drawTexture (point : QPointF, textureId : int, textureTarget : int) : void;
    function drawTexture (target : QRectF, textureId : int, textureTarget : int) : void;
    function format () : QGLFramebufferObjectFormat;
    function handle () : int;
    function isBound () : boolean;
    function isValid () : boolean;
    function release () : boolean;
    function size () : QSize;
    function texture () : int;
    function toImage () : QImage;
}
