/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLFramebufferObjectFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglframebufferobject.jsx";

native class QGLFramebufferObjectFormat
{
    function constructor ();
    function constructor (other : QGLFramebufferObjectFormat);

    // Methods
    function attachment () : Qt_QGLFramebufferObject_Attachment;
    function internalTextureFormat () : int;
    function mipmap () : boolean;
    function operator_assign (other : QGLFramebufferObjectFormat) : QGLFramebufferObjectFormat;
    function operator_equal (other : QGLFramebufferObjectFormat) : boolean;
    function samples () : int;
    function setAttachment (attachment : Qt_QGLFramebufferObject_Attachment) : void;
    function setInternalTextureFormat (internalTextureFormat : int) : void;
    function setMipmap (enabled : boolean) : void;
    function setSamples (samples : int) : void;
    function setTextureTarget (target : int) : void;
    function textureTarget () : int;
}
