/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLFramebufferObjectFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglframebufferobject.jsx";

native class QGLFramebufferObjectFormat
{
    function constructor ();
    function constructor (other : QGLFramebufferObjectFormat);

    // Methods
    function attachment () : Qt_QGLFramebufferObject_Attachment;
    function operator_assign (other : QGLFramebufferObjectFormat) : QGLFramebufferObjectFormat;
    function setAttachment (attachment : Qt_QGLFramebufferObject_Attachment) : void;
}
