/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLPixelBuffer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglcontext.jsx";
import "qt/qimage.jsx";
import "qt/qpaintdevice.jsx";
import "qt/qpaintengine.jsx";
import "qt/qpixmap.jsx";
import "qt/qpointf.jsx";
import "qt/qrectf.jsx";
import "qt/qsize.jsx";

native class QGLPixelBuffer
{

    // Static Members
    static function hasOpenGLPbuffers () : boolean;

    // Methods
    function bindTexture (image : QImage, target : int) : int;
    function bindTexture (pixmap : QPixmap, target : int) : int;
    function bindTexture (fileName : string) : int;
    function bindToDynamicTexture (texture : int) : boolean;
    function context () : QGLContext;
    function deleteTexture (texture_id : int) : void;
    function devType () : int;
    function doneCurrent () : boolean;
    function drawTexture (point : QPointF, textureId : int, textureTarget : int) : void;
    function drawTexture (target : QRectF, textureId : int, textureTarget : int) : void;
    function generateDynamicTexture () : int;
    function isValid () : boolean;
    function makeCurrent () : boolean;
    function metric (metric : Qt_QPaintDevice_PaintDeviceMetric) : int;
    function paintEngine () : QPaintEngine;
    function releaseFromDynamicTexture () : void;
    function size () : QSize;
    function toImage () : QImage;
    function updateDynamicTexture (texture_id : int) : void;
}
