/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLShaderProgram class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglshader.jsx";

native class QGLShaderProgram
{
    function constructor ();

    // Methods
    function log () : string;
    function release () : void;
    function removeAllShaders () : void;
    function removeShader (shader : QGLShader) : void;
    function shaders () : QGLShader[];
}
