/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLShader class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QGLShader_ShaderTypeBit {}

final native class Qt_QGLShader_ShaderType {}

native class QGLShader
{
    function constructor ();

    static const Vertex : Qt_QGLShader_ShaderTypeBit;
    static const Fragment : Qt_QGLShader_ShaderTypeBit;
    static const Geometry : Qt_QGLShader_ShaderTypeBit;
    static function ShaderTypeBit(value : Qt_QGLShader_ShaderTypeBit) : Qt_QGLShader_ShaderTypeBit;
    static function ShaderType(...value : Qt_QGLShader_ShaderTypeBit) : Qt_QGLShader_ShaderType;

    // Methods
    function log () : string;
    function shaderType () : Qt_QGLShader_ShaderType;
}
