/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGLWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qevent.jsx";
import "qt/qfont.jsx";
import "qt/qglcolormap.jsx";
import "qt/qglcontext.jsx";
import "qt/qimage.jsx";
import "qt/qpaintengine.jsx";
import "qt/qpaintevent.jsx";
import "qt/qpixmap.jsx";
import "qt/qpointf.jsx";
import "qt/qrectf.jsx";
import "qt/qresizeevent.jsx";

native class QGLWidget
{
    function constructor ();

    // Static Members
    static function convertToGLFormat (img : QImage) : QImage;

    // Methods
    function autoBufferSwap () : boolean;
    function bindTexture (image : QImage, target : int, format : int) : int;
    function bindTexture (image : QImage, target : int, format : int, options : Qt_QGLContext_BindOptions) : int;
    function bindTexture (pixmap : QPixmap, target : int, format : int) : int;
    function bindTexture (pixmap : QPixmap, target : int, format : int, options : Qt_QGLContext_BindOptions) : int;
    function bindTexture (fileName : string) : int;
    function colormap () : QGLColormap;
    function context () : QGLContext;
    function deleteTexture (tx_id : int) : void;
    function doneCurrent () : void;
    function doubleBuffer () : boolean;
    function drawTexture (point : QPointF, textureId : int, textureTarget : int) : void;
    function drawTexture (target : QRectF, textureId : int, textureTarget : int) : void;
    function event (arg__1 : QEvent) : boolean;
    function glDraw () : void;
    function glInit () : void;
    function grabFrameBuffer (withAlpha : boolean) : QImage;
    function initializeGL () : void;
    function initializeOverlayGL () : void;
    function isSharing () : boolean;
    function isValid () : boolean;
    function makeCurrent () : void;
    function makeOverlayCurrent () : void;
    function overlayContext () : QGLContext;
    function paintEngine () : QPaintEngine;
    function paintEvent (arg__1 : QPaintEvent) : void;
    function paintGL () : void;
    function paintOverlayGL () : void;
    function qglClearColor (c : QColor) : void;
    function qglColor (c : QColor) : void;
    function renderPixmap (w : int, h : int, useContext : boolean) : QPixmap;
    function renderText (x : number, y : number, z : number, str : string, fnt : QFont) : void;
    function renderText (x : int, y : int, str : string, fnt : QFont) : void;
    function resizeEvent (arg__1 : QResizeEvent) : void;
    function resizeGL (w : int, h : int) : void;
    function resizeOverlayGL (w : int, h : int) : void;
    function setAutoBufferSwap (on : boolean) : void;
    function setColormap (map : QGLColormap) : void;
    function swapBuffers () : void;

    // Slots
    function updateGL () : void;
    function updateOverlayGL () : void;
}
