/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsScene class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsitemgroup.jsx";
import "qt/qgraphicsscenecontextmenuevent.jsx";
import "qt/qgraphicsscenedragdropevent.jsx";
import "qt/qgraphicsscenehelpevent.jsx";
import "qt/qgraphicsscenemouseevent.jsx";
import "qt/qgraphicsscenewheelevent.jsx";
import "qt/qgraphicsview.jsx";
import "qt/qgraphicswidget.jsx";
import "qt/qstyle.jsx";
import "qt/_signals.jsx";

final native class Qt_QGraphicsScene_ItemIndexMethod {}

native class QGraphicsScene
{
    function constructor ();

    static const NoIndex : Qt_QGraphicsScene_ItemIndexMethod;
    static const BspTreeIndex : Qt_QGraphicsScene_ItemIndexMethod;
    static function ItemIndexMethod(value : Qt_QGraphicsScene_ItemIndexMethod) : Qt_QGraphicsScene_ItemIndexMethod;

    // Methods
    function activePanel () : QGraphicsItem;
    function activeWindow () : QGraphicsWidget;
    function addItem (item : QGraphicsItem) : void;
    function clearFocus () : void;
    function contextMenuEvent (event : QGraphicsSceneContextMenuEvent) : void;
    function createItemGroup (items : QGraphicsItem[]) : QGraphicsItemGroup;
    function destroyItemGroup (group : QGraphicsItemGroup) : void;
    function dragEnterEvent (event : QGraphicsSceneDragDropEvent) : void;
    function dragLeaveEvent (event : QGraphicsSceneDragDropEvent) : void;
    function dragMoveEvent (event : QGraphicsSceneDragDropEvent) : void;
    function dropEvent (event : QGraphicsSceneDragDropEvent) : void;
    function focusItem () : QGraphicsItem;
    function helpEvent (event : QGraphicsSceneHelpEvent) : void;
    function mouseDoubleClickEvent (event : QGraphicsSceneMouseEvent) : void;
    function mouseGrabberItem () : QGraphicsItem;
    function mouseMoveEvent (event : QGraphicsSceneMouseEvent) : void;
    function mousePressEvent (event : QGraphicsSceneMouseEvent) : void;
    function mouseReleaseEvent (event : QGraphicsSceneMouseEvent) : void;
    function removeItem (item : QGraphicsItem) : void;
    function selectedItems () : QGraphicsItem[];
    function setActivePanel (item : QGraphicsItem) : void;
    function setActiveWindow (widget : QGraphicsWidget) : void;
    function setStyle (style : QStyle) : void;
    function style () : QStyle;
    function views () : QGraphicsView[];
    function wheelEvent (event : QGraphicsSceneWheelEvent) : void;

    // Slots
    function advance () : void;
    function clear () : void;
    function clearSelection () : void;

    // Signals
    var selectionChanged : QtJSXSignal;

    // Instance Properties
    var itemIndexMethod : Qt_QGraphicsScene_ItemIndexMethod;
}
