/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneContextMenuEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

final native class Qt_QGraphicsSceneContextMenuEvent_Reason {}

native class QGraphicsSceneContextMenuEvent extends QGraphicsSceneEvent
{
    function constructor ();

    static const Mouse : Qt_QGraphicsSceneContextMenuEvent_Reason;
    static const Keyboard : Qt_QGraphicsSceneContextMenuEvent_Reason;
    static const Other : Qt_QGraphicsSceneContextMenuEvent_Reason;
    static function Reason(value : Qt_QGraphicsSceneContextMenuEvent_Reason) : Qt_QGraphicsSceneContextMenuEvent_Reason;

    // Methods
    function reason () : Qt_QGraphicsSceneContextMenuEvent_Reason;
    function setReason (reason : Qt_QGraphicsSceneContextMenuEvent_Reason) : void;
}
