/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";
import "qt/qobject.jsx";
import "qt/qpointf.jsx";
import "qt/_signals.jsx";

native class QGraphicsObject extends QObject
{
    function constructor ();

    // Signals
    var childrenChanged : QtJSXSignal;
    var enabledChanged : QtJSXSignal;
    var heightChanged : QtJSXSignal;
    var opacityChanged : QtJSXSignal;
    var parentChanged : QtJSXSignal;
    var rotationChanged : QtJSXSignal;
    var scaleChanged : QtJSXSignal;
    var visibleChanged : QtJSXSignal;
    var widthChanged : QtJSXSignal;
    var xChanged : QtJSXSignal;
    var yChanged : QtJSXSignal;
    var zChanged : QtJSXSignal;

    // Instance Properties
    var parent : QGraphicsObject;
    var opacity : number;
    var enabled : boolean;
    var visible : boolean;
    var pos : QPointF;
    var x : number;
    var y : number;
    var z : number;
    var rotation : number;
    var scale : number;
    var transformOriginPoint : QPointF;
    var effect : QGraphicsEffect;
}
