/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsRectItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractgraphicsshapeitem.jsx";
import "qt/qgraphicsitem.jsx";

native class QGraphicsRectItem extends QAbstractGraphicsShapeItem
{
    function constructor (parent : QGraphicsItem);
}
