/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicslayoutitem.jsx";

native class QGraphicsLayout extends QGraphicsLayoutItem
{
    function constructor (parent : QGraphicsLayoutItem);

    // Methods
    function activate () : void;
    function addChildLayoutItem (layoutItem : QGraphicsLayoutItem) : void;
    function invalidate () : void;
}
