/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";
import "qt/qgraphicsitemgroup.jsx";
import "qt/qgraphicsobject.jsx";
import "qt/qgraphicsscene.jsx";
import "qt/qgraphicsscenecontextmenuevent.jsx";
import "qt/qgraphicsscenedragdropevent.jsx";
import "qt/qgraphicsscenehoverevent.jsx";
import "qt/qgraphicsscenemouseevent.jsx";
import "qt/qgraphicsscenewheelevent.jsx";
import "qt/qgraphicstransform.jsx";
import "qt/qgraphicswidget.jsx";

final native class Qt_QGraphicsItem_PanelModality {}

final native class Qt_QGraphicsItem_GraphicsItemFlag {}

final native class Qt_QGraphicsItem_GraphicsItemFlags {}

final native class Qt_QGraphicsItem_GraphicsItemChange {}

native class QGraphicsItem
{
    function constructor (parent : QGraphicsItem);

    static const NonModal : Qt_QGraphicsItem_PanelModality;
    static const PanelModal : Qt_QGraphicsItem_PanelModality;
    static const SceneModal : Qt_QGraphicsItem_PanelModality;
    static function PanelModality(value : Qt_QGraphicsItem_PanelModality) : Qt_QGraphicsItem_PanelModality;

    static const ItemIsMovable : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemIsSelectable : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemIsFocusable : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemClipsToShape : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemClipsChildrenToShape : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemIgnoresTransformations : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemIgnoresParentOpacity : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemDoesntPropagateOpacityToChildren : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemStacksBehindParent : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemUsesExtendedStyleOption : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemHasNoContents : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemSendsGeometryChanges : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemAcceptsInputMethod : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemNegativeZStacksBehindParent : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemIsPanel : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemIsFocusScope : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemSendsScenePositionChanges : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemStopsClickFocusPropagation : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemStopsFocusHandling : Qt_QGraphicsItem_GraphicsItemFlag;
    static const ItemContainsChildrenInShape : Qt_QGraphicsItem_GraphicsItemFlag;
    static function GraphicsItemFlag(value : Qt_QGraphicsItem_GraphicsItemFlag) : Qt_QGraphicsItem_GraphicsItemFlag;
    static function GraphicsItemFlags(...value : Qt_QGraphicsItem_GraphicsItemFlag) : Qt_QGraphicsItem_GraphicsItemFlags;

    static const ItemPositionChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemMatrixChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemVisibleChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemEnabledChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemSelectedChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemParentChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemChildAddedChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemChildRemovedChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemTransformChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemPositionHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemTransformHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemSceneChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemVisibleHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemEnabledHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemSelectedHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemParentHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemSceneHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemCursorChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemCursorHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemToolTipChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemToolTipHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemFlagsChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemFlagsHaveChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemZValueChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemZValueHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemOpacityChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemOpacityHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemScenePositionHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemRotationChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemRotationHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemScaleChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemScaleHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemTransformOriginPointChange : Qt_QGraphicsItem_GraphicsItemChange;
    static const ItemTransformOriginPointHasChanged : Qt_QGraphicsItem_GraphicsItemChange;
    static function GraphicsItemChange(value : Qt_QGraphicsItem_GraphicsItemChange) : Qt_QGraphicsItem_GraphicsItemChange;

    // Methods
    function addToIndex () : void;
    function childItems () : QGraphicsItem[];
    function clearFocus () : void;
    function commonAncestorItem (other : QGraphicsItem) : QGraphicsItem;
    function contextMenuEvent (event : QGraphicsSceneContextMenuEvent) : void;
    function dragEnterEvent (event : QGraphicsSceneDragDropEvent) : void;
    function dragLeaveEvent (event : QGraphicsSceneDragDropEvent) : void;
    function dragMoveEvent (event : QGraphicsSceneDragDropEvent) : void;
    function dropEvent (event : QGraphicsSceneDragDropEvent) : void;
    function extension (variant : variant) : variant;
    function flags () : Qt_QGraphicsItem_GraphicsItemFlags;
    function focusItem () : QGraphicsItem;
    function focusProxy () : QGraphicsItem;
    function focusScopeItem () : QGraphicsItem;
    function grabKeyboard () : void;
    function grabMouse () : void;
    function graphicsEffect () : QGraphicsEffect;
    function group () : QGraphicsItemGroup;
    function hide () : void;
    function hoverEnterEvent (event : QGraphicsSceneHoverEvent) : void;
    function hoverLeaveEvent (event : QGraphicsSceneHoverEvent) : void;
    function hoverMoveEvent (event : QGraphicsSceneHoverEvent) : void;
    function installSceneEventFilter (filterItem : QGraphicsItem) : void;
    function itemChange (change : Qt_QGraphicsItem_GraphicsItemChange, value : variant) : variant;
    function mouseDoubleClickEvent (event : QGraphicsSceneMouseEvent) : void;
    function mouseMoveEvent (event : QGraphicsSceneMouseEvent) : void;
    function mousePressEvent (event : QGraphicsSceneMouseEvent) : void;
    function mouseReleaseEvent (event : QGraphicsSceneMouseEvent) : void;
    function panel () : QGraphicsItem;
    function panelModality () : Qt_QGraphicsItem_PanelModality;
    function parentItem () : QGraphicsItem;
    function parentObject () : QGraphicsObject;
    function parentWidget () : QGraphicsWidget;
    function prepareGeometryChange () : void;
    function removeFromIndex () : void;
    function removeSceneEventFilter (filterItem : QGraphicsItem) : void;
    function resetTransform () : void;
    function scene () : QGraphicsScene;
    function setFlags (flags : Qt_QGraphicsItem_GraphicsItemFlags) : void;
    function setFocusProxy (item : QGraphicsItem) : void;
    function setGraphicsEffect (effect : QGraphicsEffect) : void;
    function setGroup (group : QGraphicsItemGroup) : void;
    function setPanelModality (panelModality : Qt_QGraphicsItem_PanelModality) : void;
    function setParentItem (parent : QGraphicsItem) : void;
    function setToolTip (toolTip : string) : void;
    function setTransformations (transformations : QGraphicsTransform[]) : void;
    function show () : void;
    function stackBefore (sibling : QGraphicsItem) : void;
    function toGraphicsObject () : QGraphicsObject;
    function toolTip () : string;
    function topLevelItem () : QGraphicsItem;
    function topLevelWidget () : QGraphicsWidget;
    function transformations () : QGraphicsTransform[];
    function ungrabKeyboard () : void;
    function ungrabMouse () : void;
    function unsetCursor () : void;
    function updateMicroFocus () : void;
    function wheelEvent (event : QGraphicsSceneWheelEvent) : void;
    function window () : QGraphicsWidget;
}
