/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsDropShadowEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";

native class QGraphicsDropShadowEffect extends QGraphicsEffect
{
    function constructor ();
}
