/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";
import "qt/qgraphicsitem.jsx";
import "qt/_signals.jsx";

native class QGraphicsObject
{
    function constructor (parent : QGraphicsItem);

    // Slots
    function updateMicroFocus () : void;

    // Signals
    var childrenChanged : QtJSXSignal;
    var enabledChanged : QtJSXSignal;
    var heightChanged : QtJSXSignal;
    var opacityChanged : QtJSXSignal;
    var parentChanged : QtJSXSignal;
    var rotationChanged : QtJSXSignal;
    var scaleChanged : QtJSXSignal;
    var visibleChanged : QtJSXSignal;
    var widthChanged : QtJSXSignal;
    var xChanged : QtJSXSignal;
    var yChanged : QtJSXSignal;
    var zChanged : QtJSXSignal;

    // Instance Properties
    var parent : QGraphicsObject;
    var effect : QGraphicsEffect;
}
