/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractscrollarea.jsx";
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsscene.jsx";
import "qt/qwidget.jsx";

final native class Qt_QGraphicsView_DragMode {}

final native class Qt_QGraphicsView_ViewportAnchor {}

native class QGraphicsView extends QAbstractScrollArea
{
    function constructor (scene : QGraphicsScene, parent : QWidget);
    function constructor (parent : QWidget);

    static const NoDrag : Qt_QGraphicsView_DragMode;
    static const ScrollHandDrag : Qt_QGraphicsView_DragMode;
    static const RubberBandDrag : Qt_QGraphicsView_DragMode;
    static function DragMode(value : Qt_QGraphicsView_DragMode) : Qt_QGraphicsView_DragMode;

    static const NoAnchor : Qt_QGraphicsView_ViewportAnchor;
    static const AnchorViewCenter : Qt_QGraphicsView_ViewportAnchor;
    static const AnchorUnderMouse : Qt_QGraphicsView_ViewportAnchor;
    static function ViewportAnchor(value : Qt_QGraphicsView_ViewportAnchor) : Qt_QGraphicsView_ViewportAnchor;

    // Methods
    function centerOn (item : QGraphicsItem) : void;
    function items () : QGraphicsItem[];
    function resetCachedContent () : void;
    function resetMatrix () : void;
    function resetTransform () : void;
    function scene () : QGraphicsScene;
    function setScene (scene : QGraphicsScene) : void;

    // Instance Properties
    var dragMode : Qt_QGraphicsView_DragMode;
    var cacheMode : Qt_QGraphicsView_CacheMode;
    var transformationAnchor : Qt_QGraphicsView_ViewportAnchor;
    var resizeAnchor : Qt_QGraphicsView_ViewportAnchor;
    var viewportUpdateMode : Qt_QGraphicsView_ViewportUpdateMode;
    var optimizationFlags : Qt_QGraphicsView_OptimizationFlags;
}
