/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsPixmapItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";

final native class Qt_QGraphicsPixmapItem_ShapeMode {}

native class QGraphicsPixmapItem extends QGraphicsItem
{
    function constructor (parent : QGraphicsItem);

    static const MaskShape : Qt_QGraphicsPixmapItem_ShapeMode;
    static const BoundingRectShape : Qt_QGraphicsPixmapItem_ShapeMode;
    static const HeuristicMaskShape : Qt_QGraphicsPixmapItem_ShapeMode;
    static function ShapeMode(value : Qt_QGraphicsPixmapItem_ShapeMode) : Qt_QGraphicsPixmapItem_ShapeMode;

    // Methods
    function setShapeMode (mode : Qt_QGraphicsPixmapItem_ShapeMode) : void;
    function shapeMode () : Qt_QGraphicsPixmapItem_ShapeMode;
}
