/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneMouseEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

native class QGraphicsSceneMouseEvent extends QGraphicsSceneEvent
{
    function constructor ();
}
