/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsTransform class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QGraphicsTransform
{

    // Slots
    function update () : void;
}
