/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsLineItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";

native class QGraphicsLineItem extends QGraphicsItem
{
    function constructor (parent : QGraphicsItem);
}
