/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsScale class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicstransform.jsx";
import "qt/_signals.jsx";

native class QGraphicsScale extends QGraphicsTransform
{

    // Signals
    var originChanged : QtJSXSignal;
    var scaleChanged : QtJSXSignal;
    var xScaleChanged : QtJSXSignal;
    var yScaleChanged : QtJSXSignal;
    var zScaleChanged : QtJSXSignal;
}
