/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneHoverEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

native class QGraphicsSceneHoverEvent extends QGraphicsSceneEvent
{
    function constructor ();
}
