/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";

native class QGraphicsSceneEvent
{
    function constructor ();

    // Methods
    function widget () : QWidget;
}
