/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsItemAnimation class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";

native class QGraphicsItemAnimation
{
    function constructor ();

    // Methods
    function clear () : void;
    function item () : QGraphicsItem;
    function setItem (item : QGraphicsItem) : void;

    // Slots
    function reset () : void;
}
