/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGradient class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QGradient_Type {}

native class QGradient
{
    function constructor ();

    static const LinearGradient : Qt_QGradient_Type;
    static const RadialGradient : Qt_QGradient_Type;
    static const ConicalGradient : Qt_QGradient_Type;
    static const NoGradient : Qt_QGradient_Type;
    static function Type(value : Qt_QGradient_Type) : Qt_QGradient_Type;

    // Methods
    function coordinateMode () : Qt_QGradient_CoordinateMode;
    function setCoordinateMode (mode : Qt_QGradient_CoordinateMode) : void;
    function setSpread (spread : Qt_QGradient_Spread) : void;
    function spread () : Qt_QGradient_Spread;
    function type () : Qt_QGradient_Type;
}
