/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneResizeEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

native class QGraphicsSceneResizeEvent extends QGraphicsSceneEvent
{
    function constructor ();
}
