/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsAnchor class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsizepolicy.jsx";

native class QGraphicsAnchor
{

    // Methods
    function unsetSpacing () : void;

    // Instance Properties
    var sizePolicy : Qt_QSizePolicy_Policy;
}
