/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneHelpEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

native class QGraphicsSceneHelpEvent extends QGraphicsSceneEvent
{
    function constructor ();
}
