/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qgraphicslayout.jsx";
import "qt/qgraphicsobject.jsx";
import "qt/qgraphicsscenemoveevent.jsx";
import "qt/qgraphicssceneresizeevent.jsx";
import "qt/qsizepolicy.jsx";
import "qt/qstyle.jsx";
import "qt/qstyleoption.jsx";
import "qt/_signals.jsx";

native class QGraphicsWidget extends QGraphicsObject
{
    function constructor ();

    // Static Members
    static function setTabOrder (first : QGraphicsWidget, second : QGraphicsWidget) : void;

    // Methods
    function actions () : QAction[];
    function addAction (action : QAction) : void;
    function addActions (actions : QAction[]) : void;
    function adjustSize () : void;
    function focusWidget () : QGraphicsWidget;
    function initStyleOption (option : QStyleOption) : void;
    function insertAction (before : QAction, action : QAction) : void;
    function insertActions (before : QAction, actions : QAction[]) : void;
    function moveEvent (event : QGraphicsSceneMoveEvent) : void;
    function polishEvent () : void;
    function propertyChange (propertyName : string, value : variant) : variant;
    function removeAction (action : QAction) : void;
    function resizeEvent (event : QGraphicsSceneResizeEvent) : void;
    function setStyle (style : QStyle) : void;
    function style () : QStyle;
    function unsetLayoutDirection () : void;
    function unsetWindowFrameMargins () : void;

    // Signals
    var geometryChanged : QtJSXSignal;
    var layoutChanged : QtJSXSignal;

    // Instance Properties
    var sizePolicy : QSizePolicy;
    var windowTitle : string;
    var layout : QGraphicsLayout;
}
