/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsProxyWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicswidget.jsx";
import "qt/qwidget.jsx";

native class QGraphicsProxyWidget extends QGraphicsWidget
{
    function constructor ();

    // Methods
    function createProxyForChildWidget (child : QWidget) : QGraphicsProxyWidget;
    function setWidget (widget : QWidget) : void;
    function widget () : QWidget;

    // Slots
    function newProxyWidget (arg__1 : QWidget) : QGraphicsProxyWidget;
}
