/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QGraphicsEffect_ChangeFlag {}

final native class Qt_QGraphicsEffect_ChangeFlags {}

native class QGraphicsEffect
{
    function constructor ();

    static const SourceAttached : Qt_QGraphicsEffect_ChangeFlag;
    static const SourceDetached : Qt_QGraphicsEffect_ChangeFlag;
    static const SourceBoundingRectChanged : Qt_QGraphicsEffect_ChangeFlag;
    static const SourceInvalidated : Qt_QGraphicsEffect_ChangeFlag;
    static function ChangeFlag(value : Qt_QGraphicsEffect_ChangeFlag) : Qt_QGraphicsEffect_ChangeFlag;
    static function ChangeFlags(...value : Qt_QGraphicsEffect_ChangeFlag) : Qt_QGraphicsEffect_ChangeFlags;

    // Methods
    function sourceChanged (flags : Qt_QGraphicsEffect_ChangeFlags) : void;
    function updateBoundingRect () : void;

    // Slots
    function update () : void;
}
