/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsColorizeEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";

native class QGraphicsColorizeEffect extends QGraphicsEffect
{
    function constructor ();
}
