/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsAnchorLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicslayout.jsx";
import "qt/qgraphicslayoutitem.jsx";

native class QGraphicsAnchorLayout extends QGraphicsLayout
{
    function constructor (parent : QGraphicsLayoutItem);
}
