/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneWheelEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

native class QGraphicsSceneWheelEvent extends QGraphicsSceneEvent
{
    function constructor ();
}
