/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSimpleTextItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractgraphicsshapeitem.jsx";
import "qt/qgraphicsitem.jsx";

native class QGraphicsSimpleTextItem extends QAbstractGraphicsShapeItem
{
    function constructor (parent : QGraphicsItem);
    function constructor (text : string, parent : QGraphicsItem);

    // Methods
    function setText (text : string) : void;
    function text () : string;
}
