/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneDragDropEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";
import "qt/qwidget.jsx";

native class QGraphicsSceneDragDropEvent extends QGraphicsSceneEvent
{
    function constructor ();

    // Methods
    function acceptProposedAction () : void;
    function source () : QWidget;
}
