/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsSceneMoveEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicssceneevent.jsx";

native class QGraphicsSceneMoveEvent extends QGraphicsSceneEvent
{
    function constructor ();
}
