/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsLayoutItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";
import "qt/qsizepolicy.jsx";

native class QGraphicsLayoutItem
{

    // Methods
    function graphicsItem () : QGraphicsItem;
    function parentLayoutItem () : QGraphicsLayoutItem;
    function setParentLayoutItem (parent : QGraphicsLayoutItem) : void;
    function setSizePolicy (hPolicy : Qt_QSizePolicy_Policy, vPolicy : Qt_QSizePolicy_Policy, controlType : Qt_QSizePolicy_ControlType) : void;
    function setSizePolicy (policy : QSizePolicy) : void;
    function sizePolicy () : QSizePolicy;
    function updateGeometry () : void;
}
