/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsOpacityEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicseffect.jsx";

native class QGraphicsOpacityEffect extends QGraphicsEffect
{
    function constructor ();
}
