/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsRotation class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicstransform.jsx";
import "qt/_signals.jsx";

native class QGraphicsRotation extends QGraphicsTransform
{

    // Signals
    var angleChanged : QtJSXSignal;
    var axisChanged : QtJSXSignal;
    var originChanged : QtJSXSignal;
}
