/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsTextItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicsitem.jsx";
import "qt/qgraphicsobject.jsx";
import "qt/_signals.jsx";

native class QGraphicsTextItem extends QGraphicsObject
{
    function constructor (parent : QGraphicsItem);
    function constructor (text : string, parent : QGraphicsItem);

    // Methods
    function adjustSize () : void;
    function setHtml (html : string) : void;
    function setPlainText (text : string) : void;
    function toHtml () : string;
    function toPlainText () : string;

    // Signals
    var linkActivated : QtJSXQStringSignal;
    var linkHovered : QtJSXQStringSignal;
}
