/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGraphicsGridLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgraphicslayout.jsx";
import "qt/qgraphicslayoutitem.jsx";

native class QGraphicsGridLayout extends QGraphicsLayout
{
    function constructor (parent : QGraphicsLayoutItem);

    // Methods
    function removeItem (item : QGraphicsLayoutItem) : void;
}
