/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGridLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";
import "qt/qwidget.jsx";

native class QGridLayout extends QLayout
{
    function constructor ();
    function constructor (parent : QWidget);
}
