/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGroupBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptiongroupbox.jsx";
import "qt/qwidget.jsx";

native class QGroupBox extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (title : string, parent : QWidget);

    // Methods
    function initStyleOption (option : QStyleOptionGroupBox) : void;

    // Instance Properties
    var title : string;
}
