/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QGuiApplication class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qclipboard.jsx";
import "qt/qcursor.jsx";
import "qt/qfont.jsx";
import "qt/qicon.jsx";
import "qt/qpalette.jsx";
import "qt/_signals.jsx";

native class QGuiApplication
{
    function constructor ();

    // Static Members
    static function changeOverrideCursor (arg__1 : QCursor) : void;
    static function clipboard () : QClipboard;
    static function font () : QFont;
    static function overrideCursor () : QCursor;
    static function palette () : QPalette;
    static function restoreOverrideCursor () : void;
    static function setFont (arg__1 : QFont) : void;
    static function setOverrideCursor (arg__1 : QCursor) : void;
    static function setPalette (pal : QPalette) : void;
    static function sync () : void;

    // Methods
    function sessionId () : string;
    function sessionKey () : string;

    // Signals
    var applicationDisplayNameChanged : QtJSXSignal;
    var fontChanged : QtJSXQFontSignal;
    var fontDatabaseChanged : QtJSXSignal;
    var lastWindowClosed : QtJSXSignal;
    var paletteChanged : QtJSXQPaletteSignal;

    // Instance Properties
    var windowIcon : QIcon;
    var applicationDisplayName : string;
    var desktopFileName : string;
    var platformName : string;
}
