/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QHeaderView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qstyleoptionheader.jsx";
import "qt/_signals.jsx";

final native class Qt_QHeaderView_ResizeMode {}

native class QHeaderView extends QAbstractItemView
{
    function constructor ();

    static const Interactive : Qt_QHeaderView_ResizeMode;
    static const Stretch : Qt_QHeaderView_ResizeMode;
    static const Fixed : Qt_QHeaderView_ResizeMode;
    static const ResizeToContents : Qt_QHeaderView_ResizeMode;
    static function ResizeMode(value : Qt_QHeaderView_ResizeMode) : Qt_QHeaderView_ResizeMode;

    // Methods
    function initStyleOption (option : QStyleOptionHeader) : void;
    function initialize () : void;
    function initializeSections () : void;
    function resetDefaultSectionSize () : void;
    function resizeSections (mode : Qt_QHeaderView_ResizeMode) : void;
    function setSectionResizeMode (mode : Qt_QHeaderView_ResizeMode) : void;

    // Slots
    function resizeSections () : void;
    function setOffsetToLastSection () : void;

    // Signals
    var geometriesChanged : QtJSXSignal;
}
