/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QHostInfo class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QHostInfo_HostInfoError {}

native class QHostInfo
{
    function constructor (d : QHostInfo);

    static const NoError : Qt_QHostInfo_HostInfoError;
    static const HostNotFound : Qt_QHostInfo_HostInfoError;
    static const UnknownError : Qt_QHostInfo_HostInfoError;
    static function HostInfoError(value : Qt_QHostInfo_HostInfoError) : Qt_QHostInfo_HostInfoError;
}
