/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QImageWriter class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QImageWriter_ImageWriterError {}

native class QImageWriter
{
    function constructor ();

    static const UnknownError : Qt_QImageWriter_ImageWriterError;
    static const DeviceError : Qt_QImageWriter_ImageWriterError;
    static const UnsupportedFormatError : Qt_QImageWriter_ImageWriterError;
    static const InvalidImageError : Qt_QImageWriter_ImageWriterError;
    static function ImageWriterError(value : Qt_QImageWriter_ImageWriterError) : Qt_QImageWriter_ImageWriterError;

    // Methods
    function error () : Qt_QImageWriter_ImageWriterError;
    function errorString () : string;
    function fileName () : string;
    function setFileName (fileName : string) : void;
    function setText (key : string, text : string) : void;
}
