/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QImageReader class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qcolor.jsx";
import "qt/qimage.jsx";
import "qt/qimageiohandler.jsx";
import "qt/qiodevice.jsx";
import "qt/qrect.jsx";
import "qt/qsize.jsx";

final native class Qt_QImageReader_ImageReaderError {}

native class QImageReader
{
    function constructor ();
    function constructor (device : QIODevice, format : QByteArray);
    function constructor (fileName : string, format : QByteArray);

    // Static Members
    static function imageFormat (device : QIODevice) : QByteArray;
    static function imageFormatsForMimeType (mimeType : QByteArray) : QByteArray[];
    static function supportedImageFormats () : QByteArray[];
    static function supportedMimeTypes () : QByteArray[];
    static function tr (sourceText : string, disambiguation : string, n : int) : string;
    static function trUtf8 (sourceText : string, disambiguation : string, n : int) : string;

    static const UnknownError : Qt_QImageReader_ImageReaderError;
    static const FileNotFoundError : Qt_QImageReader_ImageReaderError;
    static const DeviceError : Qt_QImageReader_ImageReaderError;
    static const UnsupportedFormatError : Qt_QImageReader_ImageReaderError;
    static const InvalidDataError : Qt_QImageReader_ImageReaderError;
    static function ImageReaderError(value : Qt_QImageReader_ImageReaderError) : Qt_QImageReader_ImageReaderError;

    // Methods
    function autoDetectImageFormat () : boolean;
    function autoTransform () : boolean;
    function backgroundColor () : QColor;
    function canRead () : boolean;
    function clipRect () : QRect;
    function currentImageNumber () : int;
    function currentImageRect () : QRect;
    function decideFormatFromContent () : boolean;
    function device () : QIODevice;
    function error () : Qt_QImageReader_ImageReaderError;
    function errorString () : string;
    function fileName () : string;
    function format () : QByteArray;
    function gamma () : number;
    function imageCount () : int;
    function imageFormat () : Qt_QImage_Format;
    function jumpToImage (imageNumber : int) : boolean;
    function jumpToNextImage () : boolean;
    function loopCount () : int;
    function nextImageDelay () : int;
    function quality () : int;
    function read () : QImage;
    function scaledClipRect () : QRect;
    function scaledSize () : QSize;
    function setAutoDetectImageFormat (enabled : boolean) : void;
    function setAutoTransform (enabled : boolean) : void;
    function setBackgroundColor (color : QColor) : void;
    function setClipRect (rect : QRect) : void;
    function setDecideFormatFromContent (ignored : boolean) : void;
    function setDevice (device : QIODevice) : void;
    function setFileName (fileName : string) : void;
    function setFormat (format : QByteArray) : void;
    function setGamma (gamma : number) : void;
    function setQuality (quality : int) : void;
    function setScaledClipRect (rect : QRect) : void;
    function setScaledSize (size : QSize) : void;
    function size () : QSize;
    function subType () : QByteArray;
    function supportedSubTypes () : QByteArray[];
    function supportsAnimation () : boolean;
    function supportsOption (option : Qt_QImageIOHandler_ImageOption) : boolean;
    function text (key : string) : string;
    function textKeys () : string[];
}
