/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QImage class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QImage_InvertMode {}

final native class Qt_QImage_Format {}

native class QImage
{
    function constructor (arg__1 : QImage);

    static const InvertRgb : Qt_QImage_InvertMode;
    static const InvertRgba : Qt_QImage_InvertMode;
    static function InvertMode(value : Qt_QImage_InvertMode) : Qt_QImage_InvertMode;

    static const Format_Invalid : Qt_QImage_Format;
    static const Format_Mono : Qt_QImage_Format;
    static const Format_MonoLSB : Qt_QImage_Format;
    static const Format_Indexed8 : Qt_QImage_Format;
    static const Format_RGB32 : Qt_QImage_Format;
    static const Format_ARGB32 : Qt_QImage_Format;
    static const Format_ARGB32_Premultiplied : Qt_QImage_Format;
    static const Format_RGB16 : Qt_QImage_Format;
    static const Format_ARGB8565_Premultiplied : Qt_QImage_Format;
    static const Format_RGB666 : Qt_QImage_Format;
    static const Format_ARGB6666_Premultiplied : Qt_QImage_Format;
    static const Format_RGB555 : Qt_QImage_Format;
    static const Format_ARGB8555_Premultiplied : Qt_QImage_Format;
    static const Format_RGB888 : Qt_QImage_Format;
    static const Format_RGB444 : Qt_QImage_Format;
    static const Format_ARGB4444_Premultiplied : Qt_QImage_Format;
    static const Format_RGBX8888 : Qt_QImage_Format;
    static const Format_RGBA8888 : Qt_QImage_Format;
    static const Format_RGBA8888_Premultiplied : Qt_QImage_Format;
    static const Format_BGR30 : Qt_QImage_Format;
    static const Format_A2BGR30_Premultiplied : Qt_QImage_Format;
    static const Format_RGB30 : Qt_QImage_Format;
    static const Format_A2RGB30_Premultiplied : Qt_QImage_Format;
    static const Format_Alpha8 : Qt_QImage_Format;
    static const Format_Grayscale8 : Qt_QImage_Format;
    static const Format_RGBX64 : Qt_QImage_Format;
    static const Format_RGBA64 : Qt_QImage_Format;
    static const Format_RGBA64_Premultiplied : Qt_QImage_Format;
    static const Format_Grayscale16 : Qt_QImage_Format;
    static const Format_BGR888 : Qt_QImage_Format;
    static const NImageFormats : Qt_QImage_Format;
    static function Format(value : Qt_QImage_Format) : Qt_QImage_Format;
}
