/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QImageReader class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qimage.jsx";

final native class Qt_QImageReader_ImageReaderError {}

native class QImageReader
{
    function constructor ();

    static const UnknownError : Qt_QImageReader_ImageReaderError;
    static const FileNotFoundError : Qt_QImageReader_ImageReaderError;
    static const DeviceError : Qt_QImageReader_ImageReaderError;
    static const UnsupportedFormatError : Qt_QImageReader_ImageReaderError;
    static const InvalidDataError : Qt_QImageReader_ImageReaderError;
    static function ImageReaderError(value : Qt_QImageReader_ImageReaderError) : Qt_QImageReader_ImageReaderError;

    // Methods
    function backgroundColor () : QColor;
    function error () : Qt_QImageReader_ImageReaderError;
    function errorString () : string;
    function fileName () : string;
    function imageFormat () : Qt_QImage_Format;
    function read () : QImage;
    function setBackgroundColor (color : QColor) : void;
    function setFileName (fileName : string) : void;
    function text (key : string) : string;
    function textKeys () : string[];
}
