/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QImageIOPlugin class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QImageIOPlugin_Capability {}

final native class Qt_QImageIOPlugin_Capabilities {}

native class QImageIOPlugin
{

    static const CanRead : Qt_QImageIOPlugin_Capability;
    static const CanWrite : Qt_QImageIOPlugin_Capability;
    static const CanReadIncremental : Qt_QImageIOPlugin_Capability;
    static function Capability(value : Qt_QImageIOPlugin_Capability) : Qt_QImageIOPlugin_Capability;
    static function Capabilities(...value : Qt_QImageIOPlugin_Capability) : Qt_QImageIOPlugin_Capabilities;
}
