/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QInputDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdialog.jsx";
import "qt/qlineedit.jsx";
import "qt/_signals.jsx";

final native class Qt_QInputDialog_InputDialogOption {}

final native class Qt_QInputDialog_InputDialogOptions {}

final native class Qt_QInputDialog_InputMode {}

native class QInputDialog extends QDialog
{
    function constructor ();

    static const NoButtons : Qt_QInputDialog_InputDialogOption;
    static const UseListViewForComboBoxItems : Qt_QInputDialog_InputDialogOption;
    static const UsePlainTextEditForTextInput : Qt_QInputDialog_InputDialogOption;
    static function InputDialogOption(value : Qt_QInputDialog_InputDialogOption) : Qt_QInputDialog_InputDialogOption;
    static function InputDialogOptions(...value : Qt_QInputDialog_InputDialogOption) : Qt_QInputDialog_InputDialogOptions;

    static const TextInput : Qt_QInputDialog_InputMode;
    static const IntInput : Qt_QInputDialog_InputMode;
    static const DoubleInput : Qt_QInputDialog_InputMode;
    static function InputMode(value : Qt_QInputDialog_InputMode) : Qt_QInputDialog_InputMode;

    // Methods
    function cancelButtonText () : string;
    function comboBoxItems () : string[];
    function inputMode () : Qt_QInputDialog_InputMode;
    function labelText () : string;
    function okButtonText () : string;
    function options () : Qt_QInputDialog_InputDialogOptions;
    function setCancelButtonText (text : string) : void;
    function setComboBoxItems (items : string[]) : void;
    function setInputMode (mode : Qt_QInputDialog_InputMode) : void;
    function setLabelText (text : string) : void;
    function setOkButtonText (text : string) : void;
    function setOptions (options : Qt_QInputDialog_InputDialogOptions) : void;
    function setTextEchoMode (mode : Qt_QLineEdit_EchoMode) : void;
    function setTextValue (text : string) : void;
    function textEchoMode () : Qt_QLineEdit_EchoMode;
    function textValue () : string;

    // Signals
    var textValueChanged : QtJSXQStringSignal;
    var textValueSelected : QtJSXQStringSignal;
}
