/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QIntValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qvalidator.jsx";

native class QIntValidator extends QValidator
{
    function constructor ();
}
