/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QIntValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qvalidator.jsx";
import "qt/_signals.jsx";

native class QIntValidator
{
    function constructor (parent : QObject);
    function constructor (bottom : int, top : int, parent : QObject);

    // Methods
    function fixup (input : string) : void;
    function setRange (bottom : int, top : int) : void;
    function validate (arg__1 : string, arg__2 : int) : Qt_QValidator_State;

    // Signals
    var bottomChanged : QtJSXintSignal;
    var topChanged : QtJSXintSignal;

    // Instance Properties
    var bottom : int;
    var top : int;
}
