/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QItemDelegate class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemdelegate.jsx";
import "qt/qitemeditorfactory.jsx";

native class QItemDelegate extends QAbstractItemDelegate
{
    function constructor ();

    // Methods
    function itemEditorFactory () : QItemEditorFactory;
    function setItemEditorFactory (factory : QItemEditorFactory) : void;
}
