/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QItemSelectionModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qitemselection.jsx";
import "qt/_signals.jsx";

final native class Qt_QItemSelectionModel_SelectionFlag {}

final native class Qt_QItemSelectionModel_SelectionFlags {}

native class QItemSelectionModel
{
    function constructor ();

    static const NoUpdate : Qt_QItemSelectionModel_SelectionFlag;
    static const Clear : Qt_QItemSelectionModel_SelectionFlag;
    static const Select : Qt_QItemSelectionModel_SelectionFlag;
    static const ClearAndSelect : Qt_QItemSelectionModel_SelectionFlag;
    static const Deselect : Qt_QItemSelectionModel_SelectionFlag;
    static const Toggle : Qt_QItemSelectionModel_SelectionFlag;
    static const Current : Qt_QItemSelectionModel_SelectionFlag;
    static const SelectCurrent : Qt_QItemSelectionModel_SelectionFlag;
    static const ToggleCurrent : Qt_QItemSelectionModel_SelectionFlag;
    static const Rows : Qt_QItemSelectionModel_SelectionFlag;
    static const Columns : Qt_QItemSelectionModel_SelectionFlag;
    static function SelectionFlag(value : Qt_QItemSelectionModel_SelectionFlag) : Qt_QItemSelectionModel_SelectionFlag;
    static function SelectionFlags(...value : Qt_QItemSelectionModel_SelectionFlag) : Qt_QItemSelectionModel_SelectionFlags;

    // Methods
    function emitSelectionChanged (newSelection : QItemSelection, oldSelection : QItemSelection) : void;

    // Slots
    function clear () : void;
    function clearCurrentIndex () : void;
    function clearSelection () : void;
    function reset () : void;
    function select (selection : QItemSelection, command : Qt_QItemSelectionModel_SelectionFlags) : void;

    // Signals
    var selectionChanged : QtJSXQItemSelectionQItemSelectionSignal;

    // Instance Properties
    var selection : QItemSelection;
}
