/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QItemEditorCreatorBase class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";

native class QItemEditorCreatorBase
{
    function constructor ();

    // Methods
    function createWidget (parent : QWidget) : QWidget;
}
