/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QItemEditorFactory class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QItemEditorFactory
{
    function constructor ();

    // Static Members
    static function defaultFactory () : QItemEditorFactory;
    static function setDefaultFactory (factory : QItemEditorFactory) : void;
}
