/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QItemSelection class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qitemselectionmodel.jsx";
import "qt/qitemselectionrange.jsx";
import "qt/qmodelindex.jsx";

native class QItemSelection
{
    function constructor ();
    function constructor (topLeft : QModelIndex, bottomRight : QModelIndex);

    // Static Members
    static function split (range : QItemSelectionRange, other : QItemSelectionRange, result : QItemSelection) : void;

    // Methods
    function contains (index : QModelIndex) : boolean;
    function indexes () : QModelIndex[];
    function merge (other : QItemSelection, command : Qt_QItemSelectionModel_SelectionFlags) : void;
    function select (topLeft : QModelIndex, bottomRight : QModelIndex) : void;
}
