/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QItemSelection class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qitemselectionmodel.jsx";
import "qt/qitemselectionrange.jsx";

native class QItemSelection
{

    // Static Members
    static function split (range : QItemSelectionRange, other : QItemSelectionRange, result : QItemSelection) : void;

    // Methods
    function merge (other : QItemSelection, command : Qt_QItemSelectionModel_SelectionFlags) : void;
}
