/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QKeyEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qinputevent.jsx";

native class QKeyEvent extends QInputEvent
{

    // Methods
    function text () : string;
}
