/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLabel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QLabel extends QFrame
{
    function constructor ();

    // Methods
    function buddy () : QWidget;
    function setBuddy (arg__1 : QWidget) : void;

    // Slots
    function clear () : void;

    // Signals
    var linkActivated : QtJSXQStringSignal;
    var linkHovered : QtJSXQStringSignal;

    // Instance Properties
    var text : string;
    var selectedText : string;
}
