/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLayoutItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayout.jsx";
import "qt/qsizepolicy.jsx";
import "qt/qspaceritem.jsx";
import "qt/qwidget.jsx";

native class QLayoutItem
{

    // Methods
    function controlTypes () : Qt_QSizePolicy_ControlTypes;
    function invalidate () : void;
    function layout () : QLayout;
    function spacerItem () : QSpacerItem;
    function widget () : QWidget;
}
