/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayoutitem.jsx";
import "qt/qwidget.jsx";

final native class Qt_QLayout_SizeConstraint {}

native class QLayout
{
    function constructor ();
    function constructor (parent : QWidget);

    static const SetDefaultConstraint : Qt_QLayout_SizeConstraint;
    static const SetNoConstraint : Qt_QLayout_SizeConstraint;
    static const SetMinimumSize : Qt_QLayout_SizeConstraint;
    static const SetFixedSize : Qt_QLayout_SizeConstraint;
    static const SetMaximumSize : Qt_QLayout_SizeConstraint;
    static const SetMinAndMaxSize : Qt_QLayout_SizeConstraint;
    static function SizeConstraint(value : Qt_QLayout_SizeConstraint) : Qt_QLayout_SizeConstraint;

    // Methods
    function addChildLayout (l : QLayout) : void;
    function addChildWidget (w : QWidget) : void;
    function addItem (arg__1 : QLayoutItem) : void;
    function addWidget (w : QWidget) : void;
    function menuBar () : QWidget;
    function parentWidget () : QWidget;
    function removeItem (arg__1 : QLayoutItem) : void;
    function removeWidget (w : QWidget) : void;
    function setMenuBar (w : QWidget) : void;
    function update () : void;

    // Instance Properties
    var sizeConstraint : Qt_QLayout_SizeConstraint;
}
