/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLCDNumber class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QLCDNumber_SegmentStyle {}

final native class Qt_QLCDNumber_Mode {}

native class QLCDNumber extends QFrame
{
    function constructor (parent : QWidget);
    function constructor (numDigits : int, parent : QWidget);

    static const Outline : Qt_QLCDNumber_SegmentStyle;
    static const Filled : Qt_QLCDNumber_SegmentStyle;
    static const Flat : Qt_QLCDNumber_SegmentStyle;
    static function SegmentStyle(value : Qt_QLCDNumber_SegmentStyle) : Qt_QLCDNumber_SegmentStyle;

    static const Hex : Qt_QLCDNumber_Mode;
    static const Dec : Qt_QLCDNumber_Mode;
    static const Oct : Qt_QLCDNumber_Mode;
    static const Bin : Qt_QLCDNumber_Mode;
    static function Mode(value : Qt_QLCDNumber_Mode) : Qt_QLCDNumber_Mode;

    // Methods
    function checkOverflow (num : number) : boolean;
    function checkOverflow (num : int) : boolean;
    function display (str : string) : void;
    function display (num : int) : void;
    function setBinMode () : void;
    function setDecMode () : void;
    function setHexMode () : void;
    function setOctMode () : void;

    // Signals
    var overflow : QtJSXSignal;

    // Instance Properties
    var smallDecimalPoint : boolean;
    var digitCount : int;
    var mode : Qt_QLCDNumber_Mode;
    var segmentStyle : Qt_QLCDNumber_SegmentStyle;
    var value : number;
    var intValue : int;
}
