/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLCDNumber class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QLCDNumber_Mode {}

native class QLCDNumber extends QFrame
{
    function constructor (parent : QWidget);

    static const Hex : Qt_QLCDNumber_Mode;
    static const Dec : Qt_QLCDNumber_Mode;
    static const Oct : Qt_QLCDNumber_Mode;
    static const Bin : Qt_QLCDNumber_Mode;
    static function Mode(value : Qt_QLCDNumber_Mode) : Qt_QLCDNumber_Mode;

    // Slots
    function display (str : string) : void;
    function setBinMode () : void;
    function setDecMode () : void;
    function setHexMode () : void;
    function setOctMode () : void;

    // Signals
    var overflow : QtJSXSignal;

    // Instance Properties
    var mode : Qt_QLCDNumber_Mode;
    var segmentStyle : Qt_QLCDNumber_SegmentStyle;
}
