/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLineEdit class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcompleter.jsx";
import "qt/qmenu.jsx";
import "qt/qstyleoptionframe.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QLineEdit_EchoMode {}

native class QLineEdit extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (arg__1 : string, parent : QWidget);

    static const Normal : Qt_QLineEdit_EchoMode;
    static const NoEcho : Qt_QLineEdit_EchoMode;
    static const Password : Qt_QLineEdit_EchoMode;
    static const PasswordEchoOnEdit : Qt_QLineEdit_EchoMode;
    static function EchoMode(value : Qt_QLineEdit_EchoMode) : Qt_QLineEdit_EchoMode;

    // Methods
    function backspace () : void;
    function completer () : QCompleter;
    function createStandardContextMenu () : QMenu;
    function del () : void;
    function deselect () : void;
    function initStyleOption (option : QStyleOptionFrame) : void;
    function insert (arg__1 : string) : void;
    function setCompleter (completer : QCompleter) : void;

    // Slots
    function clear () : void;
    function copy () : void;
    function cut () : void;
    function paste () : void;
    function redo () : void;
    function selectAll () : void;
    function undo () : void;

    // Signals
    var editingFinished : QtJSXSignal;
    var inputRejected : QtJSXSignal;
    var returnPressed : QtJSXSignal;
    var selectionChanged : QtJSXSignal;
    var textChanged : QtJSXQStringSignal;
    var textEdited : QtJSXQStringSignal;

    // Instance Properties
    var inputMask : string;
    var text : string;
    var echoMode : Qt_QLineEdit_EchoMode;
    var displayText : string;
    var selectedText : string;
    var placeholderText : string;
}
