/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLinearGradient class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgradient.jsx";

native class QLinearGradient extends QGradient
{
    function constructor ();
}
