/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLineF class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qline.jsx";

final native class Qt_QLineF_IntersectType {}

native class QLineF
{
    function constructor ();
    function constructor (line : QLine);

    static const NoIntersection : Qt_QLineF_IntersectType;
    static const BoundedIntersection : Qt_QLineF_IntersectType;
    static const UnboundedIntersection : Qt_QLineF_IntersectType;
    static function IntersectType(value : Qt_QLineF_IntersectType) : Qt_QLineF_IntersectType;

    // Methods
    function normalVector () : QLineF;
    function toLine () : QLine;
    function unitVector () : QLineF;
}
