/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QListWidgetItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlistwidget.jsx";

final native class Qt_QListWidgetItem_ItemType {}

native class QListWidgetItem
{

    static const Type : Qt_QListWidgetItem_ItemType;
    static const UserType : Qt_QListWidgetItem_ItemType;
    static function ItemType(value : Qt_QListWidgetItem_ItemType) : Qt_QListWidgetItem_ItemType;

    // Methods
    function clone () : QListWidgetItem;
    function listWidget () : QListWidget;
    function setStatusTip (statusTip : string) : void;
    function setText (text : string) : void;
    function setToolTip (toolTip : string) : void;
    function setWhatsThis (whatsThis : string) : void;
    function statusTip () : string;
    function text () : string;
    function toolTip () : string;
    function whatsThis () : string;
}
