/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QListWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qitemselectionmodel.jsx";
import "qt/qlistview.jsx";
import "qt/qlistwidgetitem.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QListWidget extends QListView
{
    function constructor (parent : QWidget);

    // Methods
    function addItem (item : QListWidgetItem) : void;
    function addItem (label : string) : void;
    function addItems (labels : string[]) : void;
    function closePersistentEditor (item : QListWidgetItem) : void;
    function currentItem () : QListWidgetItem;
    function editItem (item : QListWidgetItem) : void;
    function itemWidget (item : QListWidgetItem) : QWidget;
    function mimeTypes () : string[];
    function openPersistentEditor (item : QListWidgetItem) : void;
    function removeItemWidget (item : QListWidgetItem) : void;
    function selectedItems () : QListWidgetItem[];
    function setCurrentItem (item : QListWidgetItem) : void;
    function setCurrentItem (item : QListWidgetItem, command : Qt_QItemSelectionModel_SelectionFlags) : void;
    function setItemWidget (item : QListWidgetItem, widget : QWidget) : void;

    // Slots
    function clear () : void;
    function scrollToItem (item : QListWidgetItem, hint : Qt_QAbstractItemView_ScrollHint) : void;

    // Signals
    var currentItemChanged : QtJSXQListWidgetItemQListWidgetItemSignal;
    var currentTextChanged : QtJSXQStringSignal;
    var itemActivated : QtJSXQListWidgetItemSignal;
    var itemChanged : QtJSXQListWidgetItemSignal;
    var itemClicked : QtJSXQListWidgetItemSignal;
    var itemDoubleClicked : QtJSXQListWidgetItemSignal;
    var itemEntered : QtJSXQListWidgetItemSignal;
    var itemPressed : QtJSXQListWidgetItemSignal;
    var itemSelectionChanged : QtJSXSignal;
}
