/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QListView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qwidget.jsx";

final native class Qt_QListView_Movement {}

native class QListView extends QAbstractItemView
{
    function constructor (parent : QWidget);

    static const Static : Qt_QListView_Movement;
    static const Free : Qt_QListView_Movement;
    static const Snap : Qt_QListView_Movement;
    static function Movement(value : Qt_QListView_Movement) : Qt_QListView_Movement;

    // Methods
    function clearPropertyFlags () : void;

    // Instance Properties
    var movement : Qt_QListView_Movement;
    var flow : Qt_QListView_Flow;
    var resizeMode : Qt_QListView_ResizeMode;
    var layoutMode : Qt_QListView_LayoutMode;
    var viewMode : Qt_QListView_ViewMode;
}
