/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QLocalServer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractsocket.jsx";
import "qt/qlocalsocket.jsx";
import "qt/_signals.jsx";

native class QLocalServer
{
    function constructor ();

    // Methods
    function close () : void;
    function errorString () : string;
    function fullServerName () : string;
    function nextPendingConnection () : QLocalSocket;
    function serverError () : Qt_QAbstractSocket_SocketError;
    function serverName () : string;

    // Signals
    var newConnection : QtJSXSignal;
}
