/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMainWindow class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdockwidget.jsx";
import "qt/qmenu.jsx";
import "qt/qmenubar.jsx";
import "qt/qstatusbar.jsx";
import "qt/qtabwidget.jsx";
import "qt/qtoolbar.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QMainWindow_DockOption {}

final native class Qt_QMainWindow_DockOptions {}

native class QMainWindow extends QWidget
{
    function constructor ();

    static const AnimatedDocks : Qt_QMainWindow_DockOption;
    static const AllowNestedDocks : Qt_QMainWindow_DockOption;
    static const AllowTabbedDocks : Qt_QMainWindow_DockOption;
    static const ForceTabbedDocks : Qt_QMainWindow_DockOption;
    static const VerticalTabs : Qt_QMainWindow_DockOption;
    static const GroupedDragging : Qt_QMainWindow_DockOption;
    static function DockOption(value : Qt_QMainWindow_DockOption) : Qt_QMainWindow_DockOption;
    static function DockOptions(...value : Qt_QMainWindow_DockOption) : Qt_QMainWindow_DockOptions;

    // Methods
    function addToolBar (toolbar : QToolBar) : void;
    function addToolBar (title : string) : QToolBar;
    function centralWidget () : QWidget;
    function createPopupMenu () : QMenu;
    function insertToolBar (before : QToolBar, toolbar : QToolBar) : void;
    function insertToolBarBreak (before : QToolBar) : void;
    function menuBar () : QMenuBar;
    function menuWidget () : QWidget;
    function removeDockWidget (dockwidget : QDockWidget) : void;
    function removeToolBar (toolbar : QToolBar) : void;
    function removeToolBarBreak (before : QToolBar) : void;
    function setCentralWidget (widget : QWidget) : void;
    function setMenuBar (menubar : QMenuBar) : void;
    function setMenuWidget (menubar : QWidget) : void;
    function setStatusBar (statusbar : QStatusBar) : void;
    function statusBar () : QStatusBar;
    function tabifiedDockWidgets (dockwidget : QDockWidget) : QDockWidget[];
    function tabifyDockWidget (first : QDockWidget, second : QDockWidget) : void;
    function takeCentralWidget () : QWidget;

    // Signals
    var tabifiedDockWidgetActivated : QtJSXQDockWidgetSignal;

    // Instance Properties
    var tabShape : Qt_QTabWidget_TabShape;
    var dockOptions : Qt_QMainWindow_DockOptions;
}
