/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMatrix4x4 class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmatrix.jsx";
import "qt/qmatrix3x3.jsx";
import "qt/qquaternion.jsx";
import "qt/qtransform.jsx";
import "qt/qvector3d.jsx";
import "qt/qvector4d.jsx";

native class QMatrix4x4
{
    function constructor ();
    function constructor (matrix : QMatrix);
    function constructor (transform : QTransform);

    // Methods
    function flipCoordinates () : void;
    function lookAt (eye : QVector3D, center : QVector3D, up : QVector3D) : void;
    function map (point : QVector3D) : QVector3D;
    function map (point : QVector4D) : QVector4D;
    function mapVector (vector : QVector3D) : QVector3D;
    function normalMatrix () : QMatrix3x3;
    function operator_add_assign (other : QMatrix4x4) : QMatrix4x4;
    function operator_multiply_assign (other : QMatrix4x4) : QMatrix4x4;
    function operator_subtract_assign (other : QMatrix4x4) : QMatrix4x4;
    function optimize () : void;
    function rotate (quaternion : QQuaternion) : void;
    function scale (vector : QVector3D) : void;
    function setToIdentity () : void;
    function toAffine () : QMatrix;
    function toTransform () : QTransform;
    function translate (vector : QVector3D) : void;
    function transposed () : QMatrix4x4;
}
