/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMdiSubWindow class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmdiarea.jsx";
import "qt/qmenu.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QMdiSubWindow_SubWindowOption {}

final native class Qt_QMdiSubWindow_SubWindowOptions {}

native class QMdiSubWindow extends QWidget
{
    function constructor ();

    static const AllowOutsideAreaHorizontally : Qt_QMdiSubWindow_SubWindowOption;
    static const AllowOutsideAreaVertically : Qt_QMdiSubWindow_SubWindowOption;
    static const RubberBandResize : Qt_QMdiSubWindow_SubWindowOption;
    static const RubberBandMove : Qt_QMdiSubWindow_SubWindowOption;
    static function SubWindowOption(value : Qt_QMdiSubWindow_SubWindowOption) : Qt_QMdiSubWindow_SubWindowOption;
    static function SubWindowOptions(...value : Qt_QMdiSubWindow_SubWindowOption) : Qt_QMdiSubWindow_SubWindowOptions;

    // Methods
    function maximizedButtonsWidget () : QWidget;
    function maximizedSystemMenuIconWidget () : QWidget;
    function mdiArea () : QMdiArea;
    function setSystemMenu (systemMenu : QMenu) : void;
    function setWidget (widget : QWidget) : void;
    function systemMenu () : QMenu;
    function widget () : QWidget;

    // Slots
    function showShaded () : void;
    function showSystemMenu () : void;

    // Signals
    var aboutToActivate : QtJSXSignal;
}
