/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMdiSubWindow class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qchildevent.jsx";
import "qt/qevent.jsx";
import "qt/qmdiarea.jsx";
import "qt/qmenu.jsx";
import "qt/qobject.jsx";
import "qt/qt.jsx";
import "qt/qtimerevent.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QMdiSubWindow_SubWindowOption {}

final native class Qt_QMdiSubWindow_SubWindowOptions {}

native class QMdiSubWindow extends QWidget
{
    function constructor (parent : QWidget, flags : Qt_WindowFlags);

    static const AllowOutsideAreaHorizontally : Qt_QMdiSubWindow_SubWindowOption;
    static const AllowOutsideAreaVertically : Qt_QMdiSubWindow_SubWindowOption;
    static const RubberBandResize : Qt_QMdiSubWindow_SubWindowOption;
    static const RubberBandMove : Qt_QMdiSubWindow_SubWindowOption;
    static function SubWindowOption(value : Qt_QMdiSubWindow_SubWindowOption) : Qt_QMdiSubWindow_SubWindowOption;
    static function SubWindowOptions(...value : Qt_QMdiSubWindow_SubWindowOption) : Qt_QMdiSubWindow_SubWindowOptions;

    // Methods
    function childEvent (childEvent : QChildEvent) : void;
    function eventFilter (object : QObject, event : QEvent) : boolean;
    function isShaded () : boolean;
    function maximizedButtonsWidget () : QWidget;
    function maximizedSystemMenuIconWidget () : QWidget;
    function mdiArea () : QMdiArea;
    function setOption (option : Qt_QMdiSubWindow_SubWindowOption, on : boolean) : void;
    function setSystemMenu (systemMenu : QMenu) : void;
    function setWidget (widget : QWidget) : void;
    function showShaded () : void;
    function showSystemMenu () : void;
    function systemMenu () : QMenu;
    function testOption (arg__1 : Qt_QMdiSubWindow_SubWindowOption) : boolean;
    function timerEvent (timerEvent : QTimerEvent) : void;
    function widget () : QWidget;

    // Signals
    var aboutToActivate : QtJSXSignal;
    var windowStateChanged : QtJSXQt_WindowStatesQt_WindowStatesSignal;

    // Instance Properties
    var keyboardSingleStep : int;
    var keyboardPageStep : int;
}
