/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMdiArea class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractscrollarea.jsx";
import "qt/qmdisubwindow.jsx";
import "qt/qtabwidget.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QMdiArea_WindowOrder {}

final native class Qt_QMdiArea_AreaOption {}

final native class Qt_QMdiArea_AreaOptions {}

native class QMdiArea extends QAbstractScrollArea
{
    function constructor (parent : QWidget);

    static const CreationOrder : Qt_QMdiArea_WindowOrder;
    static const StackingOrder : Qt_QMdiArea_WindowOrder;
    static const ActivationHistoryOrder : Qt_QMdiArea_WindowOrder;
    static function WindowOrder(value : Qt_QMdiArea_WindowOrder) : Qt_QMdiArea_WindowOrder;

    static const DontMaximizeSubWindowOnActivation : Qt_QMdiArea_AreaOption;
    static function AreaOption(value : Qt_QMdiArea_AreaOption) : Qt_QMdiArea_AreaOption;
    static function AreaOptions(...value : Qt_QMdiArea_AreaOption) : Qt_QMdiArea_AreaOptions;

    // Methods
    function activeSubWindow () : QMdiSubWindow;
    function currentSubWindow () : QMdiSubWindow;
    function removeSubWindow (widget : QWidget) : void;
    function subWindowList (order : Qt_QMdiArea_WindowOrder) : QMdiSubWindow[];

    // Slots
    function activateNextSubWindow () : void;
    function activatePreviousSubWindow () : void;
    function cascadeSubWindows () : void;
    function closeActiveSubWindow () : void;
    function closeAllSubWindows () : void;
    function setActiveSubWindow (window : QMdiSubWindow) : void;
    function tileSubWindows () : void;

    // Signals
    var subWindowActivated : QtJSXQMdiSubWindowSignal;

    // Instance Properties
    var activationOrder : Qt_QMdiArea_WindowOrder;
    var viewMode : Qt_QMdiArea_ViewMode;
    var tabShape : Qt_QTabWidget_TabShape;
    var tabPosition : Qt_QTabWidget_TabPosition;
}
