/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMenuBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qmenu.jsx";
import "qt/qstyleoptionmenuitem.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QMenuBar extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function activeAction () : QAction;
    function addAction (text : string) : QAction;
    function addMenu (menu : QMenu) : QAction;
    function addMenu (title : string) : QMenu;
    function addSeparator () : QAction;
    function clear () : void;
    function initStyleOption (option : QStyleOptionMenuItem, action : QAction) : void;
    function insertMenu (before : QAction, menu : QMenu) : QAction;
    function insertSeparator (before : QAction) : QAction;
    function setActiveAction (action : QAction) : void;

    // Signals
    var hovered : QtJSXQActionSignal;
    var triggered : QtJSXQActionSignal;
}
