/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMenu class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qstyleoptionmenuitem.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QMenu extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (title : string, parent : QWidget);

    // Methods
    function activeAction () : QAction;
    function addAction (text : string) : QAction;
    function addMenu (menu : QMenu) : QAction;
    function addMenu (title : string) : QMenu;
    function addSection (text : string) : QAction;
    function addSeparator () : QAction;
    function clear () : void;
    function defaultAction () : QAction;
    function exec () : QAction;
    function hideTearOffMenu () : void;
    function initStyleOption (option : QStyleOptionMenuItem, action : QAction) : void;
    function insertMenu (before : QAction, menu : QMenu) : QAction;
    function insertSection (before : QAction, text : string) : QAction;
    function insertSeparator (before : QAction) : QAction;
    function menuAction () : QAction;
    function setActiveAction (act : QAction) : void;
    function setDefaultAction (arg__1 : QAction) : void;
    function showTearOffMenu () : void;

    // Signals
    var aboutToHide : QtJSXSignal;
    var aboutToShow : QtJSXSignal;
    var hovered : QtJSXQActionSignal;
    var triggered : QtJSXQActionSignal;

    // Instance Properties
    var title : string;
}
