/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QMovie class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qimage.jsx";
import "qt/qimagereader.jsx";
import "qt/qpixmap.jsx";
import "qt/_signals.jsx";

final native class Qt_QMovie_MovieState {}

native class QMovie
{
    function constructor ();

    static const NotRunning : Qt_QMovie_MovieState;
    static const Paused : Qt_QMovie_MovieState;
    static const Running : Qt_QMovie_MovieState;
    static function MovieState(value : Qt_QMovie_MovieState) : Qt_QMovie_MovieState;

    // Methods
    function backgroundColor () : QColor;
    function currentImage () : QImage;
    function currentPixmap () : QPixmap;
    function fileName () : string;
    function lastError () : Qt_QImageReader_ImageReaderError;
    function lastErrorString () : string;
    function setBackgroundColor (color : QColor) : void;
    function setFileName (fileName : string) : void;
    function state () : Qt_QMovie_MovieState;

    // Slots
    function start () : void;
    function stop () : void;

    // Signals
    var error : QtJSXQt_QImageReader_ImageReaderErrorSignal;
    var finished : QtJSXSignal;
    var started : QtJSXSignal;
    var stateChanged : QtJSXQt_QMovie_MovieStateSignal;

    // Instance Properties
    var cacheMode : Qt_QMovie_CacheMode;
}
