/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkCookieJar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qnetworkcookie.jsx";

native class QNetworkCookieJar
{
    function constructor ();

    // Methods
    function allCookies () : QNetworkCookie[];
    function setAllCookies (cookieList : QNetworkCookie[]) : void;
}
