/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkRequest class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qobject.jsx";
import "qt/qsslconfiguration.jsx";
import "qt/qurl.jsx";

final native class Qt_QNetworkRequest_LoadControl {}

final native class Qt_QNetworkRequest_CacheLoadControl {}

final native class Qt_QNetworkRequest_Attribute {}

final native class Qt_QNetworkRequest_Priority {}

final native class Qt_QNetworkRequest_KnownHeaders {}

native class QNetworkRequest
{
    function constructor ();
    function constructor (other : QNetworkRequest);
    function constructor (url : QUrl);

    static const Automatic : Qt_QNetworkRequest_LoadControl;
    static const Manual : Qt_QNetworkRequest_LoadControl;
    static function LoadControl(value : Qt_QNetworkRequest_LoadControl) : Qt_QNetworkRequest_LoadControl;

    static const AlwaysNetwork : Qt_QNetworkRequest_CacheLoadControl;
    static const PreferNetwork : Qt_QNetworkRequest_CacheLoadControl;
    static const PreferCache : Qt_QNetworkRequest_CacheLoadControl;
    static const AlwaysCache : Qt_QNetworkRequest_CacheLoadControl;
    static function CacheLoadControl(value : Qt_QNetworkRequest_CacheLoadControl) : Qt_QNetworkRequest_CacheLoadControl;

    static const HttpStatusCodeAttribute : Qt_QNetworkRequest_Attribute;
    static const HttpReasonPhraseAttribute : Qt_QNetworkRequest_Attribute;
    static const RedirectionTargetAttribute : Qt_QNetworkRequest_Attribute;
    static const ConnectionEncryptedAttribute : Qt_QNetworkRequest_Attribute;
    static const CacheLoadControlAttribute : Qt_QNetworkRequest_Attribute;
    static const CacheSaveControlAttribute : Qt_QNetworkRequest_Attribute;
    static const SourceIsFromCacheAttribute : Qt_QNetworkRequest_Attribute;
    static const DoNotBufferUploadDataAttribute : Qt_QNetworkRequest_Attribute;
    static const HttpPipeliningAllowedAttribute : Qt_QNetworkRequest_Attribute;
    static const HttpPipeliningWasUsedAttribute : Qt_QNetworkRequest_Attribute;
    static const CustomVerbAttribute : Qt_QNetworkRequest_Attribute;
    static const CookieLoadControlAttribute : Qt_QNetworkRequest_Attribute;
    static const AuthenticationReuseAttribute : Qt_QNetworkRequest_Attribute;
    static const CookieSaveControlAttribute : Qt_QNetworkRequest_Attribute;
    static const MaximumDownloadBufferSizeAttribute : Qt_QNetworkRequest_Attribute;
    static const DownloadBufferAttribute : Qt_QNetworkRequest_Attribute;
    static const SynchronousRequestAttribute : Qt_QNetworkRequest_Attribute;
    static const BackgroundRequestAttribute : Qt_QNetworkRequest_Attribute;
    static const SpdyAllowedAttribute : Qt_QNetworkRequest_Attribute;
    static const SpdyWasUsedAttribute : Qt_QNetworkRequest_Attribute;
    static const EmitAllUploadProgressSignalsAttribute : Qt_QNetworkRequest_Attribute;
    static const FollowRedirectsAttribute : Qt_QNetworkRequest_Attribute;
    static const Http2AllowedAttribute : Qt_QNetworkRequest_Attribute;
    static const Http2WasUsedAttribute : Qt_QNetworkRequest_Attribute;
    static const OriginalContentLengthAttribute : Qt_QNetworkRequest_Attribute;
    static const RedirectPolicyAttribute : Qt_QNetworkRequest_Attribute;
    static const Http2DirectAttribute : Qt_QNetworkRequest_Attribute;
    static const ResourceTypeAttribute : Qt_QNetworkRequest_Attribute;
    static const AutoDeleteReplyOnFinishAttribute : Qt_QNetworkRequest_Attribute;
    static const User : Qt_QNetworkRequest_Attribute;
    static const UserMax : Qt_QNetworkRequest_Attribute;
    static function Attribute(value : Qt_QNetworkRequest_Attribute) : Qt_QNetworkRequest_Attribute;

    static const HighPriority : Qt_QNetworkRequest_Priority;
    static const NormalPriority : Qt_QNetworkRequest_Priority;
    static const LowPriority : Qt_QNetworkRequest_Priority;
    static function Priority(value : Qt_QNetworkRequest_Priority) : Qt_QNetworkRequest_Priority;

    static const ContentTypeHeader : Qt_QNetworkRequest_KnownHeaders;
    static const ContentLengthHeader : Qt_QNetworkRequest_KnownHeaders;
    static const LocationHeader : Qt_QNetworkRequest_KnownHeaders;
    static const LastModifiedHeader : Qt_QNetworkRequest_KnownHeaders;
    static const CookieHeader : Qt_QNetworkRequest_KnownHeaders;
    static const SetCookieHeader : Qt_QNetworkRequest_KnownHeaders;
    static const ContentDispositionHeader : Qt_QNetworkRequest_KnownHeaders;
    static const UserAgentHeader : Qt_QNetworkRequest_KnownHeaders;
    static const ServerHeader : Qt_QNetworkRequest_KnownHeaders;
    static const IfModifiedSinceHeader : Qt_QNetworkRequest_KnownHeaders;
    static const ETagHeader : Qt_QNetworkRequest_KnownHeaders;
    static const IfMatchHeader : Qt_QNetworkRequest_KnownHeaders;
    static const IfNoneMatchHeader : Qt_QNetworkRequest_KnownHeaders;
    static function KnownHeaders(value : Qt_QNetworkRequest_KnownHeaders) : Qt_QNetworkRequest_KnownHeaders;

    // Methods
    function attribute (code : Qt_QNetworkRequest_Attribute, defaultValue : variant) : variant;
    function hasRawHeader (headerName : QByteArray) : boolean;
    function header (header : Qt_QNetworkRequest_KnownHeaders) : variant;
    function maximumRedirectsAllowed () : int;
    function operator_equal (other : QNetworkRequest) : boolean;
    function originatingObject () : QObject;
    function peerVerifyName () : string;
    function priority () : Qt_QNetworkRequest_Priority;
    function rawHeader (headerName : QByteArray) : QByteArray;
    function rawHeaderList () : QByteArray[];
    function setAttribute (code : Qt_QNetworkRequest_Attribute, value : variant) : void;
    function setHeader (header : Qt_QNetworkRequest_KnownHeaders, value : variant) : void;
    function setMaximumRedirectsAllowed (maximumRedirectsAllowed : int) : void;
    function setOriginatingObject (object : QObject) : void;
    function setPeerVerifyName (peerName : string) : void;
    function setPriority (priority : Qt_QNetworkRequest_Priority) : void;
    function setRawHeader (headerName : QByteArray, value : QByteArray) : void;
    function setSslConfiguration (configuration : QSslConfiguration) : void;
    function setTransferTimeout (timeout : int) : void;
    function setUrl (url : QUrl) : void;
    function sslConfiguration () : QSslConfiguration;
    function swap (other : QNetworkRequest) : void;
    function transferTimeout () : int;
    function url () : QUrl;
}
