/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QNetworkDiskCache class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractnetworkcache.jsx";
import "qt/qnetworkcachemetadata.jsx";

native class QNetworkDiskCache extends QAbstractNetworkCache
{
    function constructor ();

    // Methods
    function cacheDirectory () : string;
    function fileMetaData (fileName : string) : QNetworkCacheMetaData;
    function setCacheDirectory (cacheDir : string) : void;
}
