/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qchildevent.jsx";
import "qt/qevent.jsx";
import "qt/qt.jsx";
import "qt/qtimerevent.jsx";

native class QObject
{
    function constructor (parent : QObject);

    // Methods
    function blockSignals (b : boolean) : boolean;
    function childEvent (event : QChildEvent) : void;
    function children () : QObject[];
    function customEvent (event : QEvent) : void;
    function disposeLater () : void;
    function dumpObjectInfo () : void;
    function dumpObjectTree () : void;
    function dynamicPropertyNames () : QByteArray[];
    function event (event : QEvent) : boolean;
    function eventFilter (watched : QObject, event : QEvent) : boolean;
    function inherits (classname : string) : boolean;
    function installEventFilter (filterObj : QObject) : void;
    function isWidgetType () : boolean;
    function isWindowType () : boolean;
    function killTimer (id : int) : void;
    function parent () : QObject;
    function property (name : string) : variant;
    function removeEventFilter (obj : QObject) : void;
    function senderSignalIndex () : int;
    function setParent (parent : QObject) : void;
    function setProperty (name : string, value : variant) : boolean;
    function signalsBlocked () : boolean;
    function startTimer (interval : int, timerType : Qt_TimerType) : int;
    function timerEvent (event : QTimerEvent) : void;

    // Instance Properties
    var objectName : string;
}
