/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPageSetupDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qprinter.jsx";

native class QPageSetupDialog
{

    // Methods
    function printer () : QPrinter;
}
