/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPainterPath class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QPainterPath_ElementType {}

native class QPainterPath
{
    function constructor (other : QPainterPath);

    static const MoveToElement : Qt_QPainterPath_ElementType;
    static const LineToElement : Qt_QPainterPath_ElementType;
    static const CurveToElement : Qt_QPainterPath_ElementType;
    static const CurveToDataElement : Qt_QPainterPath_ElementType;
    static function ElementType(value : Qt_QPainterPath_ElementType) : Qt_QPainterPath_ElementType;
}
