/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPaintEngineState class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qfont.jsx";
import "qt/qmatrix.jsx";
import "qt/qpaintengine.jsx";
import "qt/qpainter.jsx";
import "qt/qpainterpath.jsx";
import "qt/qpen.jsx";
import "qt/qregion.jsx";
import "qt/qtransform.jsx";

native class QPaintEngineState
{
    function constructor ();

    // Methods
    function backgroundBrush () : QBrush;
    function brush () : QBrush;
    function clipPath () : QPainterPath;
    function clipRegion () : QRegion;
    function compositionMode () : Qt_QPainter_CompositionMode;
    function font () : QFont;
    function matrix () : QMatrix;
    function painter () : QPainter;
    function pen () : QPen;
    function renderHints () : Qt_QPainter_RenderHints;
    function state () : Qt_QPaintEngine_DirtyFlags;
    function transform () : QTransform;
}
