/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPainterPathStroker class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpainterpath.jsx";
import "qt/qpen.jsx";

native class QPainterPathStroker
{
    function constructor ();
    function constructor (pen : QPen);

    // Methods
    function createStroke (path : QPainterPath) : QPainterPath;
}
