/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPaintEngine class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpaintenginestate.jsx";
import "qt/qpainter.jsx";
import "qt/qpainterpath.jsx";
import "qt/qregion.jsx";

final native class Qt_QPaintEngine_DirtyFlag {}

final native class Qt_QPaintEngine_DirtyFlags {}

final native class Qt_QPaintEngine_PaintEngineFeature {}

final native class Qt_QPaintEngine_PaintEngineFeatures {}

final native class Qt_QPaintEngine_PolygonDrawMode {}

final native class Qt_QPaintEngine_Type {}

native class QPaintEngine
{
    function constructor (features : Qt_QPaintEngine_PaintEngineFeatures);

    static const DirtyPen : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBrush : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBrushOrigin : Qt_QPaintEngine_DirtyFlag;
    static const DirtyFont : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBackground : Qt_QPaintEngine_DirtyFlag;
    static const DirtyBackgroundMode : Qt_QPaintEngine_DirtyFlag;
    static const DirtyTransform : Qt_QPaintEngine_DirtyFlag;
    static const DirtyClipRegion : Qt_QPaintEngine_DirtyFlag;
    static const DirtyClipPath : Qt_QPaintEngine_DirtyFlag;
    static const DirtyHints : Qt_QPaintEngine_DirtyFlag;
    static const DirtyCompositionMode : Qt_QPaintEngine_DirtyFlag;
    static const DirtyClipEnabled : Qt_QPaintEngine_DirtyFlag;
    static const DirtyOpacity : Qt_QPaintEngine_DirtyFlag;
    static const AllDirty : Qt_QPaintEngine_DirtyFlag;
    static function DirtyFlag(value : Qt_QPaintEngine_DirtyFlag) : Qt_QPaintEngine_DirtyFlag;
    static function DirtyFlags(...value : Qt_QPaintEngine_DirtyFlag) : Qt_QPaintEngine_DirtyFlags;

    static const AllFeatures : Qt_QPaintEngine_PaintEngineFeature;
    static const PrimitiveTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const PatternTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const PixmapTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const PatternBrush : Qt_QPaintEngine_PaintEngineFeature;
    static const LinearGradientFill : Qt_QPaintEngine_PaintEngineFeature;
    static const RadialGradientFill : Qt_QPaintEngine_PaintEngineFeature;
    static const ConicalGradientFill : Qt_QPaintEngine_PaintEngineFeature;
    static const AlphaBlend : Qt_QPaintEngine_PaintEngineFeature;
    static const PorterDuff : Qt_QPaintEngine_PaintEngineFeature;
    static const PainterPaths : Qt_QPaintEngine_PaintEngineFeature;
    static const Antialiasing : Qt_QPaintEngine_PaintEngineFeature;
    static const BrushStroke : Qt_QPaintEngine_PaintEngineFeature;
    static const ConstantOpacity : Qt_QPaintEngine_PaintEngineFeature;
    static const MaskedBrush : Qt_QPaintEngine_PaintEngineFeature;
    static const PerspectiveTransform : Qt_QPaintEngine_PaintEngineFeature;
    static const BlendModes : Qt_QPaintEngine_PaintEngineFeature;
    static const ObjectBoundingModeGradients : Qt_QPaintEngine_PaintEngineFeature;
    static const RasterOpModes : Qt_QPaintEngine_PaintEngineFeature;
    static const PaintOutsidePaintEvent : Qt_QPaintEngine_PaintEngineFeature;
    static function PaintEngineFeature(value : Qt_QPaintEngine_PaintEngineFeature) : Qt_QPaintEngine_PaintEngineFeature;
    static function PaintEngineFeatures(...value : Qt_QPaintEngine_PaintEngineFeature) : Qt_QPaintEngine_PaintEngineFeatures;

    static const OddEvenMode : Qt_QPaintEngine_PolygonDrawMode;
    static const WindingMode : Qt_QPaintEngine_PolygonDrawMode;
    static const ConvexMode : Qt_QPaintEngine_PolygonDrawMode;
    static const PolylineMode : Qt_QPaintEngine_PolygonDrawMode;
    static function PolygonDrawMode(value : Qt_QPaintEngine_PolygonDrawMode) : Qt_QPaintEngine_PolygonDrawMode;

    static const X11 : Qt_QPaintEngine_Type;
    static const Windows : Qt_QPaintEngine_Type;
    static const QuickDraw : Qt_QPaintEngine_Type;
    static const CoreGraphics : Qt_QPaintEngine_Type;
    static const MacPrinter : Qt_QPaintEngine_Type;
    static const QWindowSystem : Qt_QPaintEngine_Type;
    static const PostScript : Qt_QPaintEngine_Type;
    static const OpenGL : Qt_QPaintEngine_Type;
    static const Picture : Qt_QPaintEngine_Type;
    static const SVG : Qt_QPaintEngine_Type;
    static const Raster : Qt_QPaintEngine_Type;
    static const Direct3D : Qt_QPaintEngine_Type;
    static const Pdf : Qt_QPaintEngine_Type;
    static const OpenVG : Qt_QPaintEngine_Type;
    static const OpenGL2 : Qt_QPaintEngine_Type;
    static const PaintBuffer : Qt_QPaintEngine_Type;
    static const Blitter : Qt_QPaintEngine_Type;
    static const Direct2D : Qt_QPaintEngine_Type;
    static const User : Qt_QPaintEngine_Type;
    static const MaxUser : Qt_QPaintEngine_Type;
    static function Type(value : Qt_QPaintEngine_Type) : Qt_QPaintEngine_Type;

    // Methods
    function clearDirty (df : Qt_QPaintEngine_DirtyFlags) : void;
    function drawPath (path : QPainterPath) : void;
    function painter () : QPainter;
    function setDirty (df : Qt_QPaintEngine_DirtyFlags) : void;
    function setSystemClip (baseClip : QRegion) : void;
    function syncState () : void;
    function systemClip () : QRegion;
    function type () : Qt_QPaintEngine_Type;
    function updateState (state : QPaintEngineState) : void;
}
