/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPaintEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qregion.jsx";

native class QPaintEvent
{
    function constructor (paintRegion : QRegion);

    // Methods
    function region () : QRegion;
}
