/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPictureIO class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpicture.jsx";

native class QPictureIO
{
    function constructor ();

    // Methods
    function description () : string;
    function fileName () : string;
    function picture () : QPicture;
    function setDescription (arg__1 : string) : void;
    function setFileName (arg__1 : string) : void;
    function setPicture (arg__1 : QPicture) : void;
}
