/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPlainTextEdit class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractscrollarea.jsx";
import "qt/qmenu.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QPlainTextEdit_LineWrapMode {}

native class QPlainTextEdit extends QAbstractScrollArea
{
    function constructor (parent : QWidget);
    function constructor (text : string, parent : QWidget);

    static const NoWrap : Qt_QPlainTextEdit_LineWrapMode;
    static const WidgetWidth : Qt_QPlainTextEdit_LineWrapMode;
    static function LineWrapMode(value : Qt_QPlainTextEdit_LineWrapMode) : Qt_QPlainTextEdit_LineWrapMode;

    // Methods
    function createStandardContextMenu () : QMenu;
    function ensureCursorVisible () : void;
    function placeholderText () : string;
    function setPlaceholderText (placeholderText : string) : void;
    function toPlainText () : string;

    // Slots
    function appendHtml (html : string) : void;
    function appendPlainText (text : string) : void;
    function centerCursor () : void;
    function clear () : void;
    function copy () : void;
    function cut () : void;
    function insertPlainText (text : string) : void;
    function paste () : void;
    function redo () : void;
    function selectAll () : void;
    function setPlainText (text : string) : void;
    function undo () : void;

    // Signals
    var cursorPositionChanged : QtJSXSignal;
    var selectionChanged : QtJSXSignal;
    var textChanged : QtJSXSignal;

    // Instance Properties
    var documentTitle : string;
    var lineWrapMode : Qt_QPlainTextEdit_LineWrapMode;
}
