/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPlainTextDocumentLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QPlainTextDocumentLayout
{

    // Methods
    function requestUpdate () : void;
}
