/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPrinter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qprintengine.jsx";

final native class Qt_QPrinter_PrinterMode {}

final native class Qt_QPrinter_PaperSource {}

final native class Qt_QPrinter_Orientation {}

final native class Qt_QPrinter_OutputFormat {}

final native class Qt_QPrinter_PageOrder {}

final native class Qt_QPrinter_PrinterState {}

final native class Qt_QPrinter_PrintRange {}

final native class Qt_QPrinter_ColorMode {}

final native class Qt_QPrinter_Unit {}

final native class Qt_QPrinter_DuplexMode {}

native class QPrinter
{
    function constructor (mode : Qt_QPrinter_PrinterMode);

    static const ScreenResolution : Qt_QPrinter_PrinterMode;
    static const PrinterResolution : Qt_QPrinter_PrinterMode;
    static const HighResolution : Qt_QPrinter_PrinterMode;
    static function PrinterMode(value : Qt_QPrinter_PrinterMode) : Qt_QPrinter_PrinterMode;

    static const OnlyOne : Qt_QPrinter_PaperSource;
    static const Lower : Qt_QPrinter_PaperSource;
    static const Middle : Qt_QPrinter_PaperSource;
    static const Manual : Qt_QPrinter_PaperSource;
    static const Envelope : Qt_QPrinter_PaperSource;
    static const EnvelopeManual : Qt_QPrinter_PaperSource;
    static const Auto : Qt_QPrinter_PaperSource;
    static const Tractor : Qt_QPrinter_PaperSource;
    static const SmallFormat : Qt_QPrinter_PaperSource;
    static const LargeFormat : Qt_QPrinter_PaperSource;
    static const LargeCapacity : Qt_QPrinter_PaperSource;
    static const Cassette : Qt_QPrinter_PaperSource;
    static const FormSource : Qt_QPrinter_PaperSource;
    static const MaxPageSource : Qt_QPrinter_PaperSource;
    static const CustomSource : Qt_QPrinter_PaperSource;
    static function PaperSource(value : Qt_QPrinter_PaperSource) : Qt_QPrinter_PaperSource;

    static const Portrait : Qt_QPrinter_Orientation;
    static const Landscape : Qt_QPrinter_Orientation;
    static function Orientation(value : Qt_QPrinter_Orientation) : Qt_QPrinter_Orientation;

    static const NativeFormat : Qt_QPrinter_OutputFormat;
    static const PdfFormat : Qt_QPrinter_OutputFormat;
    static function OutputFormat(value : Qt_QPrinter_OutputFormat) : Qt_QPrinter_OutputFormat;

    static const FirstPageFirst : Qt_QPrinter_PageOrder;
    static const LastPageFirst : Qt_QPrinter_PageOrder;
    static function PageOrder(value : Qt_QPrinter_PageOrder) : Qt_QPrinter_PageOrder;

    static const Idle : Qt_QPrinter_PrinterState;
    static const Active : Qt_QPrinter_PrinterState;
    static const Aborted : Qt_QPrinter_PrinterState;
    static const Error : Qt_QPrinter_PrinterState;
    static function PrinterState(value : Qt_QPrinter_PrinterState) : Qt_QPrinter_PrinterState;

    static const AllPages : Qt_QPrinter_PrintRange;
    static const Selection : Qt_QPrinter_PrintRange;
    static const PageRange : Qt_QPrinter_PrintRange;
    static const CurrentPage : Qt_QPrinter_PrintRange;
    static function PrintRange(value : Qt_QPrinter_PrintRange) : Qt_QPrinter_PrintRange;

    static const GrayScale : Qt_QPrinter_ColorMode;
    static const Color : Qt_QPrinter_ColorMode;
    static function ColorMode(value : Qt_QPrinter_ColorMode) : Qt_QPrinter_ColorMode;

    static const Millimeter : Qt_QPrinter_Unit;
    static const Point : Qt_QPrinter_Unit;
    static const Inch : Qt_QPrinter_Unit;
    static const Pica : Qt_QPrinter_Unit;
    static const Didot : Qt_QPrinter_Unit;
    static const Cicero : Qt_QPrinter_Unit;
    static const DevicePixel : Qt_QPrinter_Unit;
    static function Unit(value : Qt_QPrinter_Unit) : Qt_QPrinter_Unit;

    static const DuplexNone : Qt_QPrinter_DuplexMode;
    static const DuplexAuto : Qt_QPrinter_DuplexMode;
    static const DuplexLongSide : Qt_QPrinter_DuplexMode;
    static const DuplexShortSide : Qt_QPrinter_DuplexMode;
    static function DuplexMode(value : Qt_QPrinter_DuplexMode) : Qt_QPrinter_DuplexMode;

    // Methods
    function colorMode () : Qt_QPrinter_ColorMode;
    function creator () : string;
    function docName () : string;
    function duplex () : Qt_QPrinter_DuplexMode;
    function orientation () : Qt_QPrinter_Orientation;
    function outputFileName () : string;
    function outputFormat () : Qt_QPrinter_OutputFormat;
    function pageOrder () : Qt_QPrinter_PageOrder;
    function pageSize () : Qt_QPrinter_PageSize;
    function paperName () : string;
    function paperSource () : Qt_QPrinter_PaperSource;
    function printEngine () : QPrintEngine;
    function printProgram () : string;
    function printRange () : Qt_QPrinter_PrintRange;
    function printerName () : string;
    function printerState () : Qt_QPrinter_PrinterState;
    function setColorMode (arg__1 : Qt_QPrinter_ColorMode) : void;
    function setCreator (arg__1 : string) : void;
    function setDocName (arg__1 : string) : void;
    function setDuplex (duplex : Qt_QPrinter_DuplexMode) : void;
    function setOrientation (arg__1 : Qt_QPrinter_Orientation) : void;
    function setOutputFileName (arg__1 : string) : void;
    function setOutputFormat (format : Qt_QPrinter_OutputFormat) : void;
    function setPageOrder (arg__1 : Qt_QPrinter_PageOrder) : void;
    function setPaperName (paperName : string) : void;
    function setPaperSource (arg__1 : Qt_QPrinter_PaperSource) : void;
    function setPrintProgram (arg__1 : string) : void;
    function setPrintRange (range : Qt_QPrinter_PrintRange) : void;
    function setPrinterName (arg__1 : string) : void;
}
