/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPrintDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractprintdialog.jsx";
import "qt/qprinter.jsx";
import "qt/_signals.jsx";

native class QPrintDialog extends QAbstractPrintDialog
{
    function constructor ();

    // Signals
}
