/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QPrintPreviewDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qprinter.jsx";
import "qt/_signals.jsx";

native class QPrintPreviewDialog
{

    // Methods
    function printer () : QPrinter;

    // Signals
    var paintRequested : QtJSXQPrinterSignal;
}
