/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QProgressBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptionprogressbar.jsx";
import "qt/qwidget.jsx";

final native class Qt_QProgressBar_Direction {}

native class QProgressBar extends QWidget
{
    function constructor (parent : QWidget);

    static const TopToBottom : Qt_QProgressBar_Direction;
    static const BottomToTop : Qt_QProgressBar_Direction;
    static function Direction(value : Qt_QProgressBar_Direction) : Qt_QProgressBar_Direction;

    // Methods
    function initStyleOption (option : QStyleOptionProgressBar) : void;
    function resetFormat () : void;

    // Slots
    function reset () : void;

    // Instance Properties
    var text : string;
    var textDirection : Qt_QProgressBar_Direction;
    var format : string;
}
