/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QProgressDialog class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qdialog.jsx";
import "qt/qlabel.jsx";
import "qt/qprogressbar.jsx";
import "qt/qpushbutton.jsx";
import "qt/_signals.jsx";

native class QProgressDialog extends QDialog
{
    function constructor ();

    // Methods
    function setBar (bar : QProgressBar) : void;
    function setCancelButton (button : QPushButton) : void;
    function setLabel (label : QLabel) : void;

    // Slots
    function cancel () : void;
    function forceShow () : void;
    function reset () : void;
    function setCancelButtonText (text : string) : void;

    // Signals
    var canceled : QtJSXSignal;

    // Instance Properties
    var labelText : string;
}
