/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QQuaternion class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmatrix3x3.jsx";
import "qt/qvector3d.jsx";
import "qt/qvector4d.jsx";

native class QQuaternion
{
    function constructor ();
    function constructor (vector : QVector4D);

    // Static Members
    static function fromAxes (xAxis : QVector3D, yAxis : QVector3D, zAxis : QVector3D) : QQuaternion;
    static function fromDirection (direction : QVector3D, up : QVector3D) : QQuaternion;
    static function fromEulerAngles (eulerAngles : QVector3D) : QQuaternion;
    static function fromRotationMatrix (rot3x3 : QMatrix3x3) : QQuaternion;
    static function rotationTo (from : QVector3D, to : QVector3D) : QQuaternion;

    // Methods
    function conjugate () : QQuaternion;
    function conjugated () : QQuaternion;
    function getAxes (xAxis : QVector3D, yAxis : QVector3D, zAxis : QVector3D) : void;
    function inverted () : QQuaternion;
    function normalize () : void;
    function normalized () : QQuaternion;
    function operator_add_assign (quaternion : QQuaternion) : QQuaternion;
    function operator_multiply_assign (quaternion : QQuaternion) : QQuaternion;
    function operator_subtract_assign (quaternion : QQuaternion) : QQuaternion;
    function rotatedVector (vector : QVector3D) : QVector3D;
    function setVector (vector : QVector3D) : void;
    function toEulerAngles () : QVector3D;
    function toRotationMatrix () : QMatrix3x3;
    function toVector4D () : QVector4D;
    function vector () : QVector3D;
}
