/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QRadialGradient class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgradient.jsx";

native class QRadialGradient extends QGradient
{
    function constructor ();
}
