/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QRegExpValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qvalidator.jsx";

native class QRegExpValidator extends QValidator
{
    function constructor ();
}
