/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QScrollBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractslider.jsx";
import "qt/qstyleoptionslider.jsx";
import "qt/qwidget.jsx";

native class QScrollBar extends QAbstractSlider
{
    function constructor (parent : QWidget);

    // Methods
    function initStyleOption (option : QStyleOptionSlider) : void;
}
