/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QScrollArea class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractscrollarea.jsx";
import "qt/qwidget.jsx";

native class QScrollArea extends QAbstractScrollArea
{
    function constructor (parent : QWidget);

    // Methods
    function setWidget (widget : QWidget) : void;
    function takeWidget () : QWidget;
    function widget () : QWidget;
}
