/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSessionManager class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QSessionManager
{

    // Methods
    function cancel () : void;
    function discardCommand () : string[];
    function release () : void;
    function requestPhase2 () : void;
    function restartCommand () : string[];
    function sessionId () : string;
    function sessionKey () : string;
    function setDiscardCommand (arg__1 : string[]) : void;
    function setManagerProperty (name : string, value : string) : void;
    function setManagerProperty (name : string, value : string[]) : void;
    function setRestartCommand (arg__1 : string[]) : void;
}
