/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSettings class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qtextcodec.jsx";

final native class Qt_QSettings_Status {}

native class QSettings
{
    function constructor (parent : QObject);
    function constructor (organization : string, application : string, parent : QObject);

    // Static Members

    static const NoError : Qt_QSettings_Status;
    static const AccessError : Qt_QSettings_Status;
    static const FormatError : Qt_QSettings_Status;
    static function Status(value : Qt_QSettings_Status) : Qt_QSettings_Status;

    // Methods
    function allKeys () : string[];
    function applicationName () : string;
    function beginGroup (prefix : string) : void;
    function beginReadArray (prefix : string) : int;
    function beginWriteArray (prefix : string, size : int) : void;
    function childGroups () : string[];
    function childKeys () : string[];
    function clear () : void;
    function contains (key : string) : boolean;
    function endArray () : void;
    function endGroup () : void;
    function fallbacksEnabled () : boolean;
    function fileName () : string;
    function group () : string;
    function iniCodec () : QTextCodec;
    function isAtomicSyncRequired () : boolean;
    function isWritable () : boolean;
    function organizationName () : string;
    function remove (key : string) : void;
    function setArrayIndex (i : int) : void;
    function setAtomicSyncRequired (enable : boolean) : void;
    function setFallbacksEnabled (b : boolean) : void;
    function setIniCodec (codec : QTextCodec) : void;
    function setIniCodec (codecName : string) : void;
    function setValue (key : string, value : variant) : void;
    function sync () : void;
    function value (key : string, defaultValue : variant) : variant;
}
