/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QShortcutEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qkeysequence.jsx";

native class QShortcutEvent
{

    // Methods
    function key () : QKeySequence;
}
