/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QShortcut class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QShortcut
{
    function constructor (parent : QWidget);

    // Methods
    function parentWidget () : QWidget;

    // Signals
    var activated : QtJSXSignal;
    var activatedAmbiguously : QtJSXSignal;

    // Instance Properties
    var whatsThis : string;
}
