/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSizeGrip class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";

native class QSizeGrip extends QWidget
{
    function constructor (parent : QWidget);
}
