/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSizeGrip class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qevent.jsx";
import "qt/qobject.jsx";
import "qt/qwidget.jsx";

native class QSizeGrip extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function eventFilter (arg__1 : QObject, arg__2 : QEvent) : boolean;
    function setVisible (arg__1 : boolean) : void;
}
