/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSocketNotifier class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qintptr.jsx";
import "qt/qobject.jsx";

final native class Qt_QSocketNotifier_Type {}

native class QSocketNotifier extends QObject
{
    function constructor (socket : qintptr, arg__2 : Qt_QSocketNotifier_Type, parent : QObject);

    static const Read : Qt_QSocketNotifier_Type;
    static const Write : Qt_QSocketNotifier_Type;
    static const Exception : Qt_QSocketNotifier_Type;
    static function Type(value : Qt_QSocketNotifier_Type) : Qt_QSocketNotifier_Type;

    // Methods
    function isEnabled () : boolean;
    function setEnabled (arg__1 : boolean) : void;
    function socket () : qintptr;
    function type () : Qt_QSocketNotifier_Type;
}
