/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSourceLocation class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QSourceLocation
{
    function constructor ();
    function constructor (other : QSourceLocation);
}
