/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSoundEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/_signals.jsx";

native class QSoundEffect extends QObject
{
    function constructor ();

    // Slots
    function play () : void;
    function stop () : void;

    // Signals
    var categoryChanged : QtJSXSignal;
    var loadedChanged : QtJSXSignal;
    var loopCountChanged : QtJSXSignal;
    var loopsRemainingChanged : QtJSXSignal;
    var mutedChanged : QtJSXSignal;
    var playingChanged : QtJSXSignal;
    var sourceChanged : QtJSXSignal;
    var statusChanged : QtJSXSignal;
    var volumeChanged : QtJSXSignal;
}
