/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSound class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QSound_Loop {}

native class QSound
{

    // Static Members
    static function play (filename : string) : void;

    static const Infinite : Qt_QSound_Loop;
    static function Loop(value : Qt_QSound_Loop) : Qt_QSound_Loop;

    // Methods
    function fileName () : string;

    // Slots
    function play () : void;
    function stop () : void;
}
