/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSoundEffect class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/_signals.jsx";

final native class Qt_QSoundEffect_Status {}

final native class Qt_QSoundEffect_Loop {}

native class QSoundEffect
{
    function constructor ();

    // Static Members
    static function supportedMimeTypes () : string[];

    static const Null : Qt_QSoundEffect_Status;
    static const Loading : Qt_QSoundEffect_Status;
    static const Ready : Qt_QSoundEffect_Status;
    static const Error : Qt_QSoundEffect_Status;
    static function Status(value : Qt_QSoundEffect_Status) : Qt_QSoundEffect_Status;

    static const Infinite : Qt_QSoundEffect_Loop;
    static function Loop(value : Qt_QSoundEffect_Loop) : Qt_QSoundEffect_Loop;

    // Methods
    function category () : string;
    function setCategory (category : string) : void;
    function status () : Qt_QSoundEffect_Status;

    // Slots
    function play () : void;
    function stop () : void;

    // Signals
    var categoryChanged : QtJSXSignal;
    var loadedChanged : QtJSXSignal;
    var loopCountChanged : QtJSXSignal;
    var loopsRemainingChanged : QtJSXSignal;
    var mutedChanged : QtJSXSignal;
    var playingChanged : QtJSXSignal;
    var sourceChanged : QtJSXSignal;
    var statusChanged : QtJSXSignal;
    var volumeChanged : QtJSXSignal;
}
