/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSpacerItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlayoutitem.jsx";
import "qt/qsizepolicy.jsx";

native class QSpacerItem extends QLayoutItem
{

    // Methods
    function sizePolicy () : QSizePolicy;
}
