/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSpinBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractspinbox.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QSpinBox extends QAbstractSpinBox
{
    function constructor (parent : QWidget);

    // Signals
    var textChanged : QtJSXQStringSignal;
    var valueChanged : QtJSXQStringSignal;

    // Instance Properties
    var suffix : string;
    var prefix : string;
    var cleanText : string;
}
