/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSplitterHandle class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsplitter.jsx";
import "qt/qwidget.jsx";

native class QSplitterHandle extends QWidget
{
    function constructor ();

    // Methods
    function splitter () : QSplitter;
}
