/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSplashScreen class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QSplashScreen extends QWidget
{
    function constructor ();

    // Methods
    function finish (w : QWidget) : void;
    function message () : string;

    // Slots
    function clearMessage () : void;

    // Signals
    var messageChanged : QtJSXQStringSignal;
}
