/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSplitter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qsplitterhandle.jsx";
import "qt/qwidget.jsx";

native class QSplitter extends QFrame
{
    function constructor (parent : QWidget);

    // Methods
    function addWidget (widget : QWidget) : void;
    function createHandle () : QSplitterHandle;
    function refresh () : void;
}
