/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlQueryModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsqldatabase.jsx";
import "qt/qsqlerror.jsx";
import "qt/qsqlquery.jsx";
import "qt/qsqlrecord.jsx";

native class QSqlQueryModel
{

    // Methods
    function beginResetModel () : void;
    function clear () : void;
    function endInsertColumns () : void;
    function endInsertRows () : void;
    function endRemoveColumns () : void;
    function endRemoveRows () : void;
    function endResetModel () : void;
    function lastError () : QSqlError;
    function query () : QSqlQuery;
    function queryChange () : void;
    function record () : QSqlRecord;
    function setLastError (error : QSqlError) : void;
    function setQuery (query : QSqlQuery) : void;
    function setQuery (query : string, db : QSqlDatabase) : void;
}
