/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlResult class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsql.jsx";
import "qt/qsqldriver.jsx";
import "qt/qsqlerror.jsx";
import "qt/qsqlrecord.jsx";

native class QSqlResult
{

    // Methods
    function addBindValue (val : variant, type : Qt_QSql_ParamType) : void;
    function bindValue (placeholder : string, val : variant, type : Qt_QSql_ParamType) : void;
    function bindValueType (placeholder : string) : Qt_QSql_ParamType;
    function boundValue (placeholder : string) : variant;
    function boundValues () : variant[];
    function clear () : void;
    function detachFromResultSet () : void;
    function driver () : QSqlDriver;
    function executedQuery () : string;
    function handle () : variant;
    function lastError () : QSqlError;
    function lastInsertId () : variant;
    function lastQuery () : string;
    function numericalPrecisionPolicy () : Qt_QSql_NumericalPrecisionPolicy;
    function record () : QSqlRecord;
    function resetBindCount () : void;
    function setLastError (e : QSqlError) : void;
    function setNumericalPrecisionPolicy (policy : Qt_QSql_NumericalPrecisionPolicy) : void;
    function setQuery (query : string) : void;
}
