/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlRecord class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsqlfield.jsx";

native class QSqlRecord
{
    function constructor ();
    function constructor (other : QSqlRecord);

    // Methods
    function append (field : QSqlField) : void;
    function clear () : void;
    function clearValues () : void;
    function field (name : string) : QSqlField;
    function keyValues (keyFields : QSqlRecord) : QSqlRecord;
    function setNull (name : string) : void;
    function setValue (name : string, val : variant) : void;
    function value (name : string) : variant;
}
