/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlRelationalTableModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsqltablemodel.jsx";

native class QSqlRelationalTableModel extends QSqlTableModel
{
}
