/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlTableModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsqldatabase.jsx";
import "qt/qsqlindex.jsx";
import "qt/qsqlquerymodel.jsx";
import "qt/qsqlrecord.jsx";
import "qt/_signals.jsx";

final native class Qt_QSqlTableModel_EditStrategy {}

native class QSqlTableModel extends QSqlQueryModel
{

    static const OnFieldChange : Qt_QSqlTableModel_EditStrategy;
    static const OnRowChange : Qt_QSqlTableModel_EditStrategy;
    static const OnManualSubmit : Qt_QSqlTableModel_EditStrategy;
    static function EditStrategy(value : Qt_QSqlTableModel_EditStrategy) : Qt_QSqlTableModel_EditStrategy;

    // Methods
    function database () : QSqlDatabase;
    function editStrategy () : Qt_QSqlTableModel_EditStrategy;
    function filter () : string;
    function orderByClause () : string;
    function primaryKey () : QSqlIndex;
    function selectStatement () : string;
    function setEditStrategy (strategy : Qt_QSqlTableModel_EditStrategy) : void;
    function setFilter (filter : string) : void;
    function setPrimaryKey (key : QSqlIndex) : void;
    function setTable (tableName : string) : void;
    function tableName () : string;

    // Slots
    function revertAll () : void;

    // Signals
    var beforeInsert : QtJSXQSqlRecordSignal;
}
