/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlQuery class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsql.jsx";
import "qt/qsqldatabase.jsx";
import "qt/qsqldriver.jsx";
import "qt/qsqlerror.jsx";
import "qt/qsqlrecord.jsx";
import "qt/qsqlresult.jsx";

final native class Qt_QSqlQuery_BatchExecutionMode {}

native class QSqlQuery
{
    function constructor (db : QSqlDatabase);
    function constructor (r : QSqlResult);
    function constructor (other : QSqlQuery);
    function constructor (query : string, db : QSqlDatabase);

    static const ValuesAsRows : Qt_QSqlQuery_BatchExecutionMode;
    static const ValuesAsColumns : Qt_QSqlQuery_BatchExecutionMode;
    static function BatchExecutionMode(value : Qt_QSqlQuery_BatchExecutionMode) : Qt_QSqlQuery_BatchExecutionMode;

    // Methods
    function addBindValue (val : variant, type : Qt_QSql_ParamType) : void;
    function bindValue (placeholder : string, val : variant, type : Qt_QSql_ParamType) : void;
    function boundValue (placeholder : string) : variant;
    function clear () : void;
    function driver () : QSqlDriver;
    function executedQuery () : string;
    function finish () : void;
    function lastError () : QSqlError;
    function lastInsertId () : variant;
    function lastQuery () : string;
    function numericalPrecisionPolicy () : Qt_QSql_NumericalPrecisionPolicy;
    function record () : QSqlRecord;
    function result () : QSqlResult;
    function setNumericalPrecisionPolicy (precisionPolicy : Qt_QSql_NumericalPrecisionPolicy) : void;
    function value (name : string) : variant;
}
