/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlIndex class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsqlrecord.jsx";

native class QSqlIndex extends QSqlRecord
{
    function constructor (other : QSqlIndex);
    function constructor (cursorName : string, name : string);

    // Methods
    function cursorName () : string;
    function name () : string;
    function setCursorName (cursorName : string) : void;
    function setName (name : string) : void;
}
