/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSqlField class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QSqlField_RequiredStatus {}

native class QSqlField
{
    function constructor (other : QSqlField);

    static const Unknown : Qt_QSqlField_RequiredStatus;
    static const Optional : Qt_QSqlField_RequiredStatus;
    static const Required : Qt_QSqlField_RequiredStatus;
    static function RequiredStatus(value : Qt_QSqlField_RequiredStatus) : Qt_QSqlField_RequiredStatus;

    // Methods
    function clear () : void;
    function defaultValue () : variant;
    function name () : string;
    function requiredStatus () : Qt_QSqlField_RequiredStatus;
    function setDefaultValue (value : variant) : void;
    function setName (name : string) : void;
    function setRequiredStatus (status : Qt_QSqlField_RequiredStatus) : void;
    function setTableName (tableName : string) : void;
    function setValue (value : variant) : void;
    function tableName () : string;
    function value () : variant;
}
