/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSslConfiguration class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qssl.jsx";
import "qt/qsslcertificate.jsx";
import "qt/qsslcipher.jsx";
import "qt/qsslkey.jsx";
import "qt/qsslsocket.jsx";

native class QSslConfiguration
{
    function constructor ();
    function constructor (other : QSslConfiguration);

    // Static Members
    static function defaultConfiguration () : QSslConfiguration;
    static function defaultDtlsConfiguration () : QSslConfiguration;
    static function setDefaultConfiguration (configuration : QSslConfiguration) : void;
    static function setDefaultDtlsConfiguration (configuration : QSslConfiguration) : void;
    static function supportedCiphers () : QSslCipher[];
    static function systemCaCertificates () : QSslCertificate[];

    // Methods
    function addCaCertificate (certificate : QSslCertificate) : void;
    function addCaCertificates (certificates : QSslCertificate[]) : void;
    function allowedNextProtocols () : QByteArray[];
    function caCertificates () : QSslCertificate[];
    function ciphers () : QSslCipher[];
    function dtlsCookieVerificationEnabled () : boolean;
    function ephemeralServerKey () : QSslKey;
    function isNull () : boolean;
    function localCertificate () : QSslCertificate;
    function localCertificateChain () : QSslCertificate[];
    function nextNegotiatedProtocol () : QByteArray;
    function ocspStaplingEnabled () : boolean;
    function operator_assign (other : QSslConfiguration) : QSslConfiguration;
    function operator_equal (other : QSslConfiguration) : boolean;
    function peerCertificate () : QSslCertificate;
    function peerCertificateChain () : QSslCertificate[];
    function peerVerifyDepth () : int;
    function peerVerifyMode () : Qt_QSslSocket_PeerVerifyMode;
    function preSharedKeyIdentityHint () : QByteArray;
    function privateKey () : QSslKey;
    function protocol () : Qt_QSsl_SslProtocol;
    function sessionCipher () : QSslCipher;
    function sessionProtocol () : Qt_QSsl_SslProtocol;
    function sessionTicket () : QByteArray;
    function sessionTicketLifeTimeHint () : int;
    function setAllowedNextProtocols (protocols : QByteArray[]) : void;
    function setBackendConfigurationOption (name : QByteArray, value : variant) : void;
    function setCaCertificates (certificates : QSslCertificate[]) : void;
    function setCiphers (ciphers : QSslCipher[]) : void;
    function setDtlsCookieVerificationEnabled (enable : boolean) : void;
    function setLocalCertificate (certificate : QSslCertificate) : void;
    function setLocalCertificateChain (localChain : QSslCertificate[]) : void;
    function setOcspStaplingEnabled (enable : boolean) : void;
    function setPeerVerifyDepth (depth : int) : void;
    function setPeerVerifyMode (mode : Qt_QSslSocket_PeerVerifyMode) : void;
    function setPreSharedKeyIdentityHint (hint : QByteArray) : void;
    function setPrivateKey (key : QSslKey) : void;
    function setProtocol (protocol : Qt_QSsl_SslProtocol) : void;
    function setSessionTicket (sessionTicket : QByteArray) : void;
    function swap (other : QSslConfiguration) : void;
}
