/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSslSocket class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qssl.jsx";
import "qt/qsslcertificate.jsx";
import "qt/qsslcipher.jsx";
import "qt/qsslconfiguration.jsx";
import "qt/qsslerror.jsx";
import "qt/qsslkey.jsx";
import "qt/qtcpsocket.jsx";
import "qt/_signals.jsx";

final native class Qt_QSslSocket_SslMode {}

final native class Qt_QSslSocket_PeerVerifyMode {}

native class QSslSocket extends QTcpSocket
{
    function constructor ();

    // Static Members
    static function addDefaultCaCertificate (certificate : QSslCertificate) : void;
    static function addDefaultCaCertificates (certificates : QSslCertificate[]) : void;
    static function defaultCaCertificates () : QSslCertificate[];
    static function defaultCiphers () : QSslCipher[];
    static function setDefaultCaCertificates (certificates : QSslCertificate[]) : void;
    static function setDefaultCiphers (ciphers : QSslCipher[]) : void;
    static function sslLibraryBuildVersionString () : string;
    static function sslLibraryVersionString () : string;
    static function supportedCiphers () : QSslCipher[];
    static function systemCaCertificates () : QSslCertificate[];

    static const UnencryptedMode : Qt_QSslSocket_SslMode;
    static const SslClientMode : Qt_QSslSocket_SslMode;
    static const SslServerMode : Qt_QSslSocket_SslMode;
    static function SslMode(value : Qt_QSslSocket_SslMode) : Qt_QSslSocket_SslMode;

    static const VerifyNone : Qt_QSslSocket_PeerVerifyMode;
    static const QueryPeer : Qt_QSslSocket_PeerVerifyMode;
    static const VerifyPeer : Qt_QSslSocket_PeerVerifyMode;
    static const AutoVerifyPeer : Qt_QSslSocket_PeerVerifyMode;
    static function PeerVerifyMode(value : Qt_QSslSocket_PeerVerifyMode) : Qt_QSslSocket_PeerVerifyMode;

    // Methods
    function addCaCertificate (certificate : QSslCertificate) : void;
    function addCaCertificates (certificates : QSslCertificate[]) : void;
    function caCertificates () : QSslCertificate[];
    function ciphers () : QSslCipher[];
    function ignoreSslErrors (errors : QSslError[]) : void;
    function localCertificate () : QSslCertificate;
    function localCertificateChain () : QSslCertificate[];
    function mode () : Qt_QSslSocket_SslMode;
    function peerCertificate () : QSslCertificate;
    function peerCertificateChain () : QSslCertificate[];
    function peerVerifyMode () : Qt_QSslSocket_PeerVerifyMode;
    function peerVerifyName () : string;
    function privateKey () : QSslKey;
    function protocol () : Qt_QSsl_SslProtocol;
    function sessionCipher () : QSslCipher;
    function sessionProtocol () : Qt_QSsl_SslProtocol;
    function setCaCertificates (certificates : QSslCertificate[]) : void;
    function setCiphers (ciphers : QSslCipher[]) : void;
    function setCiphers (ciphers : string) : void;
    function setLocalCertificate (certificate : QSslCertificate) : void;
    function setLocalCertificate (fileName : string, format : Qt_QSsl_EncodingFormat) : void;
    function setLocalCertificateChain (localChain : QSslCertificate[]) : void;
    function setPeerVerifyMode (mode : Qt_QSslSocket_PeerVerifyMode) : void;
    function setPeerVerifyName (hostName : string) : void;
    function setPrivateKey (key : QSslKey) : void;
    function setProtocol (protocol : Qt_QSsl_SslProtocol) : void;
    function setSslConfiguration (config : QSslConfiguration) : void;
    function sslConfiguration () : QSslConfiguration;
    function sslHandshakeErrors () : QSslError[];

    // Slots
    function ignoreSslErrors () : void;
    function startClientEncryption () : void;
    function startServerEncryption () : void;

    // Signals
    var encrypted : QtJSXSignal;
    var modeChanged : QtJSXQt_QSslSocket_SslModeSignal;
    var newSessionTicketReceived : QtJSXSignal;
    var peerVerifyError : QtJSXQSslErrorSignal;
    var sslErrors : QtJSXQSslErrorListSignal;
}
