/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStandardItemModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstandarditem.jsx";
import "qt/_signals.jsx";

native class QStandardItemModel
{
    function constructor ();

    // Methods
    function appendColumn (items : QStandardItem[]) : void;
    function appendRow (item : QStandardItem) : void;
    function appendRow (items : QStandardItem[]) : void;
    function clear () : void;
    function invisibleRootItem () : QStandardItem;
    function itemPrototype () : QStandardItem;
    function setHorizontalHeaderLabels (labels : string[]) : void;
    function setItemPrototype (item : QStandardItem) : void;
    function setVerticalHeaderLabels (labels : string[]) : void;

    // Signals
    var itemChanged : QtJSXQStandardItemSignal;
}
