/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStackedWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qwidget.jsx";

native class QStackedWidget extends QFrame
{
    function constructor (parent : QWidget);

    // Methods
    function currentWidget () : QWidget;
    function removeWidget (w : QWidget) : void;

    // Slots
    function setCurrentWidget (w : QWidget) : void;
}
