/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStatusTipEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QStatusTipEvent
{
    function constructor (tip : string);

    // Methods
    function tip () : string;
}
