/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStatusBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QStatusBar extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function currentMessage () : string;
    function hideOrShow () : void;
    function reformat () : void;
    function removeWidget (widget : QWidget) : void;

    // Slots
    function clearMessage () : void;

    // Signals
    var messageChanged : QtJSXQStringSignal;
}
