/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStandardItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstandarditemmodel.jsx";

native class QStandardItem
{
    function constructor ();
    function constructor (text : string);

    // Methods
    function accessibleDescription () : string;
    function accessibleText () : string;
    function appendColumn (items : QStandardItem[]) : void;
    function appendRow (item : QStandardItem) : void;
    function appendRow (items : QStandardItem[]) : void;
    function appendRows (items : QStandardItem[]) : void;
    function clearData () : void;
    function clone () : QStandardItem;
    function emitDataChanged () : void;
    function model () : QStandardItemModel;
    function parent () : QStandardItem;
    function setAccessibleDescription (accessibleDescription : string) : void;
    function setAccessibleText (accessibleText : string) : void;
    function setStatusTip (statusTip : string) : void;
    function setText (text : string) : void;
    function setToolTip (toolTip : string) : void;
    function setWhatsThis (whatsThis : string) : void;
    function statusTip () : string;
    function text () : string;
    function toolTip () : string;
    function whatsThis () : string;
}
