/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStringListModel class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QStringListModel
{
    function constructor ();

    // Methods
    function setStringList (strings : string[]) : void;
    function stringList () : string[];
}
