/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStylePainter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qpaintdevice.jsx";
import "qt/qstyle.jsx";
import "qt/qstyleoption.jsx";
import "qt/qstyleoptioncomplex.jsx";
import "qt/qwidget.jsx";

native class QStylePainter
{
    function constructor ();
    function constructor (pd : QPaintDevice, w : QWidget);
    function constructor (w : QWidget);

    // Methods
    function drawComplexControl (cc : Qt_QStyle_ComplexControl, opt : QStyleOptionComplex) : void;
    function drawControl (ce : Qt_QStyle_ControlElement, opt : QStyleOption) : void;
    function drawPrimitive (pe : Qt_QStyle_PrimitiveElement, opt : QStyleOption) : void;
    function style () : QStyle;
}
