/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStylePlugin class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyle.jsx";

native class QStylePlugin
{
    function constructor ();

    // Methods
    function create (key : string) : QStyle;
}
