/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionGraphicsItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoption.jsx";

final native class Qt_QStyleOptionGraphicsItem_StyleOptionVersion {}

final native class Qt_QStyleOptionGraphicsItem_StyleOptionType {}

native class QStyleOptionGraphicsItem extends QStyleOption
{
    function constructor ();
    function constructor (other : QStyleOptionGraphicsItem);

    static const Version : Qt_QStyleOptionGraphicsItem_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionGraphicsItem_StyleOptionVersion) : Qt_QStyleOptionGraphicsItem_StyleOptionVersion;

    static const Type : Qt_QStyleOptionGraphicsItem_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionGraphicsItem_StyleOptionType) : Qt_QStyleOptionGraphicsItem_StyleOptionType;

    // Methods
    function operator_assign (arg__1 : QStyleOptionGraphicsItem) : QStyleOptionGraphicsItem;
}
