/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QStyleOptionSizeGrip class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptioncomplex.jsx";

final native class Qt_QStyleOptionSizeGrip_StyleOptionType {}

final native class Qt_QStyleOptionSizeGrip_StyleOptionVersion {}

native class QStyleOptionSizeGrip extends QStyleOptionComplex
{
    function constructor ();
    function constructor (other : QStyleOptionSizeGrip);

    static const Type : Qt_QStyleOptionSizeGrip_StyleOptionType;
    static function StyleOptionType(value : Qt_QStyleOptionSizeGrip_StyleOptionType) : Qt_QStyleOptionSizeGrip_StyleOptionType;

    static const Version : Qt_QStyleOptionSizeGrip_StyleOptionVersion;
    static function StyleOptionVersion(value : Qt_QStyleOptionSizeGrip_StyleOptionVersion) : Qt_QStyleOptionSizeGrip_StyleOptionVersion;
}
