/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbytearray.jsx";
import "qt/qpaintevent.jsx";
import "qt/qsvgrenderer.jsx";

native class QSvgWidget
{
    function constructor ();

    // Methods
    function load (contents : QByteArray) : void;
    function load (file : string) : void;
    function paintEvent (event : QPaintEvent) : void;
    function renderer () : QSvgRenderer;
}
