/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qsvgrenderer.jsx";

native class QSvgWidget
{
    function constructor ();

    // Methods
    function renderer () : QSvgRenderer;

    // Slots
    function load (file : string) : void;
}
