/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgGenerator class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QSvgGenerator
{
    function constructor ();

    // Instance Properties
    var title : string;
    var description : string;
    var fileName : string;
}
