/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgGenerator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qiodevice.jsx";
import "qt/qpaintdevice.jsx";
import "qt/qpaintengine.jsx";
import "qt/qrectf.jsx";
import "qt/qsize.jsx";

native class QSvgGenerator
{
    function constructor ();

    // Methods
    function metric (metric : Qt_QPaintDevice_PaintDeviceMetric) : int;
    function paintEngine () : QPaintEngine;

    // Instance Properties
    var size : QSize;
    var viewBox : QRectF;
    var title : string;
    var description : string;
    var fileName : string;
    var outputDevice : QIODevice;
    var resolution : int;
}
