/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSvgRenderer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/_signals.jsx";

native class QSvgRenderer
{

    // Signals
    var repaintNeeded : QtJSXSignal;
}
