/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSwipeGesture class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qgesture.jsx";

native class QSwipeGesture extends QGesture
{
    function constructor ();

    // Instance Properties
    var horizontalDirection : Qt_QSwipeGesture_SwipeDirection;
    var verticalDirection : Qt_QSwipeGesture_SwipeDirection;
    var swipeAngle : number;
}
