/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSyntaxHighlighter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextblock.jsx";
import "qt/qtextblockuserdata.jsx";
import "qt/qtextdocument.jsx";

native class QSyntaxHighlighter
{
    function constructor (parent : QTextDocument);

    // Methods
    function currentBlock () : QTextBlock;
    function currentBlockUserData () : QTextBlockUserData;
    function document () : QTextDocument;
    function highlightBlock (text : string) : void;
    function setCurrentBlockUserData (data : QTextBlockUserData) : void;
    function setDocument (doc : QTextDocument) : void;

    // Slots
    function rehighlight () : void;
    function rehighlightBlock (block : QTextBlock) : void;
}
