/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QSystemTrayIcon class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qmenu.jsx";
import "qt/_signals.jsx";

final native class Qt_QSystemTrayIcon_MessageIcon {}

final native class Qt_QSystemTrayIcon_ActivationReason {}

native class QSystemTrayIcon
{
    function constructor ();

    static const NoIcon : Qt_QSystemTrayIcon_MessageIcon;
    static const Information : Qt_QSystemTrayIcon_MessageIcon;
    static const Warning : Qt_QSystemTrayIcon_MessageIcon;
    static const Critical : Qt_QSystemTrayIcon_MessageIcon;
    static function MessageIcon(value : Qt_QSystemTrayIcon_MessageIcon) : Qt_QSystemTrayIcon_MessageIcon;

    static const Unknown : Qt_QSystemTrayIcon_ActivationReason;
    static const Context : Qt_QSystemTrayIcon_ActivationReason;
    static const DoubleClick : Qt_QSystemTrayIcon_ActivationReason;
    static const Trigger : Qt_QSystemTrayIcon_ActivationReason;
    static const MiddleClick : Qt_QSystemTrayIcon_ActivationReason;
    static function ActivationReason(value : Qt_QSystemTrayIcon_ActivationReason) : Qt_QSystemTrayIcon_ActivationReason;

    // Methods
    function contextMenu () : QMenu;
    function setContextMenu (menu : QMenu) : void;

    // Slots
    function hide () : void;
    function show () : void;

    // Signals
    var activated : QtJSXQt_QSystemTrayIcon_ActivationReasonSignal;
    var messageClicked : QtJSXSignal;

    // Instance Properties
    var toolTip : string;
}
