/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * Qt namespace
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextstream.jsx";

final native class Qt_GlobalColor {}

final native class Qt_KeyboardModifier {}

final native class Qt_KeyboardModifiers {}

native class Qt
{

    // Static Members
    static function bin (s : QTextStream) : QTextStream;
    static function bom (s : QTextStream) : QTextStream;
    static function center (s : QTextStream) : QTextStream;
    static function dec (s : QTextStream) : QTextStream;
    static function endl (s : QTextStream) : QTextStream;
    static function fixed (s : QTextStream) : QTextStream;
    static function flush (s : QTextStream) : QTextStream;
    static function forcepoint (s : QTextStream) : QTextStream;
    static function forcesign (s : QTextStream) : QTextStream;
    static function hex (s : QTextStream) : QTextStream;
    static function left (s : QTextStream) : QTextStream;
    static function lowercasebase (s : QTextStream) : QTextStream;
    static function lowercasedigits (s : QTextStream) : QTextStream;
    static function noforcepoint (s : QTextStream) : QTextStream;
    static function noforcesign (s : QTextStream) : QTextStream;
    static function noshowbase (s : QTextStream) : QTextStream;
    static function oct (s : QTextStream) : QTextStream;
    static function reset (s : QTextStream) : QTextStream;
    static function right (s : QTextStream) : QTextStream;
    static function scientific (s : QTextStream) : QTextStream;
    static function showbase (s : QTextStream) : QTextStream;
    static function uppercasebase (s : QTextStream) : QTextStream;
    static function uppercasedigits (s : QTextStream) : QTextStream;
    static function ws (s : QTextStream) : QTextStream;

    static const color0 : Qt_GlobalColor;
    static const color1 : Qt_GlobalColor;
    static const black : Qt_GlobalColor;
    static const white : Qt_GlobalColor;
    static const darkGray : Qt_GlobalColor;
    static const gray : Qt_GlobalColor;
    static const lightGray : Qt_GlobalColor;
    static const red : Qt_GlobalColor;
    static const green : Qt_GlobalColor;
    static const blue : Qt_GlobalColor;
    static const cyan : Qt_GlobalColor;
    static const magenta : Qt_GlobalColor;
    static const yellow : Qt_GlobalColor;
    static const darkRed : Qt_GlobalColor;
    static const darkGreen : Qt_GlobalColor;
    static const darkBlue : Qt_GlobalColor;
    static const darkCyan : Qt_GlobalColor;
    static const darkMagenta : Qt_GlobalColor;
    static const darkYellow : Qt_GlobalColor;
    static const transparent : Qt_GlobalColor;
    static function GlobalColor(value : Qt_GlobalColor) : Qt_GlobalColor;

    static const KeyboardModifierMask : Qt_KeyboardModifier;
    static const NoModifier : Qt_KeyboardModifier;
    static const ShiftModifier : Qt_KeyboardModifier;
    static const ControlModifier : Qt_KeyboardModifier;
    static const AltModifier : Qt_KeyboardModifier;
    static const MetaModifier : Qt_KeyboardModifier;
    static const KeypadModifier : Qt_KeyboardModifier;
    static const GroupSwitchModifier : Qt_KeyboardModifier;
    static function KeyboardModifier(value : Qt_KeyboardModifier) : Qt_KeyboardModifier;
    static function KeyboardModifiers(...value : Qt_KeyboardModifier) : Qt_KeyboardModifiers;
}
