/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTableView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qheaderview.jsx";
import "qt/qwidget.jsx";

native class QTableView extends QAbstractItemView
{
    function constructor (parent : QWidget);

    // Methods
    function clearSpans () : void;
    function horizontalHeader () : QHeaderView;
    function setHorizontalHeader (header : QHeaderView) : void;
    function setVerticalHeader (header : QHeaderView) : void;
    function verticalHeader () : QHeaderView;

    // Slots
    function resizeColumnsToContents () : void;
    function resizeRowsToContents () : void;
}
