/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTabBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";

final native class Qt_QTabBar_Shape {}

final native class Qt_QTabBar_SelectionBehavior {}

native class QTabBar extends QWidget
{
    function constructor (parent : QWidget);

    static const RoundedNorth : Qt_QTabBar_Shape;
    static const RoundedSouth : Qt_QTabBar_Shape;
    static const RoundedWest : Qt_QTabBar_Shape;
    static const RoundedEast : Qt_QTabBar_Shape;
    static const TriangularNorth : Qt_QTabBar_Shape;
    static const TriangularSouth : Qt_QTabBar_Shape;
    static const TriangularWest : Qt_QTabBar_Shape;
    static const TriangularEast : Qt_QTabBar_Shape;
    static function Shape(value : Qt_QTabBar_Shape) : Qt_QTabBar_Shape;

    static const SelectLeftTab : Qt_QTabBar_SelectionBehavior;
    static const SelectRightTab : Qt_QTabBar_SelectionBehavior;
    static const SelectPreviousTab : Qt_QTabBar_SelectionBehavior;
    static function SelectionBehavior(value : Qt_QTabBar_SelectionBehavior) : Qt_QTabBar_SelectionBehavior;

    // Methods
    function tabLayoutChange () : void;

    // Instance Properties
    var shape : Qt_QTabBar_Shape;
    var selectionBehaviorOnRemove : Qt_QTabBar_SelectionBehavior;
}
