/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTableWidgetSelectionRange class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QTableWidgetSelectionRange
{
    function constructor ();
    function constructor (other : QTableWidgetSelectionRange);

    // Methods
    function operator_assign (other : QTableWidgetSelectionRange) : QTableWidgetSelectionRange;
}
