/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTableWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qitemselectionmodel.jsx";
import "qt/qtableview.jsx";
import "qt/qtablewidgetitem.jsx";
import "qt/qtablewidgetselectionrange.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QTableWidget extends QTableView
{
    function constructor (parent : QWidget);

    // Methods
    function closePersistentEditor (item : QTableWidgetItem) : void;
    function currentItem () : QTableWidgetItem;
    function editItem (item : QTableWidgetItem) : void;
    function itemPrototype () : QTableWidgetItem;
    function mimeTypes () : string[];
    function openPersistentEditor (item : QTableWidgetItem) : void;
    function selectedItems () : QTableWidgetItem[];
    function selectedRanges () : QTableWidgetSelectionRange[];
    function setCurrentItem (item : QTableWidgetItem) : void;
    function setCurrentItem (item : QTableWidgetItem, command : Qt_QItemSelectionModel_SelectionFlags) : void;
    function setHorizontalHeaderLabels (labels : string[]) : void;
    function setItemPrototype (item : QTableWidgetItem) : void;
    function setVerticalHeaderLabels (labels : string[]) : void;

    // Slots
    function clear () : void;
    function clearContents () : void;
    function scrollToItem (item : QTableWidgetItem, hint : Qt_QAbstractItemView_ScrollHint) : void;

    // Signals
    var currentItemChanged : QtJSXQTableWidgetItemQTableWidgetItemSignal;
    var itemActivated : QtJSXQTableWidgetItemSignal;
    var itemChanged : QtJSXQTableWidgetItemSignal;
    var itemClicked : QtJSXQTableWidgetItemSignal;
    var itemDoubleClicked : QtJSXQTableWidgetItemSignal;
    var itemEntered : QtJSXQTableWidgetItemSignal;
    var itemPressed : QtJSXQTableWidgetItemSignal;
    var itemSelectionChanged : QtJSXSignal;
}
