/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTabletEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qinputevent.jsx";

final native class Qt_QTabletEvent_TabletDevice {}

native class QTabletEvent extends QInputEvent
{

    static const NoDevice : Qt_QTabletEvent_TabletDevice;
    static const Puck : Qt_QTabletEvent_TabletDevice;
    static const Stylus : Qt_QTabletEvent_TabletDevice;
    static const Airbrush : Qt_QTabletEvent_TabletDevice;
    static const FourDMouse : Qt_QTabletEvent_TabletDevice;
    static const XFreeEraser : Qt_QTabletEvent_TabletDevice;
    static const RotationStylus : Qt_QTabletEvent_TabletDevice;
    static function TabletDevice(value : Qt_QTabletEvent_TabletDevice) : Qt_QTabletEvent_TabletDevice;

    // Methods
    function device () : Qt_QTabletEvent_TabletDevice;
    function deviceType () : Qt_QTabletEvent_TabletDevice;
    function pointerType () : Qt_QTabletEvent_PointerType;
}
