/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTableWidgetItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtablewidget.jsx";

final native class Qt_QTableWidgetItem_ItemType {}

native class QTableWidgetItem
{

    static const Type : Qt_QTableWidgetItem_ItemType;
    static const UserType : Qt_QTableWidgetItem_ItemType;
    static function ItemType(value : Qt_QTableWidgetItem_ItemType) : Qt_QTableWidgetItem_ItemType;

    // Methods
    function clone () : QTableWidgetItem;
    function setStatusTip (statusTip : string) : void;
    function setText (text : string) : void;
    function setToolTip (toolTip : string) : void;
    function setWhatsThis (whatsThis : string) : void;
    function statusTip () : string;
    function tableWidget () : QTableWidget;
    function text () : string;
    function toolTip () : string;
    function whatsThis () : string;
}
