/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTabWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qstyleoptiontabwidgetframe.jsx";
import "qt/qtabbar.jsx";
import "qt/qwidget.jsx";

final native class Qt_QTabWidget_TabShape {}

final native class Qt_QTabWidget_TabPosition {}

native class QTabWidget extends QWidget
{
    function constructor (parent : QWidget);

    static const Rounded : Qt_QTabWidget_TabShape;
    static const Triangular : Qt_QTabWidget_TabShape;
    static function TabShape(value : Qt_QTabWidget_TabShape) : Qt_QTabWidget_TabShape;

    static const North : Qt_QTabWidget_TabPosition;
    static const South : Qt_QTabWidget_TabPosition;
    static const West : Qt_QTabWidget_TabPosition;
    static const East : Qt_QTabWidget_TabPosition;
    static function TabPosition(value : Qt_QTabWidget_TabPosition) : Qt_QTabWidget_TabPosition;

    // Methods
    function clear () : void;
    function currentWidget () : QWidget;
    function initStyleOption (option : QStyleOptionTabWidgetFrame) : void;
    function setTabBar (arg__1 : QTabBar) : void;
    function tabBar () : QTabBar;

    // Slots
    function setCurrentWidget (widget : QWidget) : void;

    // Instance Properties
    var tabPosition : Qt_QTabWidget_TabPosition;
    var tabShape : Qt_QTabWidget_TabShape;
}
