/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTcpServer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractsocket.jsx";
import "qt/qhostaddress.jsx";
import "qt/qnetworkproxy.jsx";
import "qt/qtcpsocket.jsx";
import "qt/_signals.jsx";

native class QTcpServer
{
    function constructor ();

    // Methods
    function addPendingConnection (socket : QTcpSocket) : void;
    function close () : void;
    function errorString () : string;
    function nextPendingConnection () : QTcpSocket;
    function pauseAccepting () : void;
    function proxy () : QNetworkProxy;
    function resumeAccepting () : void;
    function serverAddress () : QHostAddress;
    function serverError () : Qt_QAbstractSocket_SocketError;
    function setProxy (networkProxy : QNetworkProxy) : void;

    // Signals
    var acceptError : QtJSXQt_QAbstractSocket_SocketErrorSignal;
    var newConnection : QtJSXSignal;
}
