/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTcpSocket class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractsocket.jsx";

native class QTcpSocket extends QAbstractSocket
{
    function constructor ();
}
