/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextFrameFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qtextformat.jsx";
import "qt/qtextlength.jsx";

final native class Qt_QTextFrameFormat_Position {}

final native class Qt_QTextFrameFormat_BorderStyle {}

native class QTextFrameFormat extends QTextFormat
{
    function constructor ();

    static const InFlow : Qt_QTextFrameFormat_Position;
    static const FloatLeft : Qt_QTextFrameFormat_Position;
    static const FloatRight : Qt_QTextFrameFormat_Position;
    static function Position(value : Qt_QTextFrameFormat_Position) : Qt_QTextFrameFormat_Position;

    static const BorderStyle_None : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Dotted : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Dashed : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Solid : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Double : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_DotDash : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_DotDotDash : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Groove : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Ridge : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Inset : Qt_QTextFrameFormat_BorderStyle;
    static const BorderStyle_Outset : Qt_QTextFrameFormat_BorderStyle;
    static function BorderStyle(value : Qt_QTextFrameFormat_BorderStyle) : Qt_QTextFrameFormat_BorderStyle;

    // Methods
    function borderBrush () : QBrush;
    function borderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function height () : QTextLength;
    function pageBreakPolicy () : Qt_QTextFormat_PageBreakFlags;
    function position () : Qt_QTextFrameFormat_Position;
    function setBorderBrush (brush : QBrush) : void;
    function setBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setHeight (height : QTextLength) : void;
    function setPageBreakPolicy (flags : Qt_QTextFormat_PageBreakFlags) : void;
    function setPosition (f : Qt_QTextFrameFormat_Position) : void;
    function setWidth (length : QTextLength) : void;
    function width () : QTextLength;
}
