/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextBlock class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextblockformat.jsx";
import "qt/qtextblockuserdata.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextdocument.jsx";
import "qt/qtextlayout.jsx";
import "qt/qtextlist.jsx";

native class QTextBlock
{
    function constructor ();
    function constructor (o : QTextBlock);

    // Methods
    function blockFormat () : QTextBlockFormat;
    function charFormat () : QTextCharFormat;
    function clearLayout () : void;
    function document () : QTextDocument;
    function layout () : QTextLayout;
    function next () : QTextBlock;
    function previous () : QTextBlock;
    function setUserData (data : QTextBlockUserData) : void;
    function text () : string;
    function textList () : QTextList;
    function userData () : QTextBlockUserData;
}
