/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextBlockFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextformat.jsx";

final native class Qt_QTextBlockFormat_LineHeightTypes {}

native class QTextBlockFormat extends QTextFormat
{
    function constructor ();

    static const SingleHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const ProportionalHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const FixedHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const MinimumHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static const LineDistanceHeight : Qt_QTextBlockFormat_LineHeightTypes;
    static function LineHeightTypes(value : Qt_QTextBlockFormat_LineHeightTypes) : Qt_QTextBlockFormat_LineHeightTypes;

    // Methods
    function pageBreakPolicy () : Qt_QTextFormat_PageBreakFlags;
    function setPageBreakPolicy (flags : Qt_QTextFormat_PageBreakFlags) : void;
}
