/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextBrowser class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextedit.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QTextBrowser extends QTextEdit
{
    function constructor (parent : QWidget);

    // Methods
    function clearHistory () : void;

    // Slots
    function backward () : void;
    function forward () : void;
    function home () : void;
    function reload () : void;

    // Signals
    var highlighted : QtJSXQStringSignal;
    var historyChanged : QtJSXSignal;

    // Instance Properties
    var searchPaths : string[];
}
