/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextCharFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qcolor.jsx";
import "qt/qfont.jsx";
import "qt/qpen.jsx";
import "qt/qtextformat.jsx";

native class QTextCharFormat extends QTextFormat
{
    function constructor ();

    // Methods
    function anchorHref () : string;
    function anchorNames () : string[];
    function font () : QFont;
    function fontCapitalization () : Qt_QFont_Capitalization;
    function fontFamilies () : variant;
    function fontFamily () : string;
    function fontFixedPitch () : boolean;
    function fontItalic () : boolean;
    function fontKerning () : boolean;
    function fontLetterSpacing () : number;
    function fontLetterSpacingType () : Qt_QFont_SpacingType;
    function fontOverline () : boolean;
    function fontPointSize () : number;
    function fontStretch () : int;
    function fontStrikeOut () : boolean;
    function fontStyleHint () : Qt_QFont_StyleHint;
    function fontStyleName () : variant;
    function fontStyleStrategy () : Qt_QFont_StyleStrategy;
    function fontUnderline () : boolean;
    function fontWeight () : int;
    function fontWordSpacing () : number;
    function isAnchor () : boolean;
    function setAnchor (anchor : boolean) : void;
    function setAnchorHref (value : string) : void;
    function setAnchorNames (names : string[]) : void;
    function setFont (font : QFont) : void;
    function setFontCapitalization (capitalization : Qt_QFont_Capitalization) : void;
    function setFontFamilies (families : string[]) : void;
    function setFontFamily (family : string) : void;
    function setFontFixedPitch (fixedPitch : boolean) : void;
    function setFontItalic (italic : boolean) : void;
    function setFontKerning (enable : boolean) : void;
    function setFontLetterSpacing (spacing : number) : void;
    function setFontLetterSpacingType (letterSpacingType : Qt_QFont_SpacingType) : void;
    function setFontOverline (overline : boolean) : void;
    function setFontPointSize (size : number) : void;
    function setFontStretch (factor : int) : void;
    function setFontStrikeOut (strikeOut : boolean) : void;
    function setFontStyleHint (hint : Qt_QFont_StyleHint, strategy : Qt_QFont_StyleStrategy) : void;
    function setFontStyleName (styleName : string) : void;
    function setFontStyleStrategy (strategy : Qt_QFont_StyleStrategy) : void;
    function setFontUnderline (underline : boolean) : void;
    function setFontWeight (weight : int) : void;
    function setFontWordSpacing (spacing : number) : void;
    function setTableCellColumnSpan (tableCellColumnSpan : int) : void;
    function setTableCellRowSpan (tableCellRowSpan : int) : void;
    function setTextOutline (pen : QPen) : void;
    function setToolTip (tip : string) : void;
    function setUnderlineColor (color : QColor) : void;
    function tableCellColumnSpan () : int;
    function tableCellRowSpan () : int;
    function textOutline () : QPen;
    function toolTip () : string;
    function underlineColor () : QColor;
}
