/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextdocument.jsx";
import "qt/qtextformat.jsx";

native class QTextObject
{

    // Methods
    function document () : QTextDocument;
    function format () : QTextFormat;
    function setFormat (format : QTextFormat) : void;
}
