/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextLayout class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfont.jsx";
import "qt/qtextblock.jsx";
import "qt/qtextline.jsx";

final native class Qt_QTextLayout_CursorMode {}

native class QTextLayout
{
    function constructor ();
    function constructor (text : string);
    function constructor (b : QTextBlock);

    static const SkipCharacters : Qt_QTextLayout_CursorMode;
    static const SkipWords : Qt_QTextLayout_CursorMode;
    static function CursorMode(value : Qt_QTextLayout_CursorMode) : Qt_QTextLayout_CursorMode;

    // Methods
    function beginLayout () : void;
    function clearAdditionalFormats () : void;
    function clearFormats () : void;
    function clearLayout () : void;
    function createLine () : QTextLine;
    function endLayout () : void;
    function font () : QFont;
    function preeditAreaText () : string;
    function setFont (f : QFont) : void;
    function setText (string : string) : void;
    function text () : string;
}
