/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextTable class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcursor.jsx";
import "qt/qtextdocument.jsx";
import "qt/qtexttablecell.jsx";
import "qt/qtexttableformat.jsx";

native class QTextTable
{
    function constructor (doc : QTextDocument);

    // Methods
    function cellAt (c : QTextCursor) : QTextTableCell;
    function mergeCells (cursor : QTextCursor) : void;
    function rowEnd (c : QTextCursor) : QTextCursor;
    function rowStart (c : QTextCursor) : QTextCursor;
    function setFormat (format : QTextTableFormat) : void;
    function tableFormat () : QTextTableFormat;
}
