/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextInlineObject class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextformat.jsx";

native class QTextInlineObject
{
    function constructor ();

    // Methods
    function format () : QTextFormat;
}
