/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qtextblockformat.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextframeformat.jsx";
import "qt/qtextimageformat.jsx";
import "qt/qtextlistformat.jsx";
import "qt/qtexttablecellformat.jsx";
import "qt/qtexttableformat.jsx";

final native class Qt_QTextFormat_FormatType {}

native class QTextFormat
{
    function constructor ();
    function constructor (rhs : QTextFormat);

    static const InvalidFormat : Qt_QTextFormat_FormatType;
    static const BlockFormat : Qt_QTextFormat_FormatType;
    static const CharFormat : Qt_QTextFormat_FormatType;
    static const ListFormat : Qt_QTextFormat_FormatType;
    static const TableFormat : Qt_QTextFormat_FormatType;
    static const FrameFormat : Qt_QTextFormat_FormatType;
    static const UserFormat : Qt_QTextFormat_FormatType;
    static function FormatType(value : Qt_QTextFormat_FormatType) : Qt_QTextFormat_FormatType;

    // Methods
    function background () : QBrush;
    function clearBackground () : void;
    function clearForeground () : void;
    function foreground () : QBrush;
    function merge (other : QTextFormat) : void;
    function setBackground (brush : QBrush) : void;
    function setForeground (brush : QBrush) : void;
    function swap (other : QTextFormat) : void;
    function toBlockFormat () : QTextBlockFormat;
    function toCharFormat () : QTextCharFormat;
    function toFrameFormat () : QTextFrameFormat;
    function toImageFormat () : QTextImageFormat;
    function toListFormat () : QTextListFormat;
    function toTableCellFormat () : QTextTableCellFormat;
    function toTableFormat () : QTextTableFormat;
}
