/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextTableCell class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcharformat.jsx";
import "qt/qtextcursor.jsx";

native class QTextTableCell
{
    function constructor ();
    function constructor (o : QTextTableCell);

    // Methods
    function firstCursorPosition () : QTextCursor;
    function format () : QTextCharFormat;
    function lastCursorPosition () : QTextCursor;
    function setFormat (format : QTextCharFormat) : void;
}
