/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextImageFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QTextImageFormat
{
    function constructor ();

    // Methods
    function name () : string;
    function setName (name : string) : void;
}
