/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextTableCellFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qtextframeformat.jsx";

native class QTextTableCellFormat
{
    function constructor ();

    // Methods
    function bottomBorderBrush () : QBrush;
    function bottomBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function leftBorderBrush () : QBrush;
    function leftBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function rightBorderBrush () : QBrush;
    function rightBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function setBorderBrush (brush : QBrush) : void;
    function setBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setBottomBorderBrush (brush : QBrush) : void;
    function setBottomBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setLeftBorderBrush (brush : QBrush) : void;
    function setLeftBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setRightBorderBrush (brush : QBrush) : void;
    function setRightBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setTopBorderBrush (brush : QBrush) : void;
    function setTopBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function topBorderBrush () : QBrush;
    function topBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
}
