/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextLength class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QTextLength_Type {}

native class QTextLength
{
    function constructor ();

    static const VariableLength : Qt_QTextLength_Type;
    static const FixedLength : Qt_QTextLength_Type;
    static const PercentageLength : Qt_QTextLength_Type;
    static function Type(value : Qt_QTextLength_Type) : Qt_QTextLength_Type;

    // Methods
    function type () : Qt_QTextLength_Type;
}
