/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextDocumentFragment class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcursor.jsx";
import "qt/qtextdocument.jsx";

native class QTextDocumentFragment
{
    function constructor ();
    function constructor (range : QTextCursor);
    function constructor (document : QTextDocument);
    function constructor (rhs : QTextDocumentFragment);

    // Static Members
    static function fromHtml (html : string) : QTextDocumentFragment;
    static function fromPlainText (plainText : string) : QTextDocumentFragment;

    // Methods
    function toPlainText () : string;
}
