/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextTableCellFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qbrush.jsx";
import "qt/qtextcharformat.jsx";
import "qt/qtextframeformat.jsx";

native class QTextTableCellFormat extends QTextCharFormat
{
    function constructor ();

    // Methods
    function bottomBorder () : number;
    function bottomBorderBrush () : QBrush;
    function bottomBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function bottomPadding () : number;
    function leftBorder () : number;
    function leftBorderBrush () : QBrush;
    function leftBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function leftPadding () : number;
    function rightBorder () : number;
    function rightBorderBrush () : QBrush;
    function rightBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function rightPadding () : number;
    function setBorder (width : number) : void;
    function setBorderBrush (brush : QBrush) : void;
    function setBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setBottomBorder (width : number) : void;
    function setBottomBorderBrush (brush : QBrush) : void;
    function setBottomBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setBottomPadding (padding : number) : void;
    function setLeftBorder (width : number) : void;
    function setLeftBorderBrush (brush : QBrush) : void;
    function setLeftBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setLeftPadding (padding : number) : void;
    function setPadding (padding : number) : void;
    function setRightBorder (width : number) : void;
    function setRightBorderBrush (brush : QBrush) : void;
    function setRightBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setRightPadding (padding : number) : void;
    function setTopBorder (width : number) : void;
    function setTopBorderBrush (brush : QBrush) : void;
    function setTopBorderStyle (style : Qt_QTextFrameFormat_BorderStyle) : void;
    function setTopPadding (padding : number) : void;
    function topBorder () : number;
    function topBorderBrush () : QBrush;
    function topBorderStyle () : Qt_QTextFrameFormat_BorderStyle;
    function topPadding () : number;
}
