/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextDocumentWriter class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QTextDocumentWriter
{
    function constructor ();

    // Methods
    function fileName () : string;
    function setFileName (fileName : string) : void;
}
