/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextFragment class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextcharformat.jsx";

native class QTextFragment
{
    function constructor ();
    function constructor (o : QTextFragment);

    // Methods
    function charFormat () : QTextCharFormat;
    function text () : string;
}
