/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextTableFormat class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtextframeformat.jsx";
import "qt/qtextlength.jsx";

native class QTextTableFormat extends QTextFrameFormat
{
    function constructor ();

    // Methods
    function clearColumnWidthConstraints () : void;
    function columnWidthConstraints () : QTextLength[];
    function setColumnWidthConstraints (constraints : QTextLength[]) : void;
}
