/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextDocument class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qfont.jsx";
import "qt/qtextblock.jsx";
import "qt/qtextcursor.jsx";
import "qt/qtextformat.jsx";
import "qt/qtextframe.jsx";
import "qt/qtextobject.jsx";
import "qt/_signals.jsx";

final native class Qt_QTextDocument_MetaInformation {}

final native class Qt_QTextDocument_Stacks {}

final native class Qt_QTextDocument_ResourceType {}

final native class Qt_QTextDocument_FindFlag {}

final native class Qt_QTextDocument_FindFlags {}

native class QTextDocument
{
    function constructor ();

    static const DocumentTitle : Qt_QTextDocument_MetaInformation;
    static const DocumentUrl : Qt_QTextDocument_MetaInformation;
    static function MetaInformation(value : Qt_QTextDocument_MetaInformation) : Qt_QTextDocument_MetaInformation;

    static const UndoStack : Qt_QTextDocument_Stacks;
    static const RedoStack : Qt_QTextDocument_Stacks;
    static const UndoAndRedoStacks : Qt_QTextDocument_Stacks;
    static function Stacks(value : Qt_QTextDocument_Stacks) : Qt_QTextDocument_Stacks;

    static const UnknownResource : Qt_QTextDocument_ResourceType;
    static const HtmlResource : Qt_QTextDocument_ResourceType;
    static const ImageResource : Qt_QTextDocument_ResourceType;
    static const StyleSheetResource : Qt_QTextDocument_ResourceType;
    static const MarkdownResource : Qt_QTextDocument_ResourceType;
    static const UserResource : Qt_QTextDocument_ResourceType;
    static function ResourceType(value : Qt_QTextDocument_ResourceType) : Qt_QTextDocument_ResourceType;

    static const FindBackward : Qt_QTextDocument_FindFlag;
    static const FindCaseSensitively : Qt_QTextDocument_FindFlag;
    static const FindWholeWords : Qt_QTextDocument_FindFlag;
    static function FindFlag(value : Qt_QTextDocument_FindFlag) : Qt_QTextDocument_FindFlag;
    static function FindFlags(...value : Qt_QTextDocument_FindFlag) : Qt_QTextDocument_FindFlags;

    // Methods
    function adjustSize () : void;
    function allFormats () : QTextFormat[];
    function begin () : QTextBlock;
    function clear () : void;
    function clearUndoRedoStacks (historyToClear : Qt_QTextDocument_Stacks) : void;
    function createObject (f : QTextFormat) : QTextObject;
    function end () : QTextBlock;
    function find (subString : string, cursor : QTextCursor, options : Qt_QTextDocument_FindFlags) : QTextCursor;
    function firstBlock () : QTextBlock;
    function lastBlock () : QTextBlock;
    function metaInformation (info : Qt_QTextDocument_MetaInformation) : string;
    function objectForFormat (arg__1 : QTextFormat) : QTextObject;
    function redo (cursor : QTextCursor) : void;
    function rootFrame () : QTextFrame;
    function setHtml (html : string) : void;
    function setMetaInformation (info : Qt_QTextDocument_MetaInformation, arg__2 : string) : void;
    function setPlainText (text : string) : void;
    function toPlainText () : string;
    function toRawText () : string;
    function undo (cursor : QTextCursor) : void;

    // Slots
    function redo () : void;
    function undo () : void;

    // Signals
    var contentsChanged : QtJSXSignal;
    var cursorPositionChanged : QtJSXQTextCursorSignal;
    var documentLayoutChanged : QtJSXSignal;
    var undoCommandAdded : QtJSXSignal;

    // Instance Properties
    var defaultFont : QFont;
    var defaultStyleSheet : string;
}
