/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTextEdit class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractscrollarea.jsx";
import "qt/qmenu.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

final native class Qt_QTextEdit_LineWrapMode {}

native class QTextEdit extends QAbstractScrollArea
{
    function constructor (parent : QWidget);
    function constructor (text : string, parent : QWidget);

    static const NoWrap : Qt_QTextEdit_LineWrapMode;
    static const WidgetWidth : Qt_QTextEdit_LineWrapMode;
    static const FixedPixelWidth : Qt_QTextEdit_LineWrapMode;
    static const FixedColumnWidth : Qt_QTextEdit_LineWrapMode;
    static function LineWrapMode(value : Qt_QTextEdit_LineWrapMode) : Qt_QTextEdit_LineWrapMode;

    // Methods
    function createStandardContextMenu () : QMenu;
    function ensureCursorVisible () : void;
    function fontFamily () : string;
    function placeholderText () : string;
    function setPlaceholderText (placeholderText : string) : void;
    function toHtml () : string;
    function toPlainText () : string;

    // Slots
    function append (text : string) : void;
    function clear () : void;
    function copy () : void;
    function cut () : void;
    function insertHtml (text : string) : void;
    function insertPlainText (text : string) : void;
    function paste () : void;
    function redo () : void;
    function scrollToAnchor (name : string) : void;
    function selectAll () : void;
    function setFontFamily (fontFamily : string) : void;
    function setHtml (text : string) : void;
    function setMarkdown (markdown : string) : void;
    function setPlainText (text : string) : void;
    function setText (text : string) : void;
    function undo () : void;

    // Signals
    var cursorPositionChanged : QtJSXSignal;
    var selectionChanged : QtJSXSignal;
    var textChanged : QtJSXSignal;

    // Instance Properties
    var autoFormatting : Qt_QTextEdit_AutoFormatting;
    var documentTitle : string;
    var lineWrapMode : Qt_QTextEdit_LineWrapMode;
}
