/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QThreadPool class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qobject.jsx";
import "qt/qrunnable.jsx";

native class QThreadPool extends QObject
{
    function constructor (parent : QObject);

    // Static Members
    static function globalInstance () : QThreadPool;

    // Methods
    function cancel (runnable : QRunnable) : void;
    function clear () : void;
    function releaseThread () : void;
    function reserveThread () : void;
    function start (runnable : QRunnable, priority : int) : void;
    function tryStart (runnable : QRunnable) : boolean;
    function tryTake (runnable : QRunnable) : boolean;
    function waitForDone (msecs : int) : boolean;

    // Instance Properties
    var expiryTimeout : int;
    var maxThreadCount : int;
    var activeThreadCount : int;
    var stackSize : int;
}
