/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QToolBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qicon.jsx";
import "qt/qpoint.jsx";
import "qt/qrect.jsx";
import "qt/qsize.jsx";
import "qt/qstyleoptiontoolbar.jsx";
import "qt/qt.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QToolBar extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (title : string, parent : QWidget);

    // Methods
    function actionAt (p : QPoint) : QAction;
    function actionAt (x : int, y : int) : QAction;
    function actionGeometry (action : QAction) : QRect;
    function addAction (icon : QIcon, text : string) : QAction;
    function addAction (text : string) : QAction;
    function addSeparator () : QAction;
    function addWidget (widget : QWidget) : QAction;
    function clear () : void;
    function initStyleOption (option : QStyleOptionToolBar) : void;
    function insertSeparator (before : QAction) : QAction;
    function insertWidget (before : QAction, widget : QWidget) : QAction;
    function isAreaAllowed (area : Qt_ToolBarArea) : boolean;
    function toggleViewAction () : QAction;
    function widgetForAction (action : QAction) : QWidget;

    // Slots
    function setToolButtonStyle (toolButtonStyle : Qt_ToolButtonStyle) : void;

    // Signals
    var actionTriggered : QtJSXQActionSignal;
    var allowedAreasChanged : QtJSXQt_ToolBarAreasSignal;
    var iconSizeChanged : QtJSXQSizeSignal;
    var movableChanged : QtJSXboolSignal;
    var orientationChanged : QtJSXQt_OrientationSignal;
    var toolButtonStyleChanged : QtJSXQt_ToolButtonStyleSignal;
    var topLevelChanged : QtJSXboolSignal;
    var visibilityChanged : QtJSXboolSignal;

    // Instance Properties
    var movable : boolean;
    var allowedAreas : Qt_ToolBarAreas;
    var orientation : Qt_Orientation;
    var iconSize : QSize;
    var toolButtonStyle : Qt_ToolButtonStyle;
    var floating : boolean;
    var floatable : boolean;
}
