/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QToolTip class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QToolTip
{

    // Static Members
    static function hideText () : void;
    static function text () : string;
}
