/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QToolBox class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qframe.jsx";
import "qt/qwidget.jsx";

native class QToolBox extends QFrame
{
    function constructor ();

    // Methods
    function currentWidget () : QWidget;

    // Slots
    function setCurrentWidget (widget : QWidget) : void;
}
