/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QToolBar class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qstyleoptiontoolbar.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QToolBar extends QWidget
{
    function constructor (parent : QWidget);
    function constructor (title : string, parent : QWidget);

    // Methods
    function addAction (text : string) : QAction;
    function addSeparator () : QAction;
    function addWidget (widget : QWidget) : QAction;
    function clear () : void;
    function initStyleOption (option : QStyleOptionToolBar) : void;
    function insertSeparator (before : QAction) : QAction;
    function insertWidget (before : QAction, widget : QWidget) : QAction;
    function toggleViewAction () : QAction;
    function widgetForAction (action : QAction) : QWidget;

    // Signals
    var actionTriggered : QtJSXQActionSignal;
}
