/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTranslator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qlocale.jsx";
import "qt/qobject.jsx";

native class QTranslator
{
    function constructor (parent : QObject);

    // Methods
    function filePath () : string;
    function isEmpty () : boolean;
    function language () : string;
    function load (locale : QLocale, filename : string, prefix : string, directory : string, suffix : string) : boolean;
    function load (filename : string, directory : string, search_delimiters : string, suffix : string) : boolean;
    function load (data : string, len : int, directory : string) : boolean;
}
