/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTreeWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qtreeview.jsx";
import "qt/qtreewidgetitem.jsx";
import "qt/qwidget.jsx";
import "qt/_signals.jsx";

native class QTreeWidget extends QTreeView
{
    function constructor (parent : QWidget);

    // Methods
    function addTopLevelItem (item : QTreeWidgetItem) : void;
    function addTopLevelItems (items : QTreeWidgetItem[]) : void;
    function currentItem () : QTreeWidgetItem;
    function headerItem () : QTreeWidgetItem;
    function invisibleRootItem () : QTreeWidgetItem;
    function itemAbove (item : QTreeWidgetItem) : QTreeWidgetItem;
    function itemBelow (item : QTreeWidgetItem) : QTreeWidgetItem;
    function mimeTypes () : string[];
    function selectedItems () : QTreeWidgetItem[];
    function setCurrentItem (item : QTreeWidgetItem) : void;
    function setHeaderItem (item : QTreeWidgetItem) : void;
    function setHeaderLabel (label : string) : void;
    function setHeaderLabels (labels : string[]) : void;

    // Slots
    function clear () : void;
    function collapseItem (item : QTreeWidgetItem) : void;
    function expandItem (item : QTreeWidgetItem) : void;
    function scrollToItem (item : QTreeWidgetItem, hint : Qt_QAbstractItemView_ScrollHint) : void;

    // Signals
    var currentItemChanged : QtJSXQTreeWidgetItemQTreeWidgetItemSignal;
    var itemCollapsed : QtJSXQTreeWidgetItemSignal;
    var itemExpanded : QtJSXQTreeWidgetItemSignal;
    var itemSelectionChanged : QtJSXSignal;
}
