/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTreeView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractitemview.jsx";
import "qt/qheaderview.jsx";
import "qt/qwidget.jsx";

native class QTreeView extends QAbstractItemView
{
    function constructor (parent : QWidget);

    // Methods
    function header () : QHeaderView;
    function resetIndentation () : void;
    function setHeader (header : QHeaderView) : void;

    // Slots
    function collapseAll () : void;
    function columnMoved () : void;
    function expandAll () : void;
    function reexpand () : void;
}
