/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QTreeWidgetItem class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qtreewidget.jsx";

final native class Qt_QTreeWidgetItem_ItemType {}

final native class Qt_QTreeWidgetItem_ChildIndicatorPolicy {}

native class QTreeWidgetItem
{

    static const Type : Qt_QTreeWidgetItem_ItemType;
    static const UserType : Qt_QTreeWidgetItem_ItemType;
    static function ItemType(value : Qt_QTreeWidgetItem_ItemType) : Qt_QTreeWidgetItem_ItemType;

    static const ShowIndicator : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    static const DontShowIndicator : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    static const DontShowIndicatorWhenChildless : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    static function ChildIndicatorPolicy(value : Qt_QTreeWidgetItem_ChildIndicatorPolicy) : Qt_QTreeWidgetItem_ChildIndicatorPolicy;

    // Methods
    function addChild (child : QTreeWidgetItem) : void;
    function addChildren (children : QTreeWidgetItem[]) : void;
    function childIndicatorPolicy () : Qt_QTreeWidgetItem_ChildIndicatorPolicy;
    function clone () : QTreeWidgetItem;
    function emitDataChanged () : void;
    function parent () : QTreeWidgetItem;
    function removeChild (child : QTreeWidgetItem) : void;
    function setChildIndicatorPolicy (policy : Qt_QTreeWidgetItem_ChildIndicatorPolicy) : void;
    function takeChildren () : QTreeWidgetItem[];
    function treeWidget () : QTreeWidget;
}
