/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUdpSocket class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractsocket.jsx";
import "qt/qnetworkinterface.jsx";

native class QUdpSocket extends QAbstractSocket
{
    function constructor ();

    // Methods
    function multicastInterface () : QNetworkInterface;
    function setMulticastInterface (iface : QNetworkInterface) : void;
}
