/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUiLoader class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QUiLoader
{
    function constructor ();

    // Methods
    function addPluginPath (path : string) : void;
    function availableLayouts () : string[];
    function availableWidgets () : string[];
    function clearPluginPaths () : void;
    function errorString () : string;
    function pluginPaths () : string[];
}
