/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUndoStack class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qobject.jsx";
import "qt/qundocommand.jsx";
import "qt/_signals.jsx";

native class QUndoStack extends QObject
{
    function constructor (parent : QObject);

    // Methods
    function beginMacro (text : string) : void;
    function cleanIndex () : int;
    function clear () : void;
    function command (index : int) : QUndoCommand;
    function count () : int;
    function createRedoAction (parent : QObject, prefix : string) : QAction;
    function createUndoAction (parent : QObject, prefix : string) : QAction;
    function endMacro () : void;
    function index () : int;
    function push (cmd : QUndoCommand) : void;
    function text (idx : int) : string;

    // Slots
    function redo () : void;
    function resetClean () : void;
    function setClean () : void;
    function setIndex (idx : int) : void;
    function undo () : void;

    // Signals
    var canRedoChanged : QtJSXboolSignal;
    var canUndoChanged : QtJSXboolSignal;
    var cleanChanged : QtJSXboolSignal;
    var indexChanged : QtJSXintSignal;
    var redoTextChanged : QtJSXQStringSignal;
    var undoTextChanged : QtJSXQStringSignal;

    // Instance Properties
    var active : boolean;
    var undoLimit : int;
    var canUndo : boolean;
    var canRedo : boolean;
    var undoText : string;
    var redoText : string;
    var clean : boolean;
}
