/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUndoCommand class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QUndoCommand
{
    function constructor (parent : QUndoCommand);
    function constructor (text : string, parent : QUndoCommand);

    // Methods
    function actionText () : string;
    function redo () : void;
    function setText (text : string) : void;
    function text () : string;
    function undo () : void;
}
