/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUndoGroup class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qundostack.jsx";
import "qt/_signals.jsx";

native class QUndoGroup
{
    function constructor ();

    // Methods
    function activeStack () : QUndoStack;
    function addStack (stack : QUndoStack) : void;
    function redoText () : string;
    function removeStack (stack : QUndoStack) : void;
    function stacks () : QUndoStack[];
    function undoText () : string;

    // Slots
    function redo () : void;
    function setActiveStack (stack : QUndoStack) : void;
    function undo () : void;

    // Signals
    var activeStackChanged : QtJSXQUndoStackSignal;
    var redoTextChanged : QtJSXQStringSignal;
    var undoTextChanged : QtJSXQStringSignal;
}
