/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUndoView class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qicon.jsx";
import "qt/qlistview.jsx";
import "qt/qundogroup.jsx";
import "qt/qundostack.jsx";
import "qt/qwidget.jsx";

native class QUndoView extends QListView
{
    function constructor (group : QUndoGroup, parent : QWidget);
    function constructor (stack : QUndoStack, parent : QWidget);
    function constructor (parent : QWidget);

    // Methods
    function group () : QUndoGroup;
    function setGroup (group : QUndoGroup) : void;
    function setStack (stack : QUndoStack) : void;
    function stack () : QUndoStack;

    // Instance Properties
    var emptyLabel : string;
    var cleanIcon : QIcon;
}
