/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUndoStack class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qundocommand.jsx";
import "qt/_signals.jsx";

native class QUndoStack
{
    function constructor ();

    // Methods
    function beginMacro (text : string) : void;
    function clear () : void;
    function endMacro () : void;
    function push (cmd : QUndoCommand) : void;

    // Slots
    function redo () : void;
    function resetClean () : void;
    function setClean () : void;
    function undo () : void;

    // Signals
    var redoTextChanged : QtJSXQStringSignal;
    var undoTextChanged : QtJSXQStringSignal;

    // Instance Properties
    var undoText : string;
    var redoText : string;
}
