/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QUrl class
 *
 * Note: DO NOT EDIT THIS FILE
 */

final native class Qt_QUrl_ParsingMode {}

native class QUrl
{
    function constructor ();
    function constructor (url : string, mode : Qt_QUrl_ParsingMode);
    function constructor (copy : QUrl);

    static const TolerantMode : Qt_QUrl_ParsingMode;
    static const StrictMode : Qt_QUrl_ParsingMode;
    static const DecodedMode : Qt_QUrl_ParsingMode;
    static function ParsingMode(value : Qt_QUrl_ParsingMode) : Qt_QUrl_ParsingMode;
}
