/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/_signals.jsx";

final native class Qt_QValidator_State {}

native class QValidator
{
    function constructor ();

    static const Invalid : Qt_QValidator_State;
    static const Intermediate : Qt_QValidator_State;
    static const Acceptable : Qt_QValidator_State;
    static function State(value : Qt_QValidator_State) : Qt_QValidator_State;

    // Methods
    function fixup (arg__1 : string) : void;

    // Signals
    var changed : QtJSXSignal;
}
