/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QVector3D class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qvector2d.jsx";
import "qt/qvector4d.jsx";

native class QVector3D
{
    function constructor ();
    function constructor (vector : QVector2D);
    function constructor (vector : QVector4D);

    // Static Members
    static function crossProduct (v1 : QVector3D, v2 : QVector3D) : QVector3D;
    static function normal (v1 : QVector3D, v2 : QVector3D) : QVector3D;

    // Methods
    function normalize () : void;
    function normalized () : QVector3D;
    function operator_add_assign (vector : QVector3D) : QVector3D;
    function operator_divide_assign (vector : QVector3D) : QVector3D;
    function operator_multiply_assign (vector : QVector3D) : QVector3D;
    function operator_subtract_assign (vector : QVector3D) : QVector3D;
    function toVector2D () : QVector2D;
    function toVector4D () : QVector4D;
}
