/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QVector2D class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qvector3d.jsx";
import "qt/qvector4d.jsx";

native class QVector2D
{
    function constructor ();
    function constructor (vector : QVector3D);
    function constructor (vector : QVector4D);

    // Methods
    function normalize () : void;
    function normalized () : QVector2D;
    function operator_add_assign (vector : QVector2D) : QVector2D;
    function operator_divide_assign (vector : QVector2D) : QVector2D;
    function operator_multiply_assign (vector : QVector2D) : QVector2D;
    function operator_subtract_assign (vector : QVector2D) : QVector2D;
    function toVector3D () : QVector3D;
    function toVector4D () : QVector4D;
}
