/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QVector4D class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qvector2d.jsx";
import "qt/qvector3d.jsx";

native class QVector4D
{
    function constructor ();
    function constructor (vector : QVector2D);
    function constructor (vector : QVector3D);

    // Methods
    function normalize () : void;
    function normalized () : QVector4D;
    function operator_add_assign (vector : QVector4D) : QVector4D;
    function operator_divide_assign (vector : QVector4D) : QVector4D;
    function operator_multiply_assign (vector : QVector4D) : QVector4D;
    function operator_subtract_assign (vector : QVector4D) : QVector4D;
    function toVector2D () : QVector2D;
    function toVector2DAffine () : QVector2D;
    function toVector3D () : QVector3D;
    function toVector3DAffine () : QVector3D;
}
