/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWhatsThis class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QWhatsThis
{

    // Static Members
    static function enterWhatsThisMode () : void;
    static function hideText () : void;
    static function leaveWhatsThisMode () : void;
}
