/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWhatsThisClickedEvent class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QWhatsThisClickedEvent
{
    function constructor (href : string);

    // Methods
    function href () : string;
}
