/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWidget class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qaction.jsx";
import "qt/qgraphicseffect.jsx";
import "qt/qgraphicsproxywidget.jsx";
import "qt/qlayout.jsx";
import "qt/qsizepolicy.jsx";
import "qt/qstyle.jsx";
import "qt/_signals.jsx";

final native class Qt_QWidget_RenderFlag {}

final native class Qt_QWidget_RenderFlags {}

native class QWidget
{
    function constructor ();

    // Static Members
    static function keyboardGrabber () : QWidget;
    static function mouseGrabber () : QWidget;
    static function setTabOrder (arg__1 : QWidget, arg__2 : QWidget) : void;

    static const DrawWindowBackground : Qt_QWidget_RenderFlag;
    static const DrawChildren : Qt_QWidget_RenderFlag;
    static const IgnoreMask : Qt_QWidget_RenderFlag;
    static function RenderFlag(value : Qt_QWidget_RenderFlag) : Qt_QWidget_RenderFlag;
    static function RenderFlags(...value : Qt_QWidget_RenderFlag) : Qt_QWidget_RenderFlags;

    // Methods
    function actions () : QAction[];
    function activateWindow () : void;
    function addAction (action : QAction) : void;
    function addActions (actions : QAction[]) : void;
    function adjustSize () : void;
    function clearFocus () : void;
    function clearMask () : void;
    function createWinId () : void;
    function ensurePolished () : void;
    function focusProxy () : QWidget;
    function focusWidget () : QWidget;
    function grabKeyboard () : void;
    function grabMouse () : void;
    function graphicsEffect () : QGraphicsEffect;
    function graphicsProxyWidget () : QGraphicsProxyWidget;
    function insertAction (before : QAction, action : QAction) : void;
    function insertActions (before : QAction, actions : QAction[]) : void;
    function layout () : QLayout;
    function nativeParentWidget () : QWidget;
    function nextInFocusChain () : QWidget;
    function parentWidget () : QWidget;
    function previousInFocusChain () : QWidget;
    function releaseKeyboard () : void;
    function releaseMouse () : void;
    function removeAction (action : QAction) : void;
    function setFocusProxy (arg__1 : QWidget) : void;
    function setGraphicsEffect (effect : QGraphicsEffect) : void;
    function setLayout (arg__1 : QLayout) : void;
    function setParent (parent : QWidget) : void;
    function setSizePolicy (horizontal : Qt_QSizePolicy_Policy, vertical : Qt_QSizePolicy_Policy) : void;
    function setStyle (arg__1 : QStyle) : void;
    function setWindowFilePath (filePath : string) : void;
    function setWindowRole (arg__1 : string) : void;
    function stackUnder (arg__1 : QWidget) : void;
    function style () : QStyle;
    function styleSheet () : string;
    function unsetCursor () : void;
    function unsetLayoutDirection () : void;
    function unsetLocale () : void;
    function updateGeometry () : void;
    function window () : QWidget;
    function windowFilePath () : string;
    function windowRole () : string;

    // Slots
    function hide () : void;
    function lower () : void;
    function raise () : void;
    function repaint () : void;
    function setFocus () : void;
    function setStyleSheet (styleSheet : string) : void;
    function show () : void;
    function showFullScreen () : void;
    function showMaximized () : void;
    function showMinimized () : void;
    function showNormal () : void;
    function update () : void;
    function updateMicroFocus () : void;

    // Signals
    var windowIconTextChanged : QtJSXQStringSignal;
    var windowTitleChanged : QtJSXQStringSignal;

    // Instance Properties
    var sizePolicy : QSizePolicy;
    var windowTitle : string;
    var windowIconText : string;
    var toolTip : string;
    var statusTip : string;
    var whatsThis : string;
    var accessibleName : string;
    var accessibleDescription : string;
}
