/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWizardPage class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qwidget.jsx";
import "qt/qwizard.jsx";
import "qt/_signals.jsx";

native class QWizardPage extends QWidget
{
    function constructor (parent : QWidget);

    // Methods
    function buttonText (which : Qt_QWizard_WizardButton) : string;
    function cleanupPage () : void;
    function field (name : string) : variant;
    function initializePage () : void;
    function setButtonText (which : Qt_QWizard_WizardButton, text : string) : void;
    function setField (name : string, value : variant) : void;
    function wizard () : QWizard;

    // Signals
    var completeChanged : QtJSXSignal;

    // Instance Properties
    var title : string;
    var subTitle : string;
}
