/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QWizard class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractbutton.jsx";
import "qt/qdialog.jsx";
import "qt/qwidget.jsx";
import "qt/qwizardpage.jsx";
import "qt/_signals.jsx";

final native class Qt_QWizard_WizardPixmap {}

final native class Qt_QWizard_WizardButton {}

final native class Qt_QWizard_WizardStyle {}

native class QWizard extends QDialog
{
    function constructor ();

    static const WatermarkPixmap : Qt_QWizard_WizardPixmap;
    static const LogoPixmap : Qt_QWizard_WizardPixmap;
    static const BannerPixmap : Qt_QWizard_WizardPixmap;
    static const BackgroundPixmap : Qt_QWizard_WizardPixmap;
    static const NPixmaps : Qt_QWizard_WizardPixmap;
    static function WizardPixmap(value : Qt_QWizard_WizardPixmap) : Qt_QWizard_WizardPixmap;

    static const NoButton : Qt_QWizard_WizardButton;
    static const BackButton : Qt_QWizard_WizardButton;
    static const NextButton : Qt_QWizard_WizardButton;
    static const CommitButton : Qt_QWizard_WizardButton;
    static const FinishButton : Qt_QWizard_WizardButton;
    static const CancelButton : Qt_QWizard_WizardButton;
    static const HelpButton : Qt_QWizard_WizardButton;
    static const CustomButton1 : Qt_QWizard_WizardButton;
    static const CustomButton2 : Qt_QWizard_WizardButton;
    static const CustomButton3 : Qt_QWizard_WizardButton;
    static const Stretch : Qt_QWizard_WizardButton;
    static function WizardButton(value : Qt_QWizard_WizardButton) : Qt_QWizard_WizardButton;

    static const ClassicStyle : Qt_QWizard_WizardStyle;
    static const ModernStyle : Qt_QWizard_WizardStyle;
    static const MacStyle : Qt_QWizard_WizardStyle;
    static const AeroStyle : Qt_QWizard_WizardStyle;
    static const NStyles : Qt_QWizard_WizardStyle;
    static function WizardStyle(value : Qt_QWizard_WizardStyle) : Qt_QWizard_WizardStyle;

    // Methods
    function button (which : Qt_QWizard_WizardButton) : QAbstractButton;
    function buttonText (which : Qt_QWizard_WizardButton) : string;
    function currentPage () : QWizardPage;
    function field (name : string) : variant;
    function setButton (which : Qt_QWizard_WizardButton, button : QAbstractButton) : void;
    function setButtonLayout (layout : Qt_QWizard_WizardButton[]) : void;
    function setButtonText (which : Qt_QWizard_WizardButton, text : string) : void;
    function setField (name : string, value : variant) : void;
    function setSideWidget (widget : QWidget) : void;
    function sideWidget () : QWidget;

    // Slots
    function back () : void;
    function next () : void;
    function restart () : void;

    // Signals
    var helpRequested : QtJSXSignal;

    // Instance Properties
    var wizardStyle : Qt_QWizard_WizardStyle;
    var options : Qt_QWizard_WizardOptions;
}
