/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlName class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qxmlnamepool.jsx";

native class QXmlName
{
    function constructor ();
    function constructor (namePool : QXmlNamePool, localName : string, namespaceURI : string, prefix : string);
    function constructor (other : QXmlName);

    // Static Members
    static function fromClarkName (clarkName : string, namePool : QXmlNamePool) : QXmlName;

    // Methods
    function localName (query : QXmlNamePool) : string;
    function namespaceUri (query : QXmlNamePool) : string;
    function prefix (query : QXmlNamePool) : string;
    function toClarkName (query : QXmlNamePool) : string;
}
