/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlSerializer class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractxmlreceiver.jsx";

native class QXmlSerializer extends QAbstractXmlReceiver
{
    function constructor ();
}
