/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlSchema class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractmessagehandler.jsx";
import "qt/qabstracturiresolver.jsx";
import "qt/qbytearray.jsx";
import "qt/qiodevice.jsx";
import "qt/qurl.jsx";
import "qt/qxmlnamepool.jsx";

native class QXmlSchema
{
    function constructor ();
    function constructor (other : QXmlSchema);

    // Methods
    function documentUri () : QUrl;
    function isValid () : boolean;
    function load (source : QIODevice, documentUri : QUrl) : boolean;
    function load (data : QByteArray, documentUri : QUrl) : boolean;
    function load (source : QUrl) : boolean;
    function messageHandler () : QAbstractMessageHandler;
    function namePool () : QXmlNamePool;
    function operator_assign (other : QXmlSchema) : QXmlSchema;
    function setMessageHandler (handler : QAbstractMessageHandler) : void;
    function setUriResolver (resolver : QAbstractUriResolver) : void;
    function uriResolver () : QAbstractUriResolver;
}
