/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlFormatter class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qxmlserializer.jsx";

native class QXmlFormatter extends QXmlSerializer
{
    function constructor ();
}
