/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlQuery class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractmessagehandler.jsx";
import "qt/qabstracturiresolver.jsx";
import "qt/qxmlitem.jsx";
import "qt/qxmlname.jsx";
import "qt/qxmlnamepool.jsx";
import "qt/qxmlresultitems.jsx";

final native class Qt_QXmlQuery_QueryLanguage {}

native class QXmlQuery
{
    function constructor ();
    function constructor (queryLanguage : Qt_QXmlQuery_QueryLanguage, np : QXmlNamePool);
    function constructor (np : QXmlNamePool);
    function constructor (other : QXmlQuery);

    static const XQuery10 : Qt_QXmlQuery_QueryLanguage;
    static const XSLT20 : Qt_QXmlQuery_QueryLanguage;
    static const XmlSchema11IdentityConstraintSelector : Qt_QXmlQuery_QueryLanguage;
    static const XmlSchema11IdentityConstraintField : Qt_QXmlQuery_QueryLanguage;
    static const XPath20 : Qt_QXmlQuery_QueryLanguage;
    static function QueryLanguage(value : Qt_QXmlQuery_QueryLanguage) : Qt_QXmlQuery_QueryLanguage;

    // Methods
    function bindVariable (localName : string, value : QXmlItem) : void;
    function bindVariable (localName : string, query : QXmlQuery) : void;
    function bindVariable (name : QXmlName, value : QXmlItem) : void;
    function bindVariable (name : QXmlName, query : QXmlQuery) : void;
    function evaluateTo (result : QXmlResultItems) : void;
    function initialTemplateName () : QXmlName;
    function messageHandler () : QAbstractMessageHandler;
    function namePool () : QXmlNamePool;
    function operator_assign (other : QXmlQuery) : QXmlQuery;
    function queryLanguage () : Qt_QXmlQuery_QueryLanguage;
    function setFocus (item : QXmlItem) : void;
    function setInitialTemplateName (name : string) : void;
    function setInitialTemplateName (name : QXmlName) : void;
    function setMessageHandler (messageHandler : QAbstractMessageHandler) : void;
    function setUriResolver (resolver : QAbstractUriResolver) : void;
    function uriResolver () : QAbstractUriResolver;
}
