/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlStreamAttributes class
 *
 * Note: DO NOT EDIT THIS FILE
 */

native class QXmlStreamAttributes
{
    function constructor ();

    // Methods
    function append (namespaceUri : string, name : string, value : string) : void;
    function append (qualifiedName : string, value : string) : void;
    function hasAttribute (namespaceUri : string, name : string) : boolean;
    function hasAttribute (qualifiedName : string) : boolean;
    function value (namespaceUri : string, name : string) : string;
    function value (qualifiedName : string) : string;
}
