/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * QXmlSchemaValidator class
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractmessagehandler.jsx";
import "qt/qabstracturiresolver.jsx";
import "qt/qxmlnamepool.jsx";
import "qt/qxmlschema.jsx";

native class QXmlSchemaValidator
{
    function constructor ();
    function constructor (schema : QXmlSchema);

    // Methods
    function messageHandler () : QAbstractMessageHandler;
    function namePool () : QXmlNamePool;
    function schema () : QXmlSchema;
    function setMessageHandler (handler : QAbstractMessageHandler) : void;
    function setSchema (schema : QXmlSchema) : void;
    function setUriResolver (resolver : QAbstractUriResolver) : void;
    function uriResolver () : QAbstractUriResolver;
}
