/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.core Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qabstractanimation.jsx"; // QAbstractAnimation
import "qt/qabstractitemmodel.jsx"; // QAbstractItemModel
import "qt/qabstractlistmodel.jsx"; // QAbstractListModel
import "qt/qabstractstate.jsx"; // QAbstractState
import "qt/qabstracttablemodel.jsx"; // QAbstractTableModel
import "qt/qabstracttransition.jsx"; // QAbstractTransition
import "qt/qanimationgroup.jsx"; // QAnimationGroup
import "qt/qbuffer.jsx"; // QBuffer
import "qt/qbytearraymatcher.jsx"; // QByteArrayMatcher
import "qt/qchildevent.jsx"; // QChildEvent
import "qt/qcoreapplication.jsx"; // QCoreApplication
import "qt/qcryptographichash.jsx"; // QCryptographicHash
import "qt/qdate.jsx"; // QDate
import "qt/qdiriterator.jsx"; // QDirIterator
import "qt/qdynamicpropertychangeevent.jsx"; // QDynamicPropertyChangeEvent
import "qt/qevent.jsx"; // QEvent
import "qt/qeventloop.jsx"; // QEventLoop
import "qt/qeventtransition.jsx"; // QEventTransition
import "qt/qfile.jsx"; // QFile
import "qt/qfiledevice.jsx"; // QFileDevice
import "qt/qfilesystemwatcher.jsx"; // QFileSystemWatcher
import "qt/qfinalstate.jsx"; // QFinalState
import "qt/qfuture.jsx"; // QFuture
import "qt/qfutureiterator.jsx"; // QFutureIterator
import "qt/qfuturesynchronizer.jsx"; // QFutureSynchronizer
import "qt/qfuturesynchronizervoid.jsx"; // QFutureSynchronizerVoid
import "qt/qfuturevoid.jsx"; // QFutureVoid
import "qt/qfuturewatcher.jsx"; // QFutureWatcher
import "qt/qhistorystate.jsx"; // QHistoryState
import "qt/qiodevice.jsx"; // QIODevice
import "qt/qlibraryinfo.jsx"; // QLibraryInfo
import "qt/qmargins.jsx"; // QMargins
import "qt/qmimedata.jsx"; // QMimeData
import "qt/qparallelanimationgroup.jsx"; // QParallelAnimationGroup
import "qt/qpauseanimation.jsx"; // QPauseAnimation
import "qt/qprocess.jsx"; // QProcess
import "qt/qpropertyanimation.jsx"; // QPropertyAnimation
import "qt/qreadwritelock.jsx"; // QReadWriteLock
import "qt/qrect.jsx"; // QRect
import "qt/qrunnable.jsx"; // QRunnable
import "qt/qsemaphore.jsx"; // QSemaphore
import "qt/qsequentialanimationgroup.jsx"; // QSequentialAnimationGroup
import "qt/qsettings.jsx"; // QSettings
import "qt/qsignalmapper.jsx"; // QSignalMapper
import "qt/qsignaltransition.jsx"; // QSignalTransition
import "qt/qsocketnotifier.jsx"; // QSocketNotifier
import "qt/qstate.jsx"; // QState
import "qt/qstatemachine.jsx"; // QStateMachine
import "qt/qstatemachine_signalevent.jsx"; // QStateMachine_SignalEvent
import "qt/qstatemachine_wrappedevent.jsx"; // QStateMachine_WrappedEvent
import "qt/qstringmatcher.jsx"; // QStringMatcher
import "qt/qsystemsemaphore.jsx"; // QSystemSemaphore
import "qt/qtemporaryfile.jsx"; // QTemporaryFile
import "qt/qtextboundaryfinder.jsx"; // QTextBoundaryFinder
import "qt/qtextcodec.jsx"; // QTextCodec
import "qt/qtextdecoder.jsx"; // QTextDecoder
import "qt/qtextstream.jsx"; // QTextStream
import "qt/qthreadpool.jsx"; // QThreadPool
import "qt/qtime.jsx"; // QTime
import "qt/qtimeline.jsx"; // QTimeLine
import "qt/qtimerevent.jsx"; // QTimerEvent
import "qt/qtranslator.jsx"; // QTranslator
import "qt/qurl.jsx"; // QUrl
import "qt/qvariantanimation.jsx"; // QVariantAnimation
import "qt/qwaitcondition.jsx"; // QWaitCondition
import "qt/qxmlstreamattributes.jsx"; // QXmlStreamAttributes
import "qt/qxmlstreamentityresolver.jsx"; // QXmlStreamEntityResolver
import "qt/qxmlstreamreader.jsx"; // QXmlStreamReader
import "qt/qxmlstreamwriter.jsx"; // QXmlStreamWriter
import "qt/qt.jsx"; // Qt
