/*
 * JSX wrapper code generated by JSXgenerator.
 *
 * com.trolltech.qt.opengl Package
 *
 * Note: DO NOT EDIT THIS FILE
 */
import "qt/qglcolormap.jsx"; // QGLColormap
import "qt/qglcontext.jsx"; // QGLContext
import "qt/qglframebufferobjectformat.jsx"; // QGLFramebufferObjectFormat
import "qt/qglshader.jsx"; // QGLShader
import "qt/qglshaderprogram.jsx"; // QGLShaderProgram
